sprite $Anon_Proxies [25x16/16z] {
HL075iKm2CAHeV_-z_rLUIqTSO8H1TiHnwNC6zj0MFmQwUKyHang_LuS0BkCnP8N6v0imu3c2IMT0gS3qn02kMmXXHVb5O2P07Ja7ZUj4nhi7VAkIxgfNMBv
93OrUmYIbdb6oZZ_HsLJUQXPjmuEOHJvDa0AEETlCiAvH9gUfFlsk--fKtpVoxN_0G
}

