sprite $Anti_Spam [34x33/16z] {
VPC9ZiKm24Cn1EZzJpmJdXJrRxMaRhnYPxExV5LVrzMrP5-arTqNwgwmTmNbeov_RP00N9hhkWF5Vxdw_ngHFNJQqG0TPhu9tw6cpq5olnM5JRfsBduQ-JPE
cRaKQuLCZdEtZaUPYJVa6aTy0cy0kRj0ACXeiKEQ6LNDrQcacRetEG0-6CffOXO3IYz1Q2A8DODomqTR81vUG-GUIPM641xpm48qSSvWy768Q_H6-1U21nRZ
gmj4auCPSNzB-ZvQBdZr4FSPizSPyo68kanE1G0yfpqsBQEghVlAJT_gMNr_MtsTrRVWSOpG-mvYIdBILNVdxkPrJJwaivFP4kyx6MIO5KDm6cXxaBmUJXIY
xKqTtqxs_C_jw_5NPADqUz1xyGy
}

