sprite $Badge [57x72/16z] {
xTO73kmW30HG3BPdxd_Y7wsrRF66cD_RgAIWbsBHsdUEZdawTCDrqkLs9axsEdGUqUD4USJBRl0MAE9aL27u6Yyw9Oc9Awyqt18_QCyo6cnLamYajGw0Bpc5
zlPjoXq8tAlHMORnBf7Mt4Mm2-Db03UXw1ZEI0cACI1FOtB6Y2KazPqg60rj3GbzSIESIPmkvSYTfaU1rl4qT6C4ZZNBmzgAhxHKLSHdT2mTvFEm7rUb6UqZ
X9ExKC1AaA2n5aqpQJKzpHh5UEfoAPKk9rg6ceTLId54Thza7YmboVASymz0_mQ88yp1aGLi8ks89gVHkBsKOtVpOFNDWuZCAjcz0_jiENSWUmnhxxC3nnrY
1U_Fj_SjcPDSmRC_6Yp0-KaAdRzm3USOxo29-5Db2K9YrpY7lA06QRFpp4rM3H9y3bY3EJyDOc0VHd45-p3cKF5jw2tYHPYd5ol2lB9O7OQRqIBC0slK87fU
o520uPAyX93FBRY0BcTDZXMqHQD9-y7vdoy
}

