sprite $Check [96x96/16z] {
jPfN0hGW30PDptV_0_-zigAOuBnjcoXjG_1OWqJD8tyGRYfqx89OFV51kZBrvMA9AMcz-s0Bt136LRjuOe5qATa3oyJZ2EnuXFCJEnaUOxH-yO42mOjwHH5T
iPEZZ5ElRVfjn8aMoGLz9K1TNmymwki1wlfw00fi8kZCxzY6hytQEbfi_7eN1BOIbTQfjn0bDfEqS-naNeuXQTg5E30Yaywj3HQAUHTBTlLd0LAsj7xoR7tn
OMgLzKE0yIDhwgS1R7YtlGwGdwoZqjNFLp7fDK_opI9la-Ofwoa-6eZx-laooUDRVVsuYlfc_JZ5yaKzyg1jUiC9nA_gmVgg7cepHyG6FSpdYRmLkdR4uoB3
qxOU4LS9f7RrYBpCJxMfH-Pr-gir_UYVPzTQqy_zGTEHb_9KZmmCoCHGqYFYlWErhaSu1YQMcXvkYoCmkQA7wMbcFK9C9JsK5xT_DJsO5fQOkXvqv3n0Nv-J
__VWBNhuyCtL0BQ-osCy3w1OXEVvOL1V7tHnhqbTFUmoFmzgwY7N-ukWdZxePZ04T_Ims_rTK4EVVBy_3IhhuIlbWQ2g7h9K7mWkwcErlc72HCGIU8IiLwyo
CriLBCPsU6L1h6EbucgznChO2hzUNnqXnpQSNgvllrsVFqToYrwE6O8Do357SklLxm-GylBvsjldW_t3sVuHhGGAXBn-lhmEHwrZrz5uODVZEQIHM213wRqd
8DBbQC3gUILNtl48IkI9EqneupCqvf6_pMxAY-wl
}

