sprite $Device_Control [34x34/16z] {
pT570e0m24JH8Gtc_WUsTmMt-LkUfa7Y065SXXYYj6DH1NFYYigoJEY9mhmC58ueJ3lu5dK1ieDTl80j8DKFOIimcG7RXz0dU8idU8idU0inhg0wPp6QBbLu
GeENIwf5JNoHEIVmXSx0y2SOYJg35WaqKiKNUvqBQXGpKE84_uq
}

