sprite $Encryption_for_Cloud [45x40/16z] {
dT05TWGn30DGcQtx7xYq47SWVQz_CIHdZ6kYxgw2lrcHvEFBi1La6XuioTYaDkDmjk_IauK3gPlmOcuJfgJZYZEtSySKmm4BTugduxWbZCtuA2WOdDYXOwZ4
JXKMeM68PWS68nQT0sc61rjccCoJfxuQ4mjjriNIFNwUw3URcUVEzzZiZTD9rl4QnpkBkwaeW9YLGPtT400IxAeYGxoOE7PZFe0pvN6qQAOOl354IOvIHiVK
WKK4sO95EPDbZQHOHIeccuNhFT17ISDlbLTbHkGaoP37louyMU9EjRn_7bfmAmj0lKjx1pPQqMElOCV3rWuAjZHb_I_ipGqMs9iRfB1NXeM27IyC-sxu8IiO
AjUqwfYaKU7N1F_t2G
}

