sprite $Encryption [32x32/16z] {
ZL87eYeW36kXC_U_xrFx2totSPlHCEY0fwgh2jChY6CXz8cTKOG15W1Ixca3e8E80IQM09pfmDVlugzG8Fb_UkMDqPzn18QjFWWWkXem0td7SY0IMjyJHkJZ
tkv1YWgLayrgxhed9Rm6hMupGwT6xj_8Nb7_r9RP3fYt-0vFtRukup1I-Dh_Kww_tZY3QrKotRpa2Wfo09KNPuK3NEb07B_BlRzvHRVLCzzyvJi9OlMVExwZ
34O3e0x8qKUtaWBptoPikOofsLUZjyuGkxSdqkUk0Q-vjt52z-1RZKgkSpJOFPrE0LyrigKR4qWaBt7Vltl1iOn4pcuelSOx2wyBFwi76zhGw3lied2nGAdl
mOw3EEO3dbxxuyBqEou
}

