sprite $Endpoint_Web_Protection [36x37/16z] {
bTC7aaCn20DGOOp1wFxttVbiSTd-fgKeH3WETg9Zn1YzuHjYa-_IlumDda9mqIGvhU6XDP66Wv6CXaMSfD_VepYr9ESn9GMV11aVNMeJmwxMZzKfcJr9kcch
Gr9du95amyCghSvtQwZm8vnuI3UFPCResp8rg9EAxmZfLMpYUqu280tVKrAXfE07v40dyHCFXp7niu2JiHEBWo7XF8dpu4YCU_NAk3sYCXD6ViueIgzCe7-H
cK0yiZ8E8VkTSUZMfmEJSMSIQAesAhD-siNNRMzFPjsHececljsXh4mDgZtwv4DN5M2-ZnHorgSptBg0f3qQm8yUniViwpgiQcFLF7eRjzFvC5VlDRWYco2p
N_z-ikCmQjksFtV1fKtMQc4HcGff-48FBj44N-iZWZFS1F_r0W
}

