sprite $Flag [80x71/16z] {
xTA5cKKn24JX0IAG_WlUZxkkF9drd0B-2A1e9zhwcEuJcVXHkz2oxh7k4W3GTJGkqMmU5iUJdXZBqx4oaYUfqRpKU9xDrrBjoTkOTb_h4i-clIJ5HcANUR2r
V3HJ5L6rrkU7Lkr1emJEyY31zI1EzHBaUe2JFKooXqdsu6HFdEj1Wkj1W-l1o1uwsOEJFILxSB8NN6yigjT-zFvfCBtaY5voH2yvfcSL4kupyuZ2gxZmqLJm
aABqsdjMKdXLvVLtB1DabLTpCVjxLksDueddUU9FgDcAQzLUysoERbfGXLVsyxtjRMzxszlUzcGUDVpJRW
}

