sprite $Genotypes [20x19/16z] {
XK-55K9136jEQjb_Nu8xzEj5N-qyy6w7FKsoc_a4RRgPSpzYqNg1yOGHRzXY0C7rfqEpCvzL23UD1-xOvBc3yq5urLrzZqahSyDGRDBFa5E7WdC3gQ0n59l0
fbU97oAwuHmwL5qm1td3v3N4rHimUL6ilYuVR1qXKVU-RTWjwG4
}

