sprite $Globe [96x96/16z] {
r5U74gHA29I9WF__lU_TwLPf2xY6cmjTUMQtmIRET0b4kJPcqHyGxgrccduLA5VMsK1xJVIUl7IPGqXxznsv8RbluYbx0Lb2A9T7x39V1kVRol1y2vnkHRND
jr7fklCoFu2a0Su3wXNwnFDZT1gZpNMDiiR_BJajo2Ufg-S6oXmZN_gPvhlqt5RtfnraeMfopq3skcJ-M8KcK3zVbDcJwBhs_QSp2uTY3g-tJg771fBOY6vS
RGBqvP3yHYNabPLnfD4kACcHygCPTVFP3d-BuiIUIxHeoL5UL2j-L2ae3xgZe2s6mFW3OCASpRu_6GpW_m7TNCEDaia6nSzAVAPGZgqB1WpjIfn-e924-KMA
tc29AOK667xh1mVbHsHpaQ9-HO8N9ayaHUNOulR5WVlITgYwTZ87ourKFDgZR9Kx051zGw1voxGXQ5kb386GbKSHS7ZbpcPYXnD2y5hEBjRA9aGv2fGKGuvW
w0w8xlv33W9bBsMnyjePFzc-iI7XN56_IAlFtznPIE0lVa_tkt3n-Qi_p1a8mPoT8Wh7Y8BhZYUGODCZmmykNZEEZ0Mi7L60_w9ukbUaGRhw_EJp4_3x0IZz
TAkeJ_Z1PO7m-lpJ6NyztPAxGZMu_385qE-h5CDQPo3RkOFFk3iUxpbb7edn_FflywC-maUivjc7h1uwvni4Yjal5QNd-S-ZwmkQnO3-CBY_rT7z-No-bDVp
vSjyn6D4_ZuVzSryBnVc-vlzfBfF3n2a7lQhV7M_mlqdtg-6xuUebwPB7B5jbAEP3-A647X-UGym-uSDPVZxOlpxQFpxZcGCFsyf2v0zuCZU_5-hUI195890
T6W3uFtlktadWSBFERLLPlivxAFxKZF-09j2bFK7TEPlAENzZMegAxUrKcF_c1ek7BtGcyZ2N-Btrg97_f9rCR3onzWaWDyuybI-h_qzVlFti8n-AwyKMDj2
B_Lvypi9DFD-I-YlwlydQbBBF2qZ9YMa4oBKl0Z2NSO3Da9kTyDYipSfDtgA9Yb9STn__4Q5QPhlzZCu3m2gnnVW5E4xSW0F7wJa-SYGzdCMsyXsSJdDJhu3
6vC9-Nm0KW0Y8g18Z8zY07OHWuJkbnTSopSfYQvtnP7c8JPnIj7IfiiGisucy4qtgE-PGK3P4AJjdxmHflJWUZkmeF5OYkDsT47nEQ_qyoRH46fd7R_2Ajmh
ajgV
}

