sprite $Heartbeat [65x47/16z] {
fPQ7bWKX24En8UJ__tSB9pEwrJcFxBwkLnAP8W-arYMZxl2I0HY0cfXVFGaOI08i2QYU10ma0PO4L2G18mkm5m6LlTi0s0uepr0JtkAD0Zu8eAFnpBZhvK3x
0XG3J8vg3c1U3Xe1_FpWo2pHUtuvA1jWdWFbA2xam1G2RdGx1S3W6nriW1xeSGvWLWSw7H2mcaB_3y00ByM14HMh4B3Qseu1j5XhqW41t5txlWqwlyZ2Ot2C
3cv0K3i1XHFL_AlWyrgiXeC5Y89ObKn7Z3U2bhGmRrUE9I0AYbmwjog6_tyQS5c0Y9JFDHhat8tG3T2tU1db-JpG5Y1oPRoAy77kPvCR45MFTOgQSf3ImGs8
VU6dim6EQmiGtXdlsG0ttHQhr9Z5U5qVdSvzR02zopQ75Jbh-2mtm9i3oezcJHxhQrU-8WASYRm828qie2O19ab0JmAy905Jae2M19Wa0Pe2-A49SdVhxm
}

