sprite $IPS [34x30/16z] {
jP87heCn38Az2FS_STi_acFUdlqq7M42akqbZh3F2URJ5FtgkRWgMZs28dP8Dl1jXv4imefSwTi892p8C9MGaY3sx2Ou2LEAhoA3zQRKUcVyP6b22HeaHkvv
j2acrMfVvFXnYTyfNL777VIz3w35IUYVnNHtsxxefr3tv8K_Y55SspuZClD592VZIfjJu0HqzQtpRDFy74YXpwD_QtTx2vWlJ-WroQKZLJ-fXNWrJoELGCQQ
HkhAz3b2ST0zBW2hZ_qT4hn0kls8Em
}

