sprite $Location [49x73/16z] {
xTKtTWCn40JHSK3F_K-iYEiUYZQIn1_IrSBI_eulZwog3BSTyvfzCzCVVrnzfBAxKdsbC5Qzmf7HQyM__z8tijbg7AvcUZW0IGyUodkd2ZEBeTx8ZKSyRc_w
x4tQXVRFssx_niGd4io4qvmcF6d044JbX4cTDBQ2Bmmxc_36-r_Gau-KC7r1inIzJkyhvvJkM8R5crMnTyNRDNgZFAmc7o7rJYCZXtetuKIZD3X1G739eBA5
QEQsCfiCMyecOMlgjMcWU4vVIkZrwnuv1DY008f5m0t0uWq3b8009330YJ00YMaF9GIO880I0aol1VZVY0a2g2301FiQ5GIO880A0iW50LI20F5X7_Zw0G
}

