sprite $Mobile [36x31/16z] {
ZT873gKm34NHvxZU_IzuIeGGaJBb_0gu8lGNwthIzE6a3XRDLlwUWj170dJt0BElH6h1-bI5V0wzO4m2bzDwn5dK2fOMc1f_Gro705DGCaQIpgvlyz4kKhYa
jzuXo3tDelPHwQAH1XFi0zE54qfYDpD6LxjHAyZzkIeaPW-KkAw2fK56grYwSdmFplmhniJyLwyWT9NOC_FUxsfcp-AaDEXcFVSb2Ib9NJIctYEPfBbjvfGC
ziYIWhbqmbJ4krBHfeE1Qp6VQPkpdKFikE-m1Vr6hOQGXZmV2X-WufVYYU-MXZZgDuzwApObdLP4hALNqFgdClstdm
}

