sprite $Money [99x71/16z] {
xTO7SiGW38LXFRNx7pbZZmmZnzj0s_TFRtmWPmjzMxz4As8watb5Sd-2NvAe7vJmNA2B16YoRoAi99mZlAGouaU0ojiJz344IZf7m4lw4iAckePGcWdt9-XQ
We_Ak-MZhYVO3z9C-56O8fHoA2TiMzcq6xK4si96aTGI6e2Okmh7dvSIoFks5U528Wx1-szK4cWhchlsKnKIxH12RaGYj8PfGgsF9VPC2z7pI7MCG9k4qD8w
e4p47fY8HmWctjRWTWhDXCOE0D81Wk0Qnq2Vl2LY-x4PuNP2YLUc_qaVMuizDkEW4KBSsq-IOPm8MpumsI21H12q7oGJ622CU7rRmduqpcbGjBoDN6uo9jqJ
S9M-YeIdGZn0QB_vSY98cwhziSIE2SJZxI7X0hOOVIQugV5p1SmJaJiaSfO9sKu1xqqHVImc2u6s2XSIqdvh6qtCgOwmtPujXbP6nDM5xHx9jPI8RREeks2x
ygM4o_ydELPBz9kVRfZwJGIMpX9XzCHl8gBpX74MfeY9NeOmJ7MPcEvB22k9NgrVVm
}

