sprite $Multiple_Endpoints_Secure [105x62/16z] {
xTO7kg8X38NX9EISx7_78s2NPmXOfbnVU_riuLU6lhxK5iaUvoh83iDwo6L3OQmYP8DjX7mxv2NBdmkPf7qgfAyBQMULFh0QWbxR2Cr_XGm-WEw4D1BcOpKF
MImZTaFyL2XGifnFXOga_OiXFJ8TC4x6AXrIi8cAOy5hiAqGOuvtz0sXOTOsGrpAF14AUXhZcH0apV_XaEe7GbeGPA2yELGYl82rLjuPGhYAE4JKmzyNydvl
Hx-xlojaOQ87W1v82Kk6ocA84EyBG3321Po530qP4GGxaByFMQWuzOXUhvY403PnQn9ozaD7huT9oC5un4a8C0EkBn6Ja3e7fg4umCqbduH42WPc8QWwvOXG
vIWqPudlg8HAes4YB6y9MOqGqf3jYhU4MaI3AcAinu2iXVHchCu6AqCHKOPxG6MoCepuPQmO5wErhaWD74-Ah8VYmIWaVbczaLgzqsE5n-KHn-sHIIeq7wjM
mk2kF4XiOVDwAEaRQlmoLqIMzodqTbvIZDtwV-y8Dh1iA9v254bnFiaboS1Dendx-le5
}

