sprite $Notebook [86x48/16z] {
vPO5aYGn30H5LVh_Z--iYT4oIiiPq6rACyZFH0CJ_74fXuGyWZD7aF88CRRg9rlvBbwoXhu7lc1rUGz_mAeU_t7Rj1egZPdmBQiY2LFGB9Ym5Qiou-G7jNBH
5wnQchQACMrkHKMrjQhHgTKpnED0ni754aEhagUvX-jsLucqcTLF1AXDK4KPCsiD9Y1DL0HdLa8UiKRgnAg4k_EsDSCzqcRMYhnZBS7G2ZExsrOtYxI5SUMz
wVFHkBQaOwsh6QzNxN6y_6d6mjxg4yPOwP6sS0xK4GlLo6gp9RREh22Pq9KpgoJfSdSKRFikK2TzxTuANxst-eubL-_OGYs0SFqxBwAvLI_Ctw-cnP4Rh-I1
x-9kMOZudPGHRL89vZB7QkIs5BKXkOjBWLLSFef_
}

