sprite $Partner [86x87/16z] {
xLY7bYGf3CCHs___mVUwfYajLKmt4rwukzNkP12oZ4bj0t_n5oJglKT4T3Tb-WL6zQmBmeL-H1crHdPftmD3vGffz0sTNi1lyLe1qKsO3h1QpmAljYz0qBFh
JH1RO4Hkk_2p3oXda9tZRigb69p8Cx4ym8nHTF1wsm0_M-VWP8MLbU5A5--3tbiwAw3X8G1ZgDU1f0rI2ELUQwH_4EaMhI0cI5d3uDShMhJfiEq5Kf3RYhVP
TmZz76WOKB94HrlEsa0GQAsjeHXKQW_93zeF1Rms5SDBxI8PFL_4p_kaoBukFK3GYeWs4KFHSdh5QMhKbs2d4FyaLOmvjOjEK_UhL0mc-sfJflvBLsbQvZRW
18A5i_qo5Dz4HNUpAE0ISjoNSBgqeK3FwAx2jDvuPKvCDE3-gwYkdkkDIVfIBGqFWJxBz-f7Gr-lywH7-n3EYXi7aDCuKadDZ3cJsXeaygn2c-Bj3U3PW2Xf
FghyDGmUqD7ZQgj3gZUPSe5itP3e5vTPuPCbKOGMgFAqzVAPT6L1Dt1mUTE2L5HmobAi_XcnpSbA3CdF1IQL6cckQWcmCqCoLnBbdpvdOe7Dp7NT0tpsv7CI
87jn_k3DTqeVWVAL1ZyY3cdnVfa2-caiGhv9j-AMEqigZBNthBs8DbPLGAk_PurgjBC3l6Q5pQW1yjoLorxb5vh58Br2NsvUdjW5kLVgexqHGhukMMojMTTA
RSlPzUncEUu4d5MTcsOHgk1QiLIf977q_PJMS6tIPm5L9IhslhfaLPu7itIsfQLmICVOVR38RIMSz8N6aRlqNAQA-v4R7Qgn4jvMRRqUIdhIT48AwUVzHg9i
d9q9gpQGmzYSzqyw9b2aIfu7OObpnfuZncg7QVtKDhDAj8CQvyJEhMa-2KW21c0tlEtSCiqXYaShZ-dOuVGnjmADavOxD-LmEWh8oY6rsMLkMGXowwD1BAwk
VH8xMbdWA6cuv0pvGs5U340BFfr5Q9HwK1D5oQWh8bE7zk5XqcSdJRvS0lDm8VWHOnwnPyNKAj5_VO3doK6KZJq-zL5NF4S4ssbzWe_ntUm29p_6FLDANe3V
J_20N0xvGCOnMlXH0Dmovr1mstXvC-AwWPiT1S1ydIMu6MbRW78CY8v0ZiAIl97Agmkoue_eUa7cNIdZnhc2moZExLiH1U9VueitUPkk_siW-tthTXICe63g
2WoxtZpgfOttD7JOVStnDq-4LZkaI9FJvu-bNPvj0wIRjAbus8qyHU99bmmpuIsG_T0sF-anq-AbqDiUxEqBAtj-_R6KOMOeltefxVJTLztifX_FkYpm65Fb
br-WjNqPoCSQeUsRa9wrH3gt7u34uyeOnktd85RpVi1DkFsty1V_
}

