sprite $Patch_Assessment [40x41/16z] {
rPG53WKm349BE-N-1_xDxBlxYx30t6GFw2Wev1AHrgin_MMzE2WiJJFhSC9UFPwb7jJJHc5g6bcRsc6zUcP-ZzSxv78zJCMPUcVkmNuzaBCULhqH32Dn4aJt
sSdIAfTY0dWAfwk4KbUz1ixFZxXr7VzHpwAJo1HL02WwRL-i1uxTlCzG9v2cwzoMeWSEthlUOpxqFX93KsDUmIFll0pSRrh9uUI__oSleH5D4KqUOmC
}

