sprite $PC [82x69/16z] {
xTS5TiD034LHyP_zRxXeffDgLFODquiPwBUG8Zps0bMKtWJgl0qbev3yhg9h9ziKct4dFIpUHOzh_k5YD5nfgQ9kY04cRqzonU0j0NHuaYh23fPY7vvaYa0x
bopwkMIHJqcoA5nV57qnFCoaesWDWB82RG9eHJ5i4YN5vU-zVM_nBjv5m6FWG5SHGt6XhoYlc5bMVjRMx8mcYt4kLMpNUwv836DSWN_9aTHTX4cdeVYlpf3S
lRZ893-xk1th-lDhuh9a20tuacBYV8aU99WObQWlAYPE9GoJe0gC1Q42ZeLWwYM1DKqqDMOu43DBZEQrk8ldr1zcz1MU0G
}

