sprite $Server [49x32/16z] {
lSy5iWD1489Xe1jo_nC_ryvQz2jT-QS6VE0H-47d20jVUk5ZU-4blZX34oJb3FZ434LLuk8iY0yw-z_g9AUUHmaVQfxJ12HLStognSqD4RJTDM_RYvkhOdtV
sKkhCuDJLzwrk1Hm1leAMbvShV7Ip4VGIYaBgok3P2MbcCx2QcSYGNNCok3b809KOkVCz-R9NTLPG42vW0MmBa4yWNo90foBN1pmSE3oHK43w4i20T13WmZo
Tt29omFeaiA5Yxq2
}

