sprite $Smartphone_MDM [35x50/16z] {
tPG5igr030LZfzd_Yh_aEYD5wPF6Gu-BNSQds9CG2nJM51mB83iFG3L5G9YP-Z4deCmCP4lKFpbsoi5tLYAhCZPA0XAG2yL5UhyKyfdY7N_QFb6GMQXnSsbK
2ky8TC39J-KH8lqVIISvAz654zRldIPEIia-5IDFYkgig2ugrmjQLtVVw6JITVRPTJKe7GkQC1C-A1QKFId2paexYiTR6wDYBb2LGBwSc5xwH_g5wVtxbVqk
HIi7Mi3nKDwWwkDxL0YpOAkew_YkzDmV5CvAxWjA6oeZ3PdqJ5hod5kH2yAkyHS
}

