sprite $Sophos_Quadrant_with_Logo [114x114/16z] {
xTc7OgmW48LXEOUX3DxtVzqRD-kage2a-wStFrhQxlJvmVSbVNatYOIUEhyiY9yaYBS1r2V1eoD_4ptRWqHE7J7qYhp4ZIxn4l7dH8bXf-Y7YqxdtU9m4Jed
2LlbEGqNMMO_RHRdF5wSPswBOLOtMfIvx8WoAyw8kFTS34_NHCnhAjCjFnTsYiQz5gEj6yfi_Ojtf1JVAG8ROhApaUUIk0OJfKi4jaHdvn-b54olWiwXGmHg
HVzQT3h7PX7O4w5blMGkHTDIZ89Lp2MvHX7x8hM4frSjzJQCt2O21w9_TZGGqgsiQbkQIaQBY4DHRFEUvTLc7ekoGSIXw48fDCbAglVT3KqY3aNdmdjpH5OD
9dfNAw96bBAkdu_XiPXopihrv2YTgnDH9L8rktN7rXx0OESter94dUZIke2IucCffUXjGqjmTI9gHQ-gd3OAHJD6YowMJL9KLLoTY7eHIJLp2um6xeke48ra
LbLlZXKM4CD58uDxwI5fDl1GHALev7BrnEUWPCqQu0QBHY9eNW2xTj87KGmy4j4eBlbyCvpzXQM9pi2Hef4CETzCt5-1WOSYcaGZdO_vePIN0fs1uqKZiPXB
aSx02X6LugOP20F7YqO-cOI3WKF53TCoRxHexO3x8ff5QySRBLextcZHCc-yMDabeZ9tIfIUGX3VaSWYzXINfuxMUnywwlWo4RdFqODepVde7LeZlFIU74Zm
zH0j-SRY9LuYTqNsY9V80v4ZnKkq1elyZYA7YloU8WUA_AuYXudyR97L8ZzVv12HBI87YFpk8a-BR1LvKcIxo5CYUqIU4DadSbUKFR1NPAV8Vf7i4CbJ8fj5
dXNP9fBdHR91v1YHh1J9OI9P8P93HN9V93bGjBP4MaD5KqqqhL-iRn7Vmoxn4Y-HVqJa3zf7wIbqVjaYVcxUJuwVc_iF
}

