sprite $Sophos_Cloud [71x68/16z] {
xPVfOgCm38GpHzx_aVS0PHOSOTpqvtPwj-w7PWHo_FXKFm90ai0t49IVZaHym93_wXdvhxv8OY6YeBGEmejX4Rj8rQ-MGTeX8jvyxY2k-TdgG5_dNj0YfI2W
L6qISGJXnj2s2ZjZ2BdCCCRc52M8KLOLL9mPXVak6YlIr1TV51Iaan3E3ONFcHpErKstGgbBkP9gWr4eInpsbdnFYI_qjlvQGfUkHTJKY5pnSAImBBdjSDQK
QgdT5DDPKit06d_A7x2j7Sj1NumE3xPmvBWjHtvT8B8tYiuDKdxOqq7doM4G0CwKSxtUcwNH4m_5n78euI3fnDNeIVzMF40Y_tDC5igbEBXIF2M3YcTG9aLS
yHnDwWsmauNYrB9JE8acFRYMKHoC6CHgLUdd3OTrkLF6S19sYcwLNhl1qC5m3edjEQQFj-cN9fZ4-na6HuplCMmnwTGIfbhTF0qL66BgrXEQ-oPtyUlpH9cW
UHZQPmft7AjIqFlyOwRMPXKJLKlQkOM4azzFn66AzjDFc900-f2pEPl5lbQQtirY39DsgUdbgIa7YnGZssQxKMaDmspYJJbSjQLk3qyvnXgdjcdhSVtA1Bwd
p6unLppm0iMnD0h5cUPSAnnBhQrQnUjIMBMaIpCET5LAA7ZCEKRxCZtd4TwV6kXaDxxSK_rMDvJal8CAHKaYSJgRQE6G6L3tjvLpMOoL2vmOT4w9Qr8Ecn8t
AKTDyul7v_TE1R8kofj2S6_dNYXK3flVK7QL_q-_0G
}

