sprite $Sophos_Cloud_Badge [55x44/16z] {
nTL7TkP0201Xe86k-rzu0jBuAQ2qcc_hLsx0uPThvfuPRYhlQV0ZJLvATkQhS50ot2CfBe-Y7XZxUUFLMqCsB86KMmPCRGOOqj9rZwgw6rrkj58votOzfSph
gtNVJYVWLgDEQNdpWv-rqBtpsbOJF1XvN3pQXVf1iUqzv1qpqytfKxwwF7hIY_MBvD0soqvbOtsgpQIXbKq8-PmP8D-p0VcGMRAAdomW7Z8uP_xuca7QGhT3
Sfyvs6at1UmfYrCc2VCsKs3c7p4scG1JRpBnvYJBTcJuaVtBH8V_4S0cgwxX4XmUHojpAPeqKXnjCcF8oZpFnF3QRJ7N8GELUuakbrnPpPZomEh6kOfwPQBo
9AhRIboUvRxJISWRkVsaSLvMspyHJN1vooQCfPyc7mHCd-3oZIOGAf-Pg_m_lm4
}

