sprite $Sophos_Quadrant_Logo [58x59/16z] {
xTP5Wkim381XYsnByltF-ngGIzP0De_ctpJq1PI1bkiXovKOYqYzad2HIlZzk6uIolUZNUAVBNyaVDW7alJ3MYvbV9ZbiWuZp6h389LjQ4cJOPZA_f5aTqgb
ZbuYfEZSJ-wSIT3Hmgdxos3GXsGIRTJp73Q6wv7rkQrcakPPwyr1YQPikNIEKNczc_iK894ofzVSppSBvN7ocQpkzpdUx9wsEBovPRAvnJARpnJYn8Q9x0zZ
0P9RBCtCwvIqb00tMTwwKPq_HBoMg2ifZrAIQ-gyMpX3P3NhS_G2i9GjtWhgp5IDOmn6Ama0ukVfqMPg9kV1Peh9DL7jE3_8FOxTQbuXaI1cCVZbZ36LsBVT
IrZDZ26LG7gZjBwYrO2lSbAJLuSzO29FgjRW2RBUuKe6xNR3V7VOjWq2dqh0gghMukdbngnJmAKC2jpjXhVjSp7WKWQDozw0xAun1CnbKA2gPrqmO2g3XWqN
C9Ml5gas3XSmaq739YwLTvl1N9RSvJBANIwZtEKoEjtFjpUuB9c-dyXDIhsGC1VaIn7y0W
}

