sprite $Support [35x33/16z] {
tSv5WiKm30DGoJNT_y9b3Wok_jkqIGp26z4Z5hdm0NKQQKA0NFw80YCL9teQNePqF4ZwkqBBiVviKHJus1ME2acvhK6LNPsfg4iv1wB1xFLJOc8JWfOWLacq
kEmbQ3B5J2rrXiAWgX5AC3SeHAxa0qiM6lYA-F-Mw8pT4kxvIXB2bJPBg3ilIWhyHedF13yt0G
}

