sprite $Swap [97x96/16z] {
nPg7TYqX24L1fHp-_tzVlUaEEfAoLqqxUyN2N75e3sv3r1n_SLCPZQdCIxOwuZrm_GmBTp745J3f9KSJ0o83C6d7yUgnW-kHeXbY5zXj1IlY3b2cEmp4NJ3k
37wSi3qLm-CC7xG12-8K2A_pBIhOoi0UDJmtD8ygtWhvLKEUNpUmn-VWN5W_XRKayNd897z4HhqmDPnc8IQWqJii3h4nDTYd3P1Hdne6lOPnBk2v0KolqAW8
vWQb5pfAWda0Uc66Nu0nNHXizGy0lWPwcO6UpG1CUjk1wTAWoHxpmNIJZglT9ka4xTCmBqbioIwf6HuBO390j4rU3peHaI2fjhLPW5myntez_-NPrj9QoslI
tTI81gxh5AilqImVWqZZMY1RfIAh1ahaYS2sYbsI7qwCHE2LQlg8Qb4MfEM-ZRhWANzg6L8MFEUFcK6qB917VgUPGAqgm7F-L61U5BpigBd0YuAN_1F1m7x-
WU1M_ebWFx_JWM0_FvmpWKq5B_bLWUbSyCW7gWALgU0fVrXL86CcqEVTQIWAHazNHrtG69VvZUe2C7cINnSuaIRvcmAw5YZHIFiDkXGW914CefOUSyMMI7QI
R4Jiq_m36FFf4Nn2_lnZEkJb-uNyf9lIfsqYeJDyCa9JCmOTa9mpEkedgFmSQuK-TDREjHVvfQ7rjgJteHxfKTNYog3O8QPOFduZhqLhq1Vzhb4KsB9ZDqe2
j7LFKoe2sMWAGiu5jjNMX5XvWFA-8n1dp7QgnkUXFz8Sf-RnENZRR2WL9hXWAEGdXaB-Py-3jo--g6lrYzxwfUz0_M8bfrbzU7BuwCAQwGQiSG-zt-k-zT90
fuH4KO_FQUB89O1BAxvwud7bGBXqfYhSXlcq2_69h-WmTr7pn_dSJQNpPlXl
}

