sprite $Unknown_User [31x31/16z] {
lP05bW9130Nxn-z_uLtev8qhLZWLRnD8tHbj1uiExzjzJp6mcxoVxgEM3HqZ-bDzFfeUBoQZnlshZSrbK_CmDrXefP6MAiomrPpqgUpPYTQZAqSuCjZNjT6p
BAJfz7eatXlIywqR7TB5eX2fkHgy3g0nGld3qmRwjYF2THYlyzbC6_8oahzAZsHHpcp1KXl6R0EDUknUE7pKeuTsAR2WjWtQDVu1
}

