sprite $URL_Database [19x19/16z] {
PL3LWGKm22ij423xxtlLivSFNDCMH96LK6aFLZmelH5m8YmuWHS9JMcI6YTcf3UDQOKs9xL9aV1CzoL0LjCLyOePYl8LKt3rv9XYvBA8f3UH728oSWemoShC
BOfN42BzLlLTTMVrANfE4OIIRbOmCvJPEkpULG3gt2KVrzlzSVpy-CC4BXCVVDa9N5RvpUeN
}

