sprite $User [70x61/16z] {
vPP7OYCn30G7gVZ_7-z9cRqIu6pNcQffDUFnjx380ghIRUmehiYP9s1T0JwGv9LZh77MFM1T2wm7g7OfQuVtBBMra2s9hItGxNOBrgnbpu-r-8TQ-4wMumzO
FdmV6NjBVVR9eBS0thCOZLfwVudeMXor_ljXTBVpVkte0o9A2qUsCc-6E4OOQl7Fdmq-2X9rtqj5ivaeuDu2rEk9BAyDzwQqfcFkoRD20j5v4PxhQ7byzuEA
g8r6zHpYepAYlvPZWMtsbFHOmN-lPT_Nd3UIiqEzAKDDbsqaQf2ndcgA9Q1U676kJa9SRsvrHpqTK-Se0b9PT1PjgQTvuwqM4myHRT4p0ADUz8UqHHFddIh9
upVo3m
}

