sprite $User_Group [126x66/16z] {
xPY75YCX24K3AZp-_uEtR-epp90JisNkwTEk2W7ZwI_XuE10z1lo4VDmn0zWRRNRuXeizIlYZh5M_Zcz1q4NoNimV94TGMbBv2qujiG-WeDLESUHZzhriFyJ
SHV-ETjb5oaCgXaG0JTzmIxT4H7mBhjcxN76f6hlY3DzXnnn1QHcxwG75lBAIdObRQ1KoBLYzs8FzBZ32dLUY-L0ak_su7Zor2ZQGzYiaXKgTc3bzdntaTch
AoyR0e_Jk-pa0HBMDyKTMwgThB8hpRarTjvaTPszaQddzk9-tVDogFa0UxdItgFflAHGQVcYjMnJxnlcW49xdxxdsRGwN_YSaRmdpH3NmCVZ053SSygpEYlT
Wu7x0Opg_tkRlYS3CSNRF82otIwJgQl5Sz0dan_50uB6ZehceB7CH6gagmQzcqgEarVw3dLtFDIPZjYCdVtjF0jhiiNTFCwCn9tx1UH7GI2QaRhpzHUGGN4Q
IFrKH8d1MeB9pAtEgbEFAYuiMuTmDntxY3eGsZOU_M9yezRY5NmoWPwUmU7IAkhqoSTTdil3o8tQv9NUE2DubntJ_VyWKrzdnzdU_qlxOTT1Q9SxTVeFEx_p
l_CL
}

