sprite $UTM_FW_SM [65x30/16z] {
tT9L4a9H30FGf9RzhnYNIt67TxuxbKpHK9SvhYXTGLmKEbJPEnOkCOtAY0McHe7psCxrB2aTLXhOZG4OSxz9zHYk1n2RTgHBPhV4q8fIIxbgNAtvBG6OrjQd
1NKrXjI88UrNO407UFK3aCCqXxN-XSxK2aeRwUx70m9DwS86SQB0UW2D-R2i6Q2EBO36EOG81TLb2w0fn7wI5LD7eWNG958hIGPTEoq6NqYTul1TB-gKyWMT
bw1dPHXSZoat0FJIkv6Kd4mbwReVWFN3AG5UgEhopnhaiT8avBFc
}

