sprite $VPN [45x39/16z] {
ZP85eiH024C9allV-CjIXrdwLji6oo1_8CXmUOKpWSmOTsI61tCdIhvFRODupWoOARxsRCzYeUi-udeT-QCBdrCTHqPeD1Pf79aGPE0saAychMv7g_PEc_DZ
QM3dLjMwGPtMdThjBevQouF0jL_84lMRchHvvLEDc1TVcJPPvu5QpOqqeknB57T1McDZ5YjgqaNPMblLmH1hX-EkLZFTRuKuAGsyudiRHigWpXAavjSBTVgG
twCwHrCoy49ifqzHgTeyd94K9r0R4WzhgMMydNb0-OxtNSofGoOGixQkgifB03dv1G
}

