sprite $Webserver_Protection [28x27/16z] {
vT370SDG20DGWH2_xJzlUk9k3v1tfLF6aS0OzMdqkjH6USJmD8Gb_aDi-vVCtr_gGe0AHqu_cqGlKcrksrYjUB8chMEghGH3XaOjOzO1f_Ygj6Ki4Z_hM8fV
LdWKCwnZFEhvsOMI0FWhfWcZjYIPXkQ9FkQyLCEhAfGmpZdOgx9sDsA71msNxW
}

