sprite $Wireless [38x35/16z] {
ZLC7aiGm20CBzFyVNu5OORA-p6dQEYjKNAmGTWRc8dYcWVbO797tk9Dc-2H6c97GWDiY3q8eXS9Y_2xSFa0k0o6faF106xIOjvGTKCCjXf9Qjm2MprvU6v2j
gkbVfD_5Yc2Cohzd6riRPRbiSTs65BfosJbniMGdv9uhDxIpf0IVh51ufLAotIqdQt42WoN7Lwr_vkgE_Gc7ZhqJlHluOxzMxzMboVFUbqlm-f7qupcsH4eq
RTBs0efJ_DJLIONINwu1pSzKITptXHKnx_pjqTyK6NkbKmhvWJ7Vfe-DtLqU3v34gAYIZmVeMkI31Jj1v_CA7T0RN5Vm3M0Zx1NUUERw1W
}

