sprite $Icon_process_1101_blue [96x96/16z] {
xPe54YCv34Lb1kdT_xYx0-7kL4WUVaKfCdohXP6FcHHPoKHb9GMYB2H04mTYAhMsLcj9KIuPc7n6gaEvGaTDSY13alSfmpXXbx_7mN2CBc-I1W3CNdCC1y5Z
hbqFMoGHwUyAL1H0MvOTSbC0BP8WlxkwjIHtISq0BSQGLqaAQ7dk413a9K87DCiJP0MeyX83hCYJDC3a9Hezo5EaRW0gAuXDEHY1Fw5C01jPLf00c6MXNzOQ
P1qvok_3Fq8r5GVw3B8b3u0admFzZW_nIGJwpJ5ZrLDaDG-T3RqDWTPJWGRPvyCkSWHWP15HL8mX3kY53dEMSDWqIyV4WGnbkwUA92ZYWABxMohJoRKcsSiX
6mHnm1YxEN24AWxSdhD0z2mMuir33jItMD1hWOns4Yhx26Ho9ftVEnLnuAOcQ23EGBsKVuepat4fVnTdEdff_KMSAN1fhKcSIHU6dXTKo17ovYukR3Ml8BBG
G2icxjXv_RPc_RPw_TNwh7xVrVQv-FjAA_r3XhZIlrLOxPzNnPTjWA-BusFoUk2Izdj-HdCoch3hSePRsbOtydkcRPDv5BoiwF5MYBi9rS3SUj7R_DolSfde
RdqXYdfLBhkB5QV4sUYd-YwKERqlqB73Kda0RAhY3ydGeHoxbkMgAWuk0e4PWBLuOqBTfxGxT1osqk7LjXnPjeJHn06r6kJtuHynB-rQAXHPH9c0RtQtdNmi
CUVK341Rb1KSkvPFJxFQwrwmovCKWo4lKNbjljR3ouc0FJyVr2IlCh3dvvjlDg3EyzaW6q9knfkhdskED0m0lJzVVfEEFPoFPtcV1Fc9-Rv7ZtVx_mJ_7gy_
4OgiH9coakAn_ly
}

