sprite $Icon_alerts_2504_blue [96x98/16z] {
jPc7agGm34Hn85dg___S2pjuDfgtb9YkSBUfnrXFQfUPBgZiacJpz1fjEhIdLzZlaYqbpqso5zWlqlRutzh_TwUIg_N_hr9vmURdgSjltw4ihTDJitGpH4sU
1bz6rHSyVfouN6rGZf36m2JNVX-RFm2_IFMsplsfcdOReqLQfc-g_RjXcGoUAifc7RJSTjFW6LALRniyt1Kis0NOkJYRDpFA51Pf3RD9JnSCnKAJ8yRcpfFl
5Mo6evBB5u_A9h-Kd2nUMeemokrlAb0a4A0XpG3PfS43_XILr9hepqtEeSZ-79Mm9l3dCGHx2luGbH2Au0zH2OC7_64zS1e7VuXAc2dW7s6qTXVmPvvXBU0F
Z48eWZyoog78_XoLm2Rumpo7K0H_o2C8HV27FuL5W3y_EcmY-7Ff00BmP_G0Ol2drk5GP7zkVGWwy0S7-7JovntWK6H_hY1Nd_sPKQQtorMlHFVbEvrCzZqg
umTjfeH3CNuVmcm6ZgxNqwVCLu_Up2Rp0uk5jWF-OSf3Ce0_fDJbucwMVti2X9O8Cxf2ACQlfS8NNHIL78hngnTcizR06898eztZKpvVKKabyCu0ZXHD9_uy
Xc3m99FQYJypUhgxsQGrZ_sPqSrFs2mkpHFudwFXKZqPKbwdY7-Hf3nk42_77UIwBdCjwNg5nt1iakK3eIxVbton1Lph2Fjsh3TjPkOwP6kw091lyX-Mb9g-
OvlhsboIjlpxQuRiyl83boEiwYPns7NyFBtLkArBL_rlxsSZAQt-B4rPXbgR7cmMKzU1qmOBJDlnfrcdwXjJT_CkIuy7g-TW-6CuDX_AzXaQzqpPGf6TFtr0
NVzf-QUvblm--HpQcjQtF2d-96_hdD-MO95yjbxa9BcP-J_fATjAyELBQeyU-3JVKYxpiZs0CmyUEtPfx_xVkimbHSyTkzI6yxdkaXG-XBKqdFzvbrBunRZL
SRxaVCCfp26_Ofeby0-gWdzOnJrGnRy
}

