sprite $Icon_alerts_2503_blue [96x96/16z] {
jPfNOkmu30J1d53tF-ucRh0zsYUA8lhFOQh11XKniY8NKktAlz9USv132gLpgL7ZUtXJ9goLd6Bm8OIOIfkMw2iBLnH0M_8NpgdElnQtIQ_pu-5NqGs0wdVf
BTu7252VhY435BUSefP7NHtBzEa0w7gdAz0UhTWtO749VinYdYaeZ9K-HuMwizqQw5fZasmfwP0x5HX1p5IXEpjyWovsAj0CyTaM7s0OuhsYXrexr5_y4lLo
HiguwcsIGqfGFyDlHm-Z-96EEqMVk9zRCnxUYqN-arFQyJE1_vQNFuAzhjX3CJZN-2_bkzDyfrIPShDyimKKW_A_LgqqCL1Z7WFnzTvtBLyV0_6hppv-N1F6
p4KfR_7awmxhN4Qmm4_oT370_vlCe1dXfJ9481dX9O4Bu8tmuY5aiC1FGQuCCxnqQgUPuQNHbMA6bu92CiDB0eXcU8a0mGmlOVAjy9FlpV3YVy7tx_6JVvrF
fY_Wz_FFqD_Y9p_-_wFaI_pSdqaM3BRmaa0fic2mXPV2w3HPCDZ2IwDNkYmORE5bK3F8Wi4MNY07y0i6M_W0GI39Wi46NXA83Aei66pWfJ7c_TMjmHPUb393
kZVOm4_oTBarsC1BGHVlp-i6_j_dbWZXrc03FxccpqVMptV6pwVkt_QfuVEr_Vi1QSSxuA5-wqKxlddSzzM4a_Zuyu1KXZlQtF5XM0-cynb7FVj-ijo-yjkN
LyRLRyUnyDMBdGP4Gto3R8klXlXkYdUs-A0h9-AXk_CrbbghqDpUm5ZZwdmpF2v-pZUNL83cdmutgGyQzNI-_7HiEMVURdrId_Vc-xT5nOtv_fHV-Nw2xj6d
N5O0hJbSi7DJW96Tx2lMBzyFYU5FnPHB6p2jWxnLA8DBzHBaa4Ak_OkBzf8MsRy3
}

