sprite $Icon_graphs_2303_blue [96x79/16z] {
xSnLeiKm24LHg4PW_iDzSfNmLTUpgx55esFHifeMhLPNkxXVypTPmMSpFB4F7pvy-F3hN1R6-y4HDPc2kiRxNWYbdxjlOPeV396zdyoecUOtPZPTsuSF7pw7
M1GMzbjrrOlxmRI2BsQMR-33XmyVFdpuyE73XmyVVgkz6LMIwIb5if8yN9PCXLG_lbagCzjhIpOccv_rJJ_gGxng9BfgihR_2m
}

