sprite $Icon_documents_1405_blue [96x81/16z] {
xSm50SGm44N1tMBe-PTxQ21b-YDWcAguJS5aSUBV-XG3zDD-jqaInRVy6mXR_ZP2j-LlcRBftyAuvMy1sYr_A-HD_mw6BN-Bq6pvUw6aN27E-wsdqipV-h5A
z_-tyznVl_wkt_HtkFAlNxz-_VhrwzUlNxz-_VhrwzUlNx_-rZVJSdbl
}

