sprite $Icon_time_2803_blue [96x96/16z] {
jPg9SkGw24N1icKQSVx_SzywcQ5ASRKwnZTxsds4kV86aXNftis3tmgtlglKQ3y7tyhF_JxSua_8nx6tjX_7dvq9kpE4dW60zpQ_rhe34ESF4xKPG5YJIpKB
0Dj-G7y1-FusWGxm-dI4djwrj9_dHwuEm7JP9mF6kjC6-FPHDXsmnMq7n24VQWyOAp4T0NwP6hiCKdqfh0vqkLA3TXtPWiq6qUHdV6dnRe0N39MVyaK7lDRn
w_nimlK01YxoEJ_BhrDqmf2xV77eL_OFlS_N0RlCse9GkSyN3MAJIGEQLF2bVPTdWourVEdpkMW7bog--6J18BIEhy6Gh1CEgUFB0JdR6xXKyiLXo-S5jbh-
1ZRzKSWNIo4RQ34_nwnWKipFGP-mrVEttoVImAMUBqvy7Rhx4_pzrxOlGfxWIs3fHptVYBGRzVm6kyW9yWnVu1GP-5DynqMXFyNle3kqQduse8C-nLVeHiXJ
V0dCyUVuZWVs7Dy8wC_nEy3n7FzudfzEphgjy7jxhtIAJW45RO6_8llQFFDr8LKQ7_9pVbQcahRsQNwEpA_JF7-2ymb-pwVhMdL8vmTZIAsCI45ta5evRaHo
kqcf0alN5osRG0cOWnx51ZTeEUWJL2gKUSdW1aUnlUd-gZv1SAPPavu4IlH53Ym_r9GUNLy_qeEaLix-z7oH7cfgT42RdezUTGuuCRkgr4oXd0e5Mwn4h2jR
QJaf0xQQyEsgM33addBCiwiTl33ysTLNmL7cAUB9LOT-U-xtw_gOZfiMQ6J0ND_JiztDJhkeJrQeWrtKLolKO2pNXzULGTjYVLjNkwHpVNjMd_VBLfj_IvFx
19-613_q8_mfLx8fHPjzTL2Nnb1VRC3CJLg6szcFzgurP-zkYM92RBc3lNtUdyhgVBkDjcvZ18GklVLQ-qL_S2NriJ_TtrpIMTkVdTN6MbSzJ-BHv0FrAEsF
pr9Rw-yV3c3woFg4FQrFkBU-GkS3uhnUNx6kzcvzI2jOt-9yAp-Rr4ZRl3wdhQNbRm
}

