sprite $Icon_detection_0502_blue [96x96/16z] {
j9O7jjmW34MDgGBT_IytFN64-JfCqobJkG-U2Zvs8iJIkl8lL5g9uNXFfDfPHg_nPNXi2W13QiufGquvLna0eEqLYL0LGAMSV-NWB_0ieW1QdpJgR01gJ8XW
FbO5QESJT06GzFkJuPj8yfH2KRFAy9SkreTAPW3MLykV5O2Hjl4L4Bjtoxyh2D0sdH-WPZCEtnnvd3lUACZrqUFRa6jRJXIW7C_mZxoHvcfEkSMtple23KOu
TlZBVuK1pSVtnSApTDJo1xskpjb1F7DaOMi7Phu2ZBpCSlqwjNtTo4WvBJyK0T0xgtzL7md6RUyAZ1nM-Gsv0reMEKYhvEijjMS7n9kV0enu4z15QWR4cr_q
wDTdxDpyE66iIYVVHefch_ul2oNC6sltXNBhbHwsvdE_zQJS_ZRGEHkqtVwjJ8u7PSp_I3C-xy-7F0iaA5PFPdnwPFwaMK3CPu7JBs7BNpTFi3NK_lzGhJZv
qVcPGIR7mrMR15jUzV7vN2VBeKrlhzFqP-P_lqoscwvs-nqzT_bEKOP_BjZYoTPy6-ACztcb_9tfjbYKxjq_tWNLKLjIyVSYjScD3hwB8n1jYlNtFzLKYo8U
thT8p5OhUXtZyZ2wU5SWGfwBeHhDpl3nli0moVlbJ4TCxMSVxmjaC6Ed7m6AxMeVxmjOMe4Z6SMEEFWD0Q4RDsA1umee3dv3OCRbPXAg6XpyXa1GDUbkaoCE
VbF0_aTiT_dcx5baEmpo3luvWGoGTl6-WC_tySyA981yVXrYy6i1Pta6Fmn-BU36v_cl-nCTVpwTty_NvqVxgy2dvyCyyL-SRpO4iVDvl3wV3OvcBeJmZlib
cFibVlX-VFlzNirXFlryCZzV3VehprUTCJzVVQ_LB7GOXe4OcfkbyFz_xmH35vESBHos3Vlv83qVwi-t8TER5-VpK_f7jvfd_4KPynVS97757qLgB1hqRnHX
dlwE_Idc_Id8duhzzH4Vg4vyGCytlbrJtVcC-V8bC5_ovMFWeQhcUvvyikxmILOLy5KD7-uqbcW8Q_ZsEP-lOtnUd2zeyv4ipdTq-HGwDOv_lXRlvOCs_lz6
-Q1tljcvPS_psJgKppuudpqNPl9bAFFn7iEOB0_b-nQ6PVVh4sorlWBR_mVLLyZgGrO5GNqB2p4Nhiy9j_G4
}

