sprite $Icon_payments_0702_blue [96x78/16z] {
xTPNejue341XqGNex7-vC-cGU-qqS2hdwQ-VvMxZqOp7I_wn4a2Gnmf_jd_yun-_fCSg_E6Tu-TP__Z7h_fO5PxF7kpFtB_7F_xnZtzy7rEAmJtZnsgyppHi
zsDdheMjlc-0QVHEN4XgG7Nx_6ZGeuooGVUx_0Ha-IodO66F7owfP9ZVuViRA41t6_nsTqnbq7K_GfRh5Foot-boapFggXyXNSXLvKq5tAAls0NVtyCEyg9l
w2LVFkpxkkOxI5VyXuKMRCqF4EvvIU2-q-_jKqKaVWIgpXjdsljUHDktrNdH63107VmyaHVFjvTrAitpGvtvUVwitrgMqOljNw6DRJzl_uNcuwT27TEFisEj
FkQjy8ANJfMrvWahgCnvIB9MWB5JSdwrS2UBjNl3WyfgOI2NYrwktcta0bdMS_twII53anrvWtmrVNUofM2WxjK3NVUoAT_1YXll5MXEjkKKe9KKGaYb0rPa
QxuofqvsvtCp0Apc7zR_1m
}

