sprite $Icon_scaling_0904_blue [96x91/16z] {
nPffpYCX44DxeNVg_jUT8ObdAULr70dfus-8AJyAawK77AMUus2CyQpByFKOZuYevVF4KYFYu4huNMUDs3zDt2FgoPNmks8TfZFYck_cJLV4DGrBHEo-XVdv
hjzZUwp3BkMmLL9dGrgYcvPgdCORDkAoHeR9bWL5-rmBkTJICdrZ0UjO125FR2xpfcqVYbShe2FPoi05yvf0MgNcLdwxpUNDHC5S-I0IwgOdrjhOnPZelQJA
Za5sXC4iKWAtER8suwfayo3xM-CFDGaSANluJSv7mn_Sqbgjyn0HHLFdeP3yjlXr_JBaM_L-tomHYxy9xK0rKFRzMI8YYbjBZTYK9Qwyku0k1ntfQxBasocq
5fZ-knmiHgMrTCJiB53IdP4OaVmuHKoZ5Z3OQ2H693yq_K4BU6pk69Nol_nJ__y5vW9zSyjCaVqgOth8I_-nWCnMrGfia57Ro4EMQvENVbkWJj9Jl2GsbAjY
jBpxQ2Lz3KqKZm9iKXyrDYeBzNFDcGqpclMnpTENRcR3Z0wniVJbczdakGyFhhuOYSqFwulFyZKVdHzZVrCU-VjxdyFIrJhVzkUM6446vRF6-lbCbJj6Kyg7
n0ZqbGz9myatCM9ziSaCZ3j1Z5RKL_RG7d8Tm4ZwYGtaCBDXHjBdciGe5c93ZAIFR38Zh8CPIJ-pOT-v3fuhVQSc-OQBX7dMwjKatsFB3AY3-oZL1EEX3Pq3
FSTiw4Hvdpx5qsAJgz29jdXott3Qk8mQzkgmoKdjCtBOI8_Mut64yLjUuc4oqexXJtASq5RNgM_KHpwR-vJBPqfzPBBXrzZTU8YHoOOPGHQBaSE66N7UY95n
C_Ad3NQL6U4d6cP4R80HiC6m5ms-7_9FktFDPR3-rQOocyn8RYvN_vHgOWECjD9fwxyw9h51HgzkylLVfL4MfrsjBnU-lhx-nkfajdR1rg_ZS_iI6sHqFkUR
-xj2X1W7SxL_s3gTay8_iHkRfidECFu9iYmOeT_P0eUkRy4FnDuME5vz2rnPZjU-5d96TxQGxvZE5loczotmRTxRGluFhB-5wR8Fk6y1chwhXVoVRMSBkUdx
Mu2cx_R7N_elhkzOQuV_uhe-hF4B
}

