sprite $Icon_people_1803_blue [96x105/16z] {
xPY7SiKe34LDB-By_-TkOJAUZIlmekqtlRo3k18Oj0tAfygkLfFRVb0sDOwIP7w8RieUj_okVQoV6I5s7YNOVK0NAm0jV1vy9ya9PFgmb4-TR_TXzX74Ve9t
3IZcQMxDVXZzayS94BFilG1-Ur80wYg_Tlop8f3My068svioO9VSQMFb9uiE9MWZgVE0Nmi_RYCgInE8q0ONoL86PBmkwa89sOcW0hI5ufJXL2qOL6RcN27E
s-zdIhbCygUcx7SpPooTAeOsNJvDAPekDnSHO6RveiVNZzzEEMfsliuhB3Jr-fzJXQ2vVZDapVqdGDFSFutQ_Z__K2hTIpM33E2NpWzXuYGmhJJwilqWCv_X
E1O-Pl40XnqAFssh1z0w58NPbkHvBpnB3tzD-Jq50h8jgmBXpHstpZVoF8C0f8_lf_dfv2pRHx82YBiTl9aVkS0dSuMVCFybXxHuYVVR3yW9PvHxkNjFARQZ
4_ub-ba5T_1i4Z-Vy-QqyFxpnen94XxhgNmpRx8PPmk0lG-UUDn3oSFpSPMkUZVoqPjALt4JzEloIt3Uy3pG02Xsi1TP_LOkzfO0KErLdoK80DaCz2Ah-pAr
dFdDNvokiFl4MtpUApkzArvi_U7RBux_veMdmes7bcaPMQ8UA8Vvnx5zsCZx_kiE3KIJ0QgvzgQvy_F3lVL7ctrVt7iZTMuF3bm4OChvj_x6DWUGduulk9j4
kWEc-Ji3aCi_UU7EFl_zB-R1PrElbxuhUoBlyhB_hJxMIG90mX-h90W0wR6kofwbvmUfhNH9Zi7x4BFGLUtBgVtBLdczlVhAITM_7YrbJyRhlcUJ0BialR-2
BzFpuENR-5IgICt9cvaEuU0zRlK2QW6ZmJU0dMgaBhKu4sGTVe6qzpuK57lXDBLpdWUPR5JDz_3w9oK1re5eyHku05MBNo7q92kfG4oGjFWPKbRa9yYbBo-z
1LOXQF43L56yfdawtodofO7LuZjeAF8jNKQBR-ZQrFGtuF_FRthyzix_dozwV050r8I-cZB-Lm
}

