sprite $Icon_payments_0703_blue [96x82/16z] {
xPM74kCg3031TAJz_yzzXMWIuklukEfD5yEYQ00fMr6sauvj983WjX5-R__jl_stlwHj57vpxlsprt_xRt-hssYm7zt8lNzk_oAt__Q7D8XXZx-3KNVuCo_Y
1dz5_FZYbRB5t-sR_5P-lzVVe8ub-kJl8r9KwrL_0z3iGeS-RTJgaWBKQ_u8jG8AIB3WOH5wXNZ9hyX_llxu3ozy0oJQ-Be_MtwnL-_UI3sF3yZhVgzqztaw
wfVz5Gut4MkNNi9fJbtr-_UvGNZG_NiEVj4Vpx_GLfk2Jk43udh-cgT1JUDROQfv50YhzS-0M7Q27jEXiEGx5-fl9Q_cJ1_KF0EQBjqFoKvGHTzgdcnpbc-z
7wG_6NCR_Q5gRyTw7glzwn1EJ6APoso_p7_mzUGwaSnlgW_pjx5SlvRipcIhVu6tGYRRKybT8IcGJLcUuMO7eDYjlKe5UZ3dwvoMvrfHRFqbZd6w3A_MA4C3
cUl7iUYFRrE30jeL47-wVzRmKEQVbO45ZRAS_uVtly-bbkHFDMmBvg_kNyrIMACyYkkRdZT9RM7QjiieCbQ1FgSPnNQkeEuA2Pe20hJZt2XRXUGkqIptej0i
fY1fHA2xYnJfOtzxURgWZaXHcdVVYpRvi_kGso_XmHv_uiNXDb0nBgJ_Bm
}

