sprite $Icon_cybersecurity_1205_blue [96x85/16z] {
jPc9jhCw24PFvedz_ezx1zjLxkzH6gFtMtFL3I64mEhFl5pk03sxd_z1ll9HVTv20KO9peKYG7xO-G4Z_RoL1lGdbn1avt41yO_X8qZuPL72S_ZnAnfkF6KW
G3_Arl5CY9oezti3-c1T0pcXUA4_aVV1s9XyF_ZPDExlHgVRZyS4PDr1FnUXzSyBujRvxVloXNh7_VZjdGJ-flks1lMc-xRYyWAgvVxz1JX8C-ybS6kvBxju
-H123C7xFtcoT0RqCnTIQKC0bVIQetyxidI8uxPi5-i0bSYVLahS0XbMahDjARIfbHJ39ohEXvGh0DiUTTfr_fQSNgJb2EumUtqiVVXjgGjyNVHXXdk5XXM-
a7QcL3jeGbRYN_G47IHWrgof4_6tlwz7zgjXVwhwkD-cL8Ea1zqldYzDbQFq-PYNjVemZ01az2bbkJohAPL2zQ2lgD5tfWwg_ihfLMewkya6zVu5MP6JHgA0
lt_1Ew4Tjec1J_JRdHOkQOGw4dMueEiRI7Ohx7_zhH-ttVY4AEky4M08IBbemHLvnLw72DT1Iaf5TBZpyk--Pm6glq2lWEJz65HugsYSjeLSj91UT8sB_mpm
ROoMdIRLS3goGfh2b_UegmR2oMpmngk5CkNzFg7_0p4Vr9aLk1ldfI9kfgjQbb1chjrb9MIcgrgMW_WjFFrb9r_KQzNT393UL9xBYdghdKbRoG3zaeJq_ivz
sQ2rZcoGPjAZqkxn6tKYEzVvTePwyCjy9Pn8EwLrljqhDkfDljth2l4kFneR4C3TvJi8LiTvZsztevrYyqDfhNYRN-Z6o6NoAvkgmRTAHCIUs3hqKWPqY_zp
MgChtU9dNem4sU9tocbjjlX2qJGuuLirse4t-FhOWplXwsFxyWnWpBiGJlXMZTQJlUw_LQC7oUBho58PviU9SPBz9Zz1rZoQTqxvtdwbmQXrGFjPuOljlpRe
vKjm8sAal-M2pxLcPsxU_W08AZMxNZ_tI05LV8AVG2NEVzIGS9yVXAPCj_j7ADtbwt2fKWCmabldkpnEyNg3f5L-qUmzawz2NUNtgK4xhCTdRW9UviyhS5NN
-8xB2iUalm4
}

