sprite $Icon_security_2201_blue [96x119/16z] {
hD85bYmn24RXdv83IN7tlzmdupwGxkzOkLoYeiDdyYId7wOxEYUVp5FtOPxFdpt2FM8-xxlTu-dyTxqhOeTV_1TsQva4CdPziaS2ULCb6vyoV0etJAksf_j_
UV-kDNj27eLhTgquW6dwXKtWKDyE31KCu5Xg7og9bKGN31KDI5FBWAco2KCTP--BBE5Kx_fMqRttFG53BG6XAklFon8s5Jcuchpn0qcQkXAil7XSRLvUGXCs
jMqmgzEzjE0g1ZfAUTO31UnQi4CKysj9iMkIMd91RRn3ImPOQPs5bdXfS7_RhmlZXe8W1iFtc5RzbnjM4hCCQvGA-FwT6xm66ExJxu5MUfykqoyD-GHVMxvl
txvz-_QdkDo0MD-4zCLogSKw5G0mbBGDzdzctxvz-zEKwi_0dEYF031b-EGPIF39Cw3xEZy20mEoh_Dj1tGD0wgly-NJBmoeliv_-moelipJPq3qLPu-0wel
y_GP47sTfy-0vgiyVJL0N-Nfgm7wAazV3T2NUVfS2s0yow_8R_eCLEVT7-HNVAu9vNvnz8Kzbs_VldtxzXkWoVHBspx9_zI-VVlsxSz3scQaBvBvTm
}

