sprite $Icon_alerts_2502_blue [96x96/16z] {
jPg7Tkqg34HDHw3z_v_xIbPwVETYEymgAUUm4IC9rsD58PK-d7Vvw3KTlwJK1gUQFJ-7cx_2hDMIKqmfvTBiTKf_D4Li3k1MuidCfJk0jt2JtW6y9MMT0_Hu
bsxvxmO2zAjhQEkZGdFmTYch4rZtDJJ0rpFT0OkNt3IWBtvtdWUZbHpcIapPHIH2mS3N4bkEMye-L_2UZctgCC8-lC4uzgc1RSJNlVW4SoC-ElvBgPrd9JX_
hp3zn8Ysq5OXDxDXlSH3AaF_QRuTMjburzIRQuVymnrjVXe0FgpR1F0gCu1_BytyrorxrlZgKp6GwKhGFXlhsfrWtmEE7HcIGVmINLJuUPATxA8YlaOSeHr2
u_JpE26flIP-2ZzexzkVEZAA1VItNtNuySCSKTHY0Ks7RtyktIOS-eXQ5q-2AdQ2eU9ww-OitNUvfGSHM7wRHyXLSeAgKSSqu3MAf4fNPjZ_3YXm23LSXgQ_
eG6loGlQsedfZMqUshwenq9HW8hTvXS8BoOfwKypwDgeS3oG7WvL-BiYayC7NHJmYdJp64DyOK4PaYvkA0_uGtT70SZtyGaTNGQzGAtWk9x_6TyWRUGRj4Cg
0iIRvXZOeHNlnrzSu9_w4-g4XSP9T-epzmamqrBxNUslC04OIr4LkBe_T9YzBDP4mw_kRqw_Ki6ZCoxowx6iIQ-mZmyrGTh5Vs53sSKlyEBHBhunNsfe5zzf
hoPjuR-IdRQ7_-gCNJ9eajT3iRDp0AqGBvzRE7PiaE7Y-kwn0ZHnUVrO_IFg_k3EbRw-thU01l7yReTMzwLYYz35BO37_MLu41VwJ_cPRr_prHHFob9oNTpo
KufvySHKtF9xgW9DtF9xgkZCi__EN-iiZyS-JSWRyGPrBxvln8-j-B0Ndtnb8vvUxhRLKceTBDpmfeFdrUURwIe-EypLouwjpsTV4qKBLwnXNbfoS_0M5-aY
iNgKfMFfgK-FMzzF23VRiJc0zvfEsDKSmAkcQ-N-wVsGdFvNBhNPv4NUq_EkxvDJ3M7THQNQn-HTFdfPPFyB
}

