sprite $Icon_internet_1504_blue [96x92/16z] {
xTe5WeGm50DGeC8lDFS_xbhMNPeTIyRjfUCOJZuboL9k_JJ9aYx8jryoJoklcUiyr2y0UUntfu4OxTyDU4M_kzpG9ED_y6EmFqNXwnwPDqOw-y-dVVijngS-
-Aga9x_lunDd-FcnRz--VVlsqoBr4v2K_jA197rzEf25FWk4FWk4FWjqFWkIq6U1q6U1p6T1JqAV1ShVjmpqHUZFEv1KFlbLz_gGb_daHJxvc6G-UPbFNkQJ
b_daTVv6VgZ_CH_RruaV-Fabd_6Tv1-CF-hBY-thn6LCVzgtRz--VVlsvTidd7ok0G
}

