sprite $Icon_threathunting_0205_blue [96x96/16z] {
j5O7OkqW38l1REl-n_s3haH0chpXphU4a2N3TgL4Owu6033PNboQAdgz0r-peLShAGPL_qfuIHtSIlJRwylb3fu9-rNe1G2ARk-f203PlGbT6u0asvig0wZk
NUYk0QRRkoeOK9wInYSvRspSde8tf3FfpJyBZoL20Pey9oy0FO6l9_3Yl7U_i3-3Jq1PcIfy3MZvJHoaDNnT6C9uFg_XsyeVOQ5zQ5y3Ef0yCtYLDbV8sPHR
xDHBa2lEwSXYi0cD1lZv86hXiZ7riyTjDFv4DYa0gcxtu7j64nC5odGGXUqsVFUvPtLC9ad9smFmlGMDhQdSM29_6RvpEweje_CJOExneL0FUXI0iEATGUH7
9HsGzm_ID6lNnG72u4Ut-r-OaDs23qDw1CZyxrT9WxbxhNMssp2HJgn-0QRE4H-Ypk0fG2IwqIiwzRtF3G3W5iRCW19B-uBJQTPu4FLgIzzpflIp9Hd6rWop
owALuEKaLieJp90__z3JbSaRPNcUsaf4E_6-3RA-ZbUMT26rIXlt7Jd1IFqsm9Y_T9JpH_j5gA7GfmAtgRbhHtaWAGhg9jILH5ccquwFScN292p9FuQX0Bey
oWt6bkS6H81InprAwtclzAfI_82OqKX28KRxnwAwWny82x4pv7hKWvOJ857CyWv-S4D3Fh8hr19QBW8opFa0m7y3rYDWeuIHVORbwlu2XkGw9iBERaVt6ISJ
uKJ0BWzVEW9GznOvDbWeuT2ZVVIud4vQ4G4t9-IF1bB2xtJe8JcBG4dGSJi3e5iyZC3UrtF7EAAxmkUyhFatf1FyQ_fmiWFWB-fplRz_MxKAxO116FZm4Ch_
V-waNMQNGO3TyqcTio2oAUxI_7xn-yJb8AOeVgXPD7-Vu_LLE_zQBUsIVz7NL_-rlgRyuC54DBbw2p_O-4qGSf6kpCXlA_oCu2a_p_Hba65GNnBgoqmVQP3t
GHy9zT6kxmX6VITG3vxua_1dKAe6VxBlhnn3f6NDNuMfFqoQFqmNl7dD7zhzRNPGOCBhWBTjzEVkANDpS7U8kJll9dSzy-V1aY_2zuuUEezHli1FNbzJlaY4
WSvxa8yMyrrCIHy1wFdkF9zYEuNv5FErNvs3E3LVGra0_O3vy6e_SD1lmE6Btcy8YQtrCzXp4LAVt-wNS7KNZ9RPr8yvqp0YeJ2qxNuFgIaep1t-ev-CtBLX
HDO8W0VzglwKqltBg0NlTjeFkrHl9f9xDYXgDFNRFeHKQXCIHKY_ZSYMVhu3YU9pphlp1JaqKu8dWAAFeFby90Jly3Se-ZheRBxZsgooBYVpgO1CSJvVGnyp
HjoS3xfg75iYxLXPj1a9lIpFPpr3XJv2QC3D8pX2luL0sY5ltmTGLbyNsURxiVR1lHxkJmXq3VO1dEsl2Ba-lrtT1u1N-9pasHyIOaoPwWKakerGkAlW0WVV
X0jooN8pb8t7VWK
}

