sprite $Icon_payments_0701_blue [96x75/16z] {
xPK5jiCm30Hhnht_SJzso-2dgEmfGoP-AyN2onFipGW0u5OtmxssV_gdV_fJl1a9Byxidzlwft_wQxaP5JVcrkkV_JFzOgP_-cqgoTpExm6WkrlvJKUlGBkL
F__-we5u6xy3yizBHJUty5DiWN8BVm3YDYPzVsTX3T-f-XFWrsyZ4BJzPZVrXcwK_GMmlwS9wpycNJ-D5ObdK_KpaORCjDJyh2ZzhBQMdnr9FxjLpSyhYdvU
RLf-2rhfvswXuwUAVluvg_Yv8zE_6vh07wmbT8Abf9z5hmnmZ81z6dlJxqILZvhMTCZessKINtSoQUj_O1phTZ3hcEtvSPz-NuqRnPuRYfSsFJcNsrm-Ae-7
8edT7mmTjyZFRUQuFyNRqCNrrGD_48pAI_dwme8AHgMWFpZOH9YHOmkwrEz6sji3Pa7ypbx6LVG5-O-GLcAojluR
}

