sprite $Icon_search_1601_blue [96x96/16z] {
h9Td0Z8j48ENtkQv_t6_-YgeOQtpnyQ6a2d1usd4NBjn2Uirn-DN4Kf7HI_XUt1Vx4evnH1y235T3sF5VuKUEu2r_0ZZKpE0_hbGQG1MmrwvQi18dya-nBEQ
mtW_4Qu28xwgONDlIcDWhoeR3UmjaIfGtbYVWVfwJGuOis9-_OWtQCUxKS72gsgcJwhvjOp5oUFD20RnT_1QsFYKW_dFXvKz8UVVWd__-G7XkraEuxJ6ql5T
9AXl_gRZVOxE6CVtCJ0zx1hu7-3xZGe1ol6BA13qkOxVXDGvGVmHVbGf7a-JwsBAfUGSTVhEiU8J-h4Qrx0crfw3zJFwhjWVu34kxuexFK1_AAgqBmW3h4H_
qQaCWEhEkjZVGkoB9mwWXJi-bLDFDyhTvxglPfhN5vYzZTPRlW62LhxVkfvRD0d2qoNWNXutbgkJBmDWb20y_LoWJjl1bmjwunezp3nkDcWt5GHv0vyc4jPo
ZAaQK9xvQOQRVb2B-eGlO7czFBPb0wUdQ5msC-qKUR8VAqg3ChbrdO2y87LvmZh9Z0UlYCiwsS9r4QAg0_Q9Pcu_mkegXUHiv3ERyv3L25EEA3M79DesdNR7
c2KTL2CdcFWF1tJG5DJXnQRI4IEuYHyUQySf-Hf9FAyC9O3VullLwzsDr6Kk2SfSDRw_npVt3lxHPxOUVbVw-0b_a_xKm-IthWalwZDZLRVAzXDhT_XHr5yG
fI97hhD5JLq_wUoI59RVrNSDt6dz6rdjNoVN1u8TMvJAIZyJyqUCJzcWTTAFseOhNRwVqMTQoiIu_-ob0KpE-_dl3CAKUCIhzXtwitzSHjR-fVyE5c2Kw7t8
dPNzFAJqBrr0q_ocp8DhMFgxNRF0GIW6Op3RSxl_SR4c4wJe5tr_3Ezy5RoaJjl3ymTzVqYzdCGzfxoRD_syum-U7eQQGuMc2Vd997PY-O_dR_gHxI5NxbTT
-fw_UVwPhAmxX4uioF9FCq1r5pJgCRqWQtBM2sPuBF-lsRZKnNGkMQjYx9x_U_rIzw5ForCSLryt-kKZ_INPqe_JkKOZyCoFUVteo_mMfNzf_Sxx3xn_mli_
l7_5-s-yVyZxdxn_o_lFl7_E-_zyVi7dBshCPrjvA3y_BWsQVscHSlbT8m0iVnG0a9yw09__Tf_blm80ysi1WFbx3K3yVq00drM8iOd9EW00J540Ey0ES601
rXC
}

