sprite $Icon_threathunting_0207_blue [96x96/16z] {
j9VP6k8m28NDLfB0__wFEvjr-59Dnx6H6zUoSmxSVakg1g1Rk7r1GkCXLjQhZmecEQNIWBhSUmNPtoT_lqmQ5F_K8IrLdqQFWz6Nwg_OyBai3i2E2LzS0SZZ
5vssLdyw9gn_LNzRxNyPlz2r8wO7ToCinGY1E9QNdbR2Ww4tbmn0MsYXG0z_rHicnj8OwbzOZXNib-9jhGK1hDUctDNVLbj8oYwoPsgv1Mczrx9hFxEGcu6r
Ipqyjv3rEfCccLeGGAKKqGjCQhH930AQlMJrutOgBxEKeOUHLpyIv-3HWg9XG2xxS64nz00YOi21YjB70HJFxMXX5TDLT-rain3iSrQm-CzDe7X0bqimrx-i
14fTaHzlxtooYJcrBYf1hAlwqubUNLS330j3FzarzEHHqDm1QWPr0zrv-be9YW8cuGwVUG3gInQ2OKaCqFBu0gnkMrMWXgiSb_WZFNj0nYwQ_uD5Gsc6QKq7
AhndO2X8hcgcBPzmN5N3MWaZ_iBZZsE6aqT3_pUBfiukjlbvIfTjgyQZfU-fjIrwJmRTtpwB6EopLlOAIGTQU6oS-oGL-zCWyRx2bRlJRJBGH_J-hICxyST-
ZrUW3hVmc7Q1pQTXAc7RzfdqeQyWlxzg8t02r3YmfK_pkRGHKnf4EMHLzbaQ5kpWQ7GcyH1Z03cYRjZpuPAXLSXl8KeuGAw-k1_h4rk-kKqr-fDha2P_Sj5v
yiy9FtrV_uByp4_d0c_NjtnMNu7p_epN-lFRy_M43_OQ7mhd9PZWmnJVTjBAf_ZcscVuzZu-dvHWc-Fpz_bbpe_f1J_w_JZbn-JyU87VhGpQFzrFuXyDklb-
eh8L6VQJbVkLvV7aRsdTVbZ6-_6QTcyNB_LuFrxRRu_hI1Gxty_NtnUTTZtvBZzhDOy3064WXj6RkVtNvKVliJRWGn99Tl9H4I3VyNnw-XnnyVNvMN_Y1nIz
2wwjVaCHnRcV6Hr-feFzajxuiUg_7okRMx-ty2Fg9rKXVdNXnrz-kDlxOTPlitwUxGji7y7wZfPln_eKtTVOFiZtJRhFqdsPxkDmtwVt2V2-0jc7TCm-XD-t
qFkS2G
}

