sprite $Icon_internet_1506_blue [96x92/16z] {
xTf50eD044HHcl7qrFsF6y5X4yEfluc_9BZXy3cpM0u0JB5Ova8-VM-RsxAw4I-p-XQeUMXr6v5czHrG_U20N3rEkCtjLxS1slXfLh-8hhgHQAlRCfhJJv_q
wQSuVxxtbydqVjRvIvn-nj6dJv--COlw0iYIlW7CVpvz-lJfqwTlD4y3yZGrl_e17nL-zSM7IH68OP8NJZ_xzkdJfq-VVg5wYFrh-lJfqr_y-eJ3zm
}

