sprite $Icon_payments_0704_blue [96x80/16z] {
xT95jYKW303Hu9RQ_tRxF7S5sZurvsBXdo_OQGK09zDo_xQ__EKlFyLf9VxnrlpCzPU__9AdLM1-hKwh_TZvMVxobxzyLpIxIRu9MTcasPlHlesLysequtoN
sk7WIl9PsTII6-4VNgL6Ao9Akjomrsyx9nWHEVYRJ2Xigds-Fxt3fR_9PmNRvGSm8fV-vGhtC_pbBt_vbvKt_SPtwNk-uVryFCkzvukBx-RbelVyZgRx_hdl
mKfF5lmJFu7qfUGdVgDANmdSGpz0aBwCqim3tofDUWjGx_kcWPFk4fHB_yG76L26Pcvygv1aI1dKN_aHY3Ae16HpvjiA11cMLz1my4q2cfM1cRmXmyOtIO4a
WtCDK6W0nShu_8RUL9pCoMNGP3k4Nm
}

