sprite $Icon_AI_3201_blue [96x88/16z] {
jPY7SYEX4aN9gVly_-U-u1r1KM9Qaikw5NPjCmUu7GR6cIe2Q7NVaH_yauIly0Vq5683-GO-mJzdCjIlB7zS_sle5_XAMJlnVy-7TFqlGlZ6-kjNrz-dw-Ch
2HIXNtYo-u8gQCrLkFWXrpx6Q3NztGG_KiY-2alZRwQ8JT2U_0CjlTOs540_iooKMlDjadW5RMaEpWA806YlhtFNTm2Z3GJf--Hni3JY2xo03W6wUrjvj9nI
gbs1xkrCfrwxAEvpPG6DPgANhQG-LW7kCwfEQZ26cOfgxA3Jjvxv6mL5_T_nlJ-ONF_C7w_F3Rk1IfyrT9nwl1dV3k4mvu-gF-Qd_oc3ips-394Mbzd7SJ7d
EW1Df_f2X9i2ImhRtyhzDdtbD7a3GEKqGG9whG9ZZXv69idfTU7pJt_hq6T-J5ybNDswsFpbHZ0YrqC7j8LPcy7jrLt0pYvZ_iwbHvm6VULPVCItFbWdHePe
dGgrn5Zr6YIBDQkZFQngh5Z6POhGRlcFGW-AFF7ZibXghhes4WNyLh5dvMbt-eTho4pBIPX7wxOUc-Ei0zd4pMOqgpietKsbhhfgBcvbDPsqcjrqfaEFFXH5
mttGzku9SXFXkgt_UdXBg4tdlkWvLl5oVOz4KO0Ud16qlHM1SfD3SjaGbR5sTNvx71hI73vkTX21bdC33MV0w_KhxSVMw8nsgT4PVB_xh_loYQjD-DB7zjxn
LK2gTmQ_xsiBVWzXNssYsibnvYT8XbdYvmsbWlOsWFm-FodYpefz1QuXwJhRXTa-R7uQDHUTY5sfDWN4hrqEP3RjQlAtzdskPDWFxX6MBGtDkqgT_-qFVkYA
wirUc_GQzx9UZQvYIlVoxsz-0O3uEN-zYcrbKEhJvu2jVvurx0aMiZr2bI2_p_S28pXR7h9ND7ldAuXxapzVO2D7xtowkwysy2xgzX79uk_AoaDgVTy90u3c
tOblAOzhPUS-hBEqKauRVUER2Yb5VvixcoCcNmvZRSqBayd_y5uJLfzkg7kVt-tHitD2tGwJx_8Z3EzCzVt0vI2zoP_VQb8EAtpbgQAbn1ZTsLARFzkJxiUm
fJQTUP-lsmacD8LsaxlX-RG3sSPNw5PhELnnzndZAxnuuuE3tzrlpoDUuOVvwM-dINmANlyrtkla6w-MzElL2s1F4FJyl8yfclYKoW1ACmikoB6vXGwWjS6m
YbIY7VwaHtUYyb2_jGtj-P4W-nfZlEW3D1qzq-9TQA2tU0bRXuzx3OpMXt9pEUgFzJH8P_pkUTnjg5oIS-52iN9tulS95gkYhVTMmctDX3bI3FoU9rHdFBNp
_NwQjV7pcD8EVFkEsH03lsj0D_bJmfWpLGk_QrRQAtw6zYY-wTHG7SN2pqgp-BCujTKEvBtWrEX6iz9UyrtRhtf1ePVIuVNEDKw-eLY7ZF9mObprcKp-R3X7
lfsmQVicOIWgo2Vy_PrgtlrcfNtC7zlhrPQNp_codqPi-V4XVxg-8c6howT7RF7NrjMze-8-tO2M4Cfiyt-jpANo3VeyqlVuUy9_0G
}

