sprite $Icon_AI_3202_blue [96x81/16z] {
jPZfcYej30R3JY1r_vVxBMUMRe-q6GUjlzhraeST-H6fJm1cI_9wykHWPdajGG5h9SLKkW4Qv8L4ksbpdc3njVegPnhCrrKm8Sij6QQ8nAeJm6OllyvhX_wW
GAkJC-EPNezr6DYe8KANUnG06wtad6kVJushe7mpiR3wYu6UVA7C7u-hR61QIwaAq6H5Qb4EdXbN1Qo6psPrYCzqbILnI31Foh3GbnwkAlS330loa0f5raJt
wmR9rS_meFhXDB-xtJF3mv-hN9CWxUX550kFYhSzlKHeSabdxEW_5FQeEfLRT1uOlbuYP5aIOXv_jpzmWmLncUiXKWV0NN6vdT0eFWrRs8qFfkoI8QpMMoqn
X2ZR14Zt-h5X3ZhEW4sj9r-3ljDWOyL8nuZIpGD0FwEZDRLZwnZOPkkpt5Fiiza1obxhionHw1-JFkpgrtJ8pfgpenUPc8YYRz9BWYA3ljcrrmnqe_tPqql5
f37bbvJadqOaGvGt4U7OqproasT98D9-M81HVj538i7kUY3B0fP-VpDEXiaDZHcUzOV-JGj7oKs2OT4x9_Z-mXV7nnMIA4Jn3u5--_MJyVLnD5GYLEUKwVkN
vKV3maSNE04Bln-G3T9nNF43VF_vOy2oY40M9s3fzmDc_FWgYXVml5ywD3dyJi3AxmU4Zw_IeohhR_t1FWemgbmow8xVFQWFndlyd-j-WVWMV_WScSPuW__u
VuR-8x_zDHzIEv4lsoyAtV6lLjNA3M6nDoRv2h3i-Ey22jWyqDNWFeOIcBRY-Cy1_bLoScIc0N0hk-lxmxhGUuUZs7H2kdzCaLM0hm_6zDvEWXt-cm1V7oV4
HKaptlu7uds0kVfYK2xUhivNrcgqnPyUwaEg4yXNkTPB_dW8jYmTkrCPDBba0DVNqQXyet5vz-iyUiZh09hbajJc-I6-GfSp5VJw6Qn2Z-8HJbyhQBXftv1q
LO72a2THiFPX2zLW196oNb7YLS_xXmtJhlEOuvcZBEVjnoVsey_JUNBqT7eXJiUI-JGXjwvw-mpVx7DLpAtr2OI5VuVGZ1EwQFykgQaPW9OWZdyZnR0aZdyx
mF7l1pZ-_G37ln_W-BS3YkFV3S3pxmSaUMz0ahS6tEyx_m8
}

