sprite $Icon_email_2405_blue [96x76/16z] {
vPV7bkKm24HBEL7__xaJVDp30atGGMyrTzFvOcCLk06KAVm0gmK028kVGZA0-PIgrvaa9QAGwwbqbpX94KvCJXII7JV9GevGoIYiG5paIhX68rc1GERd4w3p
-UGAxzMgN-_eMcy0zUiJkV6OEoa5nlzshTteJSJMZoJF3nteITpv4ORUt0dspwrVBs3W67lxUxyd2jMarFfD5Cvwax7tsmCyms5lpDyOlnAEer3jqRP-syiz
--j9EF0VH457ou7_90gDrc7zbhAxhFqYIJZpQnGa7VJcoB-VU4TPiVw3A6ZM7NuR1Rj877uJ1Rj8t7uaNHbsaJZzzYdQHUBtwocqmzBlrnIPuU7tsoZe4_Vx
RHIqDrVzEl5qaTpqQsEqJVVzI3hnhlgLFWAk-Yt_Zn_2z55_p33-kzppXzp6d7Eq73xWBvFAo9VzHKXIHkzZFf-kTD4V9ibPljeIwoBPR_Xr6oGpQrTGlrTV
jyi_tF17sM-3IiuR_gK3rHGOVdyZ2_PqidZzaHn_kZMllxzFSKiYgyyVk5-MTKO0c5m-Vo4ZBEsLPZhdy-3QwpLSBlzYt-Zr1MPokFna-PCUdMknk_Rhyqbi
SQT7fJGoEKv_-ZgchwG_UlKp2AK4v_KdKjAN7agb8FESLwlzJq99sXnjrWBIv34D3y86BP3VvYYJu-bZBcVaN-T_GWkG-gNMzr39e0MCFfF9-m9OeGMcYRSu
vCOGxV5jy97-f9YK02VZzotMqUOW22LYHoOd_2Jk2sJHxhWetBsWL2th9PFimVoxVqMlqUr92mxgeBX28qaPhTRQv_DvnLL24ogh1bmdjR64iaPDWF8T
}

