sprite $Icon_directional_3004_blue [96x96/16z] {
rPe7alGi34I99kdT_xX_LDN4Ofhzygkm2SlGSlVYiOD2pBLF0vmr-vN3ToAtoLjMBzzUV9WN6-sg9QUSSwbj-2djcquHsmAmKLDu8TTk0DPY-1Af0rZBE-aM
G4zVhJxAPm41-kaQcdvKR0RMZhgw05tNs03JEzs14O_K740NnowVp17PO2bzBWOzd1C7cDRO6hv4iQMKNpdyC3hC67uO0sRuSRGVM_xwiUKphF3ZI8PzfzOk
UsEqXINPgtiTxOqGxS1M2ziR3Vgh-EF09FtZYF8o9LNy0fJ35Lv-Y40q87w-5jlZCVF0uqnbL7hGAmMD2d0fgxprCq4xK4UQJECsgeFQt0d6qYRIWt-hJ_-2
PZvQNa23A6V8B923m6tMnj3LIHqB4iC75l7QzmnPT3cFo-qy0WbcIBeJr_-wYFto3BdqQwrX_oyZw-g4AJlTApTD7a_O25TGCPghfAeJAgIWqbaXYFzNFD87
AyXKYABy1Rf-CJW9yWLQcYm_JGuwS7LfmSFhLh1dwixlVJ8a8Pk7oYjpDwsvQ9ew_ktL7Z38MuT1bM9jix3jkg48eNzj5hQX06GXz4yNvcIb_iIIlh3N-kbp
h6toUalwN3_3t2IIK3yBiIPiCZNzzI85Xf3fByUBs-get8uKWBerhgLupqCYARco3TpECvObupgDjSstmGlBFIV6xkpCdO1FBAPaN6VHBmWwHfECwy2L8GML
0jcDAszGe0QLZad6TIe4UJ_fUah6TGRBzrSQ2OfxJksMYwHnmSsucln7Mvh9TEDADEneVnwXkd4bZ76qPweGesRSXxh6K2y7rRYkozdzdT7SkAAQxVQTjjuA
K_SYyMRBA9bNDQxVNvzzFc3WMQBVNZi3ek0M60TMxm-z6CA4T7N2U1pRFdjW0VaWoA-dezT-RX7HkE_tlGNw9_Eke38W7-x6XcvSpwYp3pMRPDpDvYBP2YVi
DsNXnx6WX1_7XEl7bkz_RFduOyldfNXyMGrVeYArrc34S4piO4Lzlfd38KLzlkbHFz9XOqywc-ti-NBdzB5bCx0MrUh7dlMZHlwekp_V_q7l9zYcklPc0DZR
bqtoDGnWNJ5ydTBltWyf-LzAlTfO060zVxlh--8jSoFT8VdgSm6EpLx5sdy3
}

