sprite $Icon_industries_2601_blue [96x86/16z] {
xPY7qgiW44ON5gL-x_-w5szmpF8t6KtVCurwg9keD82P4f1dGxV0k8H6cauVOefOoFESsn1q7gx9FLF5haEuS-IXe582RsNM5op4eqEmRtAtesOKsnG_pPB3
WI7MNOvkp-Pv7fQtYxZ_yEr050dvxY5ciriksmvs6v_8yMNBA9AC7zl0HJXyxUH5FWxBiB7-H7a_OKlJEjR9k5XGcGfmhbnUc08ukXaE5QQRmRVrgr_zwa_-
PYGWugP4yWKt8tjw3XGZSp-K3ZILU7ZQc15e8SFIHWPJnI694Cgq435He-K4INIAbvp1rcpBpG2jRBc28AOInlrGl_hLhtxrgr_zwbU_-jLlkTBxCrTSx_TS
2RtVSQNtHwxOQi-u8FqDwL-H_eRqhrAJqV3VTh9zftugBAVIJp01dlz3rt33q1M66tIDRONs6u57XL_s-wJwrQz-ppV30nat9TbyKxtv1m
}

