sprite $Icon_integrations_0303_blue [96x110/16z] {
rPg7akmu24Kjh6pE_t_kXhQAxQe9XNRmxdjCwdWykaBe6lUn4Qa3pFDu9axbZl88FYdCKZhmo0WQrB__PfXFy9Nhlj4XFS27Tj_8a7z3lgBtZUi9VMG0VVtx
38cbfyOhPYc3LxJ88MG5PbRkg0FG4hPk9t1bgmzo7ES5N07BR46rhdiYIvUYmFYvI5M1dhwQalP3uQzl2gRCdqo30RB_yFivgSqldp_y4sZJlncdV-IoqdUt
66ZPMtwoivEOgF7lA6e5R7V4oJDOKtD_gOXdPYqRTgFahtBiFDFRlP2AEwvhP9Cks3MboIjcUiOrNQ1p0lFbcaR9eQwfmKZtA4fVhkc4Azef9ULIfXrKWjI7
Qim7N8tONDP7-0d6VMk0wJEXnl0B86jEXxdYY4LWbHqj8bNXJ6gkQMqe0MvZigA-hQ-y7464soYARTsfhu9iZY32RUHQ_n5R9C0HcDjm3J70RKGw0dCRZpW2
Sni1Zi3hDb9wE_x7GzSFZc3FEuXgijiWlcdmZpI_xISdvAzKlRBhr6EVRrannPTf-tmxYN2jb7s-vMfsUFzzle4i4r9fhIH7CN3pFme2xKCnYE5tLbnM32Bv
6RGitKtuGFv4vJK9vlL2-GcwkG89vvkhCISJpw_cFyv7-9XJEiBv3M2iDEtH_AAyGiTGq1J9j_qoNMjvoH72_rY5orITrTPpJm7yObNu8q7hDjzVXTEjcfFl
S0P-b-7ZE_okkOnzlcs-VhFdvxixaFP29t_VWzf0lNmJFkrTb-d9oIy0KxQzFzd3Fpyw0xyZFh_bc_3z-1VHrKGoljqk7uh13plL1VAR80onOX3Gy7thAHNk
q1BGrL_JKEsSzn2WjpOWe1rk6nsCrZeWS-bKRaiM46a0PSthi5w7mX4KeEQKiDG1YUx_b3T-ZUHNup-gpuIn3jP2sZ-sdjgIP8Z2h7K2ZgNhhQKifehrVpHt
G5l4vQQiY_ct8D8Lj2TRtW6Ncv8nNo79Nk0g_PxhLKaYsp-swVchR4m3oDjty9k8-0j2qatuG37zhIA_zVIFrP_C_bPTJ4xuSysPgosuLVfn_EVNJKc9-Ep0
_BmVWUOZ8DfLxBQ8tInNEs93nd9YpuHLzVm8NXH6AGFqaH4CACiKZ2VuC1pzanZN9ByPFrwV-FcDpy_drzVpzU5F
}

