sprite $Icon_scaling_0903_blue [96x78/16z] {
xTT7ckOW38HXWKb2gliVTx8wczR3M3lUtH_yrSg9zdGC2jI1JZk65b-UQGS3AB5ve0Jc5GgKx_AptYkh_11qMGyaG1KBPP4dGKlV30n0z1PGwKiL6FIxJqcW
j1vWkgDt_IoT_lOfJIR7WBjlh6-M0r5z6-YHVHhWq3vbYktJwNTskpRw2Nwyr-VX8fXx_Kmk_R7-wP_-A6_av_llFTqVU4UUwYyyrJ_zr0MODQfV57_C5DBF
2ksbCZxc6WRTcVeE5lq9JV-UL2kzK-WMFgft_GmK6vhaTTs-7dpi5u3-gj3XrEWZLz_Fty_0PTSOPQVkxvCz9bn08pT_lm1IKcuAeOW-DVob7xw_f3xIfp81
w4ZUwuE_Rz9btuNqZR-VhgkKMblhlOynUAHd-ueFQa1VLKJcP1wwstSwVNFwfz-hozpikstrQQfRtUW_x_HpRB-3G_iDuCW-TO0T_RW1HKl_X0me5jI8cOPV
o7A0yTzqUTtD_roccFgYcMx62nPWK9m1yCdVQC2WGFrp_YS
}

