sprite $Icon_cloud_2003_blue [96x76/16z] {
xTS5TiH838JXQYRzzpzkcFoyzdGCor-OAYt9ckVHxxbKk_5kjEnr9PSxB5a9keYl0DPozCx9-P3g0EXH5t1jSTf5HUDy3Tcs3keRq9pES1qiQeFlO6TA20P5
Ew91FXDlyN61zNZyS7ga7lq7VYfUAb2EZ7OoNYgGfbDZwGPO7vZNd0PUCrBdXwXPWp6vIbZFCOGGSykQvYT640PO3JeaWtjucP6TZXhKHoFgNiT5yFjRc7NA
s9j0XwHpChRN-wYJt7P6XApJskQ4ZQRpqbQ32kPqdjzOWMXaNS68Mia3J9VewtFw0RIWIzJLW3DGd2vIO5b0XUvr6JzOLD2Wwb8LshASYsKetqjRTBa2KQ-S
qNI3zh6izVtZvPnHtvSvwHO9l5GOkicWIaRIJHAcYEak3cAXwJQDEiYwJMP0q3oNMX-zHiq905xJYl5kHCtm04wJt02hEUK6rCa1mtmybZy-dNt0_StvE-P_
J8uqUNwlAN5v9LHiglz6d3r-MnnjPkyZrYcpknZqKwNhaK8lzDbBUNMscJlfC3c0o5ZrTgBzNcEkGObrldlOdY5bpDsJxumioQWNvoyluGJXZlpmkOBzGOTA
VT6nkj2WlNwCsztfYyysTVRaxKShzrr9Ttlv_RM0LfTQgxNQHhxhFxiUOVY9k_dfdtc3k7pcGhaklu25rHsrPNT5lilsH-t81hJap-Nxr03BMdF50B1HZ-MN
yH6m-KGeLWEmO_a6O3LgZmin-MFvFiNWDE7CVFzZ-V_d_v__V_wElph_6G
}

