sprite $Icon_detection_0501_blue [96x96/16z] {
h9TNWkOm28FTueQ_-nztUyFvjSuKNhP6W2J04vv5AhLFimNBRFPQKlYqo6to8goNJm2_9i3wNd9ECK28ANzlPW7CwqFWPInWrXn-1_njgqvWzVnkT0E69m6s
0W0hxoB6m6eCFY3uYDN0tanJ5b_1wpxjJIp5hhe6nMIFpubVh1h20Tz5NQodCZGOgXXGBGzeZxYPeEK2RGYOPuxI4beTyKCoradcl1WX7F1bZ5E20Zsy7pzq
A4574HhbPjNZLsjPU4Cdo51VqDeMq3r-1rPBBumAMKlRxZa7O3Nl_EHcmBXZDQL1N7VkqzZAXAsnaUuQh9SsdOnxBViWWrzkYtlFW_bI6Nknuzh1Fx61xIqO
xPLrqasfcSx-JFTvJr3kv5zxbzHd_c_imbqt2VfE_cILf_DLRaC_jenvJpYnz7n-qvuWBhA7gpjy31h_dA1YZY_pxNbuZQzdqoZ-3tu4ttnVycQGWhdVEp7a
2eaGzMvCeW6ZU6sgFb7wk7Lcy9oxyfLLVMDpwkRCrsNatsfMPLKVanP2zMNgB-ll6LX4NSMzOwD8XhhJQltwR6owYrW_WGjBgv-Sotz8DLqzkhh6_4kJ-Y_T
bJflbixOiRW4yP5zuM-MSDTQhYpjiEu-d-GG6jKNeCqXjfTilzB-sjHfVJ1tbImkqh_PPWWiHqBvhpV3dB-oNKhXwWL8J9S-Qc_-OuQYXZ0xE2CLPoaRqfj-
VmxbKHkUZaeDnqYGF7xQjgLagrF2CGPjt_-D4OvHw9F3azsp3SAZIWqxzUdT0ivHHrxDX6F4hGQNzH0HMoTypmI8TI_m5mzYlhxlaq-A_0_cTEVo74T-9atR
UnxvEUZhhfNS6XhVf3_FBZbxD34FyrKt2iROoAk7-HBxGKqfYAkZzeFRR-B5uV35rLJxpU_dsW_brNfei5U_dzDs4BAYLtjK7s0Z1PPlIBorPFW66crZSv9L
-ivrngyEqJpQT2NlzrzvI-CdrlvFXQdwkx2onNKL7tMH5JsJl5ikESTC7aGJxVz6dXJvGBpw5j2to8wGSN_VNepd4mdFlJIvNZog1ksz-8tXb_FswDKl6usl
lwpqtVJdgm77ItGV1VC-Dzfxy2icRaF1jZxBCtpvKxalUc_WOgMtugT5zQlVz9th8e76ZyO8U_bw4Gyi2Nm5FpUhsaPUtBomqdFyjCF7hyMQHGx4C104DI1Z
-l_FNRnjOkX8eyqzJ7PL0JRdOvNWOtQW_JwgPSNt2f3tjfzEV2-TFp8Es0d6z4q-cSvySeElQWUoBBQVSVOH7NcV3sUvmOSflbsCvjiidyyKdrVABmZj5uBz
oDJS1VYTM3yLxzVEVZ3TzeDXVbCRaFVzB5W_2np-HxzyFbtEZpSBzViUrISqdBPEB5P2-efp7u9UivkA029gdci7qOS4zYrCdzE-VKvZ-fmd
}

