sprite $Icon_documents_1406_blue [96x127/16z] {
xTPL0kmW38LX74fozh_SA-D2DOpdVndjLu6AMPnD5RjgigP_cN6ASs_TqK5cx2BNbVUyssg_Uvzt7tn7tZA0OauL0Dnn42g0Q2wA06etFW18vge48FJo2HWQ
kqITU0V0tOtuwKjngRcf1AG-_W1aSrS6Yc164YvgRMd2PMJN-H5NXTQakYeA_ERMMHBwv4wPPkuKRV6hMLpTwgkVwqr5ufTRBUEkjDrFM53OxWSqudYLbnmV
Vsqn0D3ZnfUs--gJNnnjy5UrsWzOMLZdcyghgcRIb_Vcllhggw--apNd5yXYF-r3MfxsCsIHUzdugg---bwMdV472FFJFaDOclOJGnHPdP_jr5TVdmyVVVta
ZTTFVJvKNttrNSgYuenF41PV-tpeYwpyil5LNttrNIwYqfTVtroHbRvs_gYlllgXoXhiQwzl5SB2j6z25EMVEhxggwy-w67XyV63-Ry
}

