sprite $Icon_detection_0506_blue [96x55/16z] {
jPY7TYih34L55w3z_v_x2auRNmsUkLdUgwGXSN0uGY1Fj2GEiRG-ZGziQar1F4gMBH6A74bj60xJaTAPigT2-vbSZOLrhIMdc58kLGSBqyCKOM9HNf2C4Jud
cu_KpgSHIpU0MOCJkIDEPXIHq6n9pETIrWZqeRc0oYKwbgKQqBFioHsWHv46LIxIm3w5xVbSPXzObilaXoWVVmQBSeDip21NAG0poGt2mAu6LD0EQ90RwBFL
Ggxw7oq_fUbhO3QkA8ehsDbmUV35oCU5naz1gEofTDTgUIwVvPHoKQExTamJzWxha8-6VrYj7pN7uAynTB2yTMvoh9QCwKKvfYf0Ez-JFJWPr53n26ls8ycW
xoldaNogA1apUXkR4Tob5l6O-5RB1gvdrGlePvktCLohLPZqq_8L_qWVnIDYGHIgLsCdlgRoFC4uhJPASshxnyOj3779Ho_tys9cX4yRESQRnCq4hzLBfiiY
_apLqCzlckmdsAiN_VRpIl_qVMHipd5RmtHNwIT1TXXoHc8bRjkJ1vC3EkN08EuEmHdADdrWxjVJITjZhHjLVf5VT_bbG7sZ_Wfz_NlVz_c_SV_appBN6U_Q
_x_rRztwDxwl_YIdmDsldvcnLN-Om5SIZBYf_tbJ_w-TN_NtvzT2iNpl_ENE-Nk_VyXmsZ-SzZzokV-fK4_w7ztUlFp-BJsb6LXs-hSAr6tJNxp-SnolOabX
HkTIfwzwz0RgNJYB7VfdhBYNKgTrSyf6zdhZqlbYLgV_Nz55NX4wQBXzVxb1DgpUl7yrkK5Gy3soAPPoXmgC91T9mx7QZWPz-ZFusMS-MctFOsoPdwyZEzQe
ubsLPElYprXq8okhhUoNtayymoHTlYh1aL6x0PgSoEjxxTDNrbj9Z-0GSz5X0Bt8pVUhw7abw-G3uvFHalp5-zkASaZh1T4mcqDRSMJwxuV_0W
}

