sprite $Icon_scaling_0902_blue [96x96/16z] {
xTetaYCn58DXUgFck_zrDzn1px08L8dPGoZp_OnaUzdLBRk-cg-jcfdbS6tPVVVTlpRtSV7iDtjjnRrNxRrqyZ_sNjxxtTwh9t-OsTD-h229g-t_-ZApil7n
I3FeYuzn_feG4FZ1-G42FDyJwKE0vmFhGu3bMn1y292yu4E0v0KV0YIl-13WUCc70CLhFWGONlGXGF2gZm6ErtqCx7dmyybFJmk70F3uu4c-FsAWXpy7F0xz
Ks1iVE0L7xTxG4p--UVFkU----wxxxxxUMuUqMRyWb-s7-3CdgZx9RxvjJl_hq3AHx_Pv_s84W8NY6P9-FmCF14GFfyZpmLqFyEz-u3e2pm411zu8Y3vm0i1
mGUU2WW-y490y84d0xGFl11WVU2L0Ea3hmGAvmiy1XRbIpm627-QsVgvJzoJPS48__hlpt6E3gjXlzWwR0x__EF-L-Q---vVlpxa-jPb_Xy
}

