sprite $Icon_directional_3002_blue [96x97/16z] {
jPe7TlOg34H51qjt_yjzDOtp4zjokUc9CoC9FXyGbZE4tCPcVA6ZbIJF4CemLjYeyRPutRv3hYNdb7EfRIZ_e-sEHHe0Q2znKRAk06n5hb4KG7UA4Ce6O5Ny
P0MinyC2wXM7j05QpaUYIHmqmChvN3TWXDF1gplZOc3vvBN05iL7w42N4mom8dwIWHw65NIwoaFOm9Bi4Ws6NAKT6II39jV9GDcFlegVES2o9vz5RXkatuUs
YDmtiBM1GfNxPB0WVzAXoHCKs9Q_7V8C3TfYR2t8GsoG__nLagS8VmHReCbpPEYp8IfFCkPozAUgimuuGfTdgL1-PXFaOVGxWGHTdgPy9z0zKz-VG724xqiW
Vmv5b1SmnaSYcxn1W_3_w9OpwGPnag1ysnnGCLSHlmkZ33acupUe42IUAuyKlq64B0M2l6HWTEceo4i60vtA_xH1WG1LtZ98a279QmPGQnLvpS3eui1jiB69
a-enw9YyQT0mUTEWWhnfKA1lVXH8v_GlCqwkuzhmesSBb47yDD3JzrnnKq_BIuMtvFtwVddfw9loCjXQUqzUb0xf0VcG-sQ0RJs7d_N9K6_Bvy5FHfvI63Vl
EqdvF_9MMz-CkHlNiNlo7R2MlksQ_Mnb5OWtvEEgLrT_jB8Yb1lojcmSXW6MnB4ypx_AruDmgcFzxEZebC-v5i_DqBm8OkpzQ-Nk_YNlRzmwv0-Z95TGJFOm
z6ClFsxkSFSlQ10lRd3NX3nTuTy0xy-BeBHfvpkS2KppUcVM1gWVNuTu6UYlyatczMs3B4wCjYS_hp_z_Qi0PKz-NfyKzn37xvHBdELNwwi1sQkVleeGr_AI
O6efUkEVRwsp_Aml6JPd_VEqPvha5-lFxXm2g38PJFABzTlmzLYLCUtwqYI_Uetu-lyTcpSIqFRtfq6Tc_aq6ypoYzPLD4-9vl4grXOf4cGoK8T1Xt0qnVhY
vRq5sS7HLUuGTmxXl4toHVN7sfNgE4Pm_pKRwDdjhUuTaXHP4XLeuTmGR-5N-Rv_NDpE3O76TOYClT8EmEfn3drvr5qD-eaJVaQM0ogWPSvUfocoxw0j7P_M
Ov-FOCJIZRFp8tK3i57IOWqLftW1CmEcV0ufy_CdANyyVs9WSo2VM4_Y8UHkhD1vnkJQUglVMVayQjSV8JgU__aR
}

