sprite $Icon_endpoint_1901_blue [96x79/16z] {
xPS5TYf144MfTgcx_-L-Qw0x19jV9pxlI9HR_c0oRwh2cylBcya3kCERoNqM_ixV-JjVmZzvUHj-v2ZrRy9NoX3jJVZqqpVw5dpvelnGYxlE3r7iV0zGvE3R
UQnAZt_e2YfclXAJeXMwFuLiK1lKGhNoqr-45D2u5jL7k4wmyKL72znbgzE_S85kurVouVxVauNlNwvYhAfQ_0k2Ye5Vrlww3YXG5sGcc_YpVAUqlwc7Jfy1
0jNK7_gfWdxEj9wPKY1QvkiQD1dkF1DLnWoIeibuN-6OTsFEDOvV9SXYzfyqPg2wlgxDlrZvcRYu_sgbTlwWn1lvZyZs_gUnD7u9cSVs5h7nXrKUzwTDKnel
2eec4zylhjmeH_pyha0N0t-rBr5wb8DBIbll8rlug_z8OwYi5LhyuTBVVMczvHSlQ3P_60swhKWtp7VwUmoNVvXEPDh_J1bljsDBfszg-FVNQhmlKMA5rj7p
CKbM59eRrHdlb_7P8S-rR534Tu1azn-VuzbqXfGnawRv2Vyf-OOkHYeB_wB4MuJ2NRdd-8wxqdv3zTdywos2Rdj-qPnIZ26glidpI-Aaz2RyWuinfJbu8z-k
dR_pTtvE6rHAsg0CofjAGzSj0jsY7ZOszEt6jVE7TlxEt_boNG62NDSclB9PkYNx_-5Vh-0t
}

