sprite $Icon_scaling_0901_blue [96x94/16z] {
xSo5SSH040J0FH1B-OThc0BxURLrypWTGDkfl3Lafoh_Bxc9UkbFraJ-e5-_VltwzUiVnYEbwL-tOqlJFqtpVw7VBItC7_rC-z4F0-r7Rxn__krvFthUZvxt
e-Vzw7a_UjwFdlUZv_teUJzwte-UzP_sbgSky7jxQFYZ9_wvMlo7iJU7u0_lykiVHhyQ-FTOGlyy-Ip1FvlFyCg_VltwzUlNdx9NZVpTvlUCl-NYbmB_Bi_w
wzUlNx_-cdt6sEz7_wV0_mq
}

