sprite $Icon_cybersecurity_1204_blue [96x96/16z] {
xPbdmkGi38DjCDNe_iVzwfOCgSgRsVxyd28ROReyn42GTmBOBwOVXxzJFmwCX_Ld-VYiFY7FCn09UPxml7pql1FhcUmBi1qWFMEE-cw080H4W8THXyixqMBo
u_E7FsYK5wBzHv1dY0Cl0I8-yPZyq6aA_OznscuD8QYUoqTXiT8Sd_5Mx45vpHrhUjP7vDF_ugFNR36662tNFluFOH-MJmu0RRL8XF_RvEb3yZO0UDOTsno0
sstvq6SFPgm3Q5_2Tqe-3S3FVcyE3FlILN7-DiiU5HXPpia0Ahkh4Es0XsisEj2LM_JLTvBQQwfJ0TI18jSfHm5yKpu9GzuFKABCz4rvjLng3Ri1Ec7dohDO
7S1HgLpkiBJ-PVeaxht5WwnCBX06V3s6CAgf7E8OAkTqZ20Bj4spn1u1Q7AA0NaUFMvNY-ZyXvCxSH0ZmU4NEZSkvO5XSXKx7pQE_e73KuTJwJidBmOOaK1R
_vnf_XfzCT208XmPqCjVErn85CY7zhINlZ1XwOS60MdsaZVeiFl3ilHDQ08G3vQXiPmFXznW7DH4MphYg48oT-6CBsBhpKkw2h_KlJPLyXCTl4mvq_QVvxNi
-mANEyIB-XNzhdxOrmyB_IPt242uad-eyGtvSvgy_oOCVFqa8Q3htwdrX1-_ZQf9Vlufr9Zbvq_RgIrw_dzV1sU0CuzVVvdjnSFx1sKCuXEScyVZwCJ-ayO0
enDWzy_lQu01YJY_q3YSEd_nnMF4-P4b08qu_z8uXXBdTvOA677_m5A8h3e_JIIWKszPYPLt9QR1mLbK2FdRzsyK_FqX1N__oMFq_Qtm7g77Y_VFTvi0JsVt
vppy_VyC_tvHqixx1G7v_aB0ln_n_0q
}

