sprite $Icon_people_1804_blue [96x69/16z] {
hLS9ikiW37jc1rltF-vVogGDUf0casZMKb2CZ8NvEOrG51qjkv-daGnxDFyekrV0IknXkzW0L7amUC3YVi0Lm1uJAK-YzGPpZqMVVu-AmkGHxNVqz87s1F-I
nWFXFdq0LZ8Kw1FXvzLVyi0678LF6wZt3uyUfTukqeaBOJZMTP270UnzulzQEMAF3VzXnU_aZmSBskTVNwqxKpmo6K0LUtSn73bPsNOdzRDM_T9akl662fZV
5727pb4sjq1zhN3PW3IdhxBRYhdp_CvsGKkTVI00PIn-FQ-FGcKO1TU560eFzAM79THUaMPska83irAFCFbsFllkn11v7ELhfUihjeHsQArSWdFJoZpbpUoF
_26ZTP6MhiLLnC7rRQnWI8iZ5eU0PHfaNvVM7XDUAN80_y6C0Rf8NZz8XzOTODF5WQHUJOcqVqhYB3XEIaQPnz-dZjN39UDXyyeZ_gM4pgRRgp2IUicVKAVP
-voa9XE_2ZiT6NMlJvm5M51sIglZhoE_gSh1pK0IpalQ6r1aRDyg5oidZ-yvJjzG8MreE0FsErQJIN6EkybV-o3zn107-eLpa5cUkFi_cVdQbx2bKf4UmIc-
JiuKxwf89UR0Im5xZuMSPDwKiL-sIRSjsK2n1WMQsma5otAcinO37_5aW5KWZC77uSvMm395FtqPE8CbVd95kaiBYf01HGKqZ66PcudMTcyuATW-DxYFZ9Bs
tDcxjN6nM1Tm_GPrMxyaLAg4siFSWl4zhpsi5K9fJLx2cgTYPJJsZ_Y_obivyIA8v9U1UygUdK3-4Ky_w5WGjhSk2Ci5VufUjeHIUAZHzHnMp2w4kdwlUXbh
MwRszXzc0EX0pZr6FBKFR4qCNnITFBCGR99Zu-eCXPnx1UUzE-n6XnxNqGEQdFiY-1PfwAeac53ZSX7pDagiCndIhF6w3kxa4gmF2dMTDzxYTD33q8RGdAlW
s3gr8l8UhsEkROJIDwdLkeg6o5gm7Wdr3dzYlG9q-cA-ZibZK14owghllGvUN95_3TtXpoZycoIxKRwJv2KqHU0Zy1n_W1hya_oDRa9ZEz0x_5my3W2yREZy
uJQ_RF0OK9_XhrYWy1rqdLzVLR03Jz77yZj7mIsa4nvo0x-zwoy
}

