sprite $Icon_communications_1701_blue [96x87/16z] {
xTX55YKX40NHXrl6_fVRxbtrFLk9CUUY8oGf3HmQIHyRE3K-y0kifVZYKZDOaWOqkTIXAxdnKeSqCBbb36Xogs6Gv5O2Y78h_eV-zhU__Ut7VBtqX6_SK7xS
NznGUjnNkDw_-dwsl_tIxwZUxtDNuMw_pJjg-_tSq_QttzT9_JK-fxt6p_salE_th_2tl_tj-_-_LRbLORBarc8Kg8xBpvfGtFWf1OEHWrvSo0CiI8gBm_h9
ckoahgyb0rX17wh6KOVyUVR3EAlwKiprXyQHty5QFIdgctAELoz7FpPW1Rscd_qmOKXUVZJeSlEJGPERNu0iDx-19Rdv0rQKbnycp20lFoxeaeF_qyDny0jG
vEP_V3XkVeSLvUM70JF8omyBXkJc6pGv-b3awLkINmcBUa5l0G
}

