sprite $Icon_automation_1301_blue [96x100/16z] {
xPg7TiCe44L57ShS___SBLhxW8An24cslnGtyJGCqu-F6LobXyhnhN1yHFfM_e86r-0BsE_aXtZqC12_bp-CD_m-c7yN___y8Odx3BznzbY7LO3Ixk17_lvZ
cu6wVeS2LO5islA1lzr1EA5cLJaWnn6Lyz48eE6umgMd0E6ypaN8YuUfrFCn0IgFsuo82XeAa7zNJGAtn2_W7tejy5W-uY40LD_4Me3jD-hhkNm6hsWy7eWG
rWxNzXJlXKdTeTQL8_OWnotsbrRqs4K6ktAukx2GRsspl2FmtjiRwRPtwBDoeipDvCv68StOAmtgvgxlt_DFLYP0nLjZVQnl35r9E_ANImXo_jZaJr3iosF9
PYLqvHlzc0AaZrIhiL7q_aBHeRgql39Qcpz86lIsR6nXETuQhQ130LpSaXkMYo3cjLGEmaNnLByLgSB4vogvlvc6pNeaDKLC5MINmzPuUINFVDLkraCEtAtB
k9vVaNr-MRfeMpyJ-Vs-VexUVZ9r5kntwr7Rfva8vhLzbhRWK_m2wDrQrx_jMjYwXTSF5vUN2ihTjberUGjNXehDgKoAr25iXLlLBCOHfzGnRDsc2GyQ5tNe
NkReUbCSrfa0nbvruIVRVwiYHTvKHi7-_iGdGDqQmIZ_d1z0WK7DwtC3cJS99bOueSc-MM_twqFheyHWlrA0ndPmcmNq3zRd3kI7-elr1gPSBbhjozSRC0Uf
SoHzTnosjbYot40cS5rGHDv7sco7TVSzJ5kjKFqyqYeWvcgRDgO_4EtCIUAvck8EMrvtBFvaTu_fGT_NEkM1sOOg9zG_wzOntYYWiGrFf82qwSY9QJIrzJgY
ZNNmEb0nrzbk6Mg32BEJYzuCzSfylXIALXa_2d3Z3_Vy3J_CRtwKtrPKHlwdIMLDzYlyflAmKwyNVf8vBGog-G9_0ib0BK2nlM5fUlnBU_pDTtrzU4s3Im0a
qwB7AdzuCPCAYemnghZRwATaC-RfCMUOKSd6BqHl0RG3r4dEsym-YIkgUPDNZ1H5IpIVo8mkI0S_QmHQsXZBtRoPsfLyfO4YKLgNtjnXYpz1TVrHLViq_zwA
XKtvJTyoM2YzLzis_TWlhKBhNd9l9VQf8Tj4s88HoAqR7sOBiMNnJIZomjCzsFvn7n1V43bmxV6B_8teM-Ll9pas608jq-p399xdMo-HwTbEIEiRzytpAMaS
vz4ciMz1uMBR5MAZBvTgCcwQPdMNsGZ5cyE62cgkkzpaJqFr1sDEzvly6JLZW1wd4NcJtusrWVN1s-tEQzwHx7TdIrspAwE44hiike5cvpO3nGn3c-fRVR89
HQt0YMG_bbTastIu1V-WDW9D3n50WWBrZ1_xY4yVjgdnosCpqdnX6-PfZ-R2_qnlEJRwNSpv6_xdFo2v4pwZFy2VQP0Vu3Tb_YMdNm4
}

