sprite $Icon_cloud_2004_blue [96x76/16z] {
jPW7jkCs3001zeAv_t7Ja6IzUfQiRv7pgzi011-h_1pDRHZEx2N8IhGC3bYDieZG0AoN55H5Gynj0eoq9FVksRvhqNpUXc9dYOOET7sM_01p-qa4UzA4Q53b
WcHGdkWjVMvW-ru_LJxHlWqGSVqdAjGlzEhPtmkGRrjJ7GROc5YGUtI8SeSyU279NIRptb3oQI36c4elSfjmemlY15gKhoYWSaa3gigtJDgdBXf1lYT1k1w5
HHunhtfWG9Pd5EogzaaUekUE14KUqqzxsEZod7nMe8gfF2V0MqqoYgp0tdL0cM2oX45vEoVqA4jej6FoFYSiea8v16G4MKQOq7wVSfeifK4_D6Sj1QeuoVzT
JFrlbb2ZomOwFbYR_rsE6iq7SvOjP0WYbIbxy9NITgNlysZ2P1SAgT9b6vqsARADmeGesuW0GROH05IseG2oaTtvxw-_aMGR2HjKsKPbL8PiOr8ZX8tbZpAt
5SYd_eAfR45zksaqsKBpgJzlckBYVmllm7HBTSRnltEgHJboENHq_iewmj0VxxWRa4xruxNg2MRyaT_raCzlkzBXSglUzxlUc2S1AXpg6IPOqTl-1dLGnvi0
MWncU7jbqdEuuNVzFyyT0uJS0Ijl55eD09ljskzwV-urG9tcWdfMXzGCmAxzhl_lkSv_0VopBSaL6bEEr_uAzUMv0QuCEKLTSE8ShlVdZcrRuDTuU2u-4El1
fOUO3-catroDlDXFUd4rLlfTGdANwwiizNi0Txb-jTy338hhb_izmA2uVhdV0qo6wzVxFG2kt-ENuVeT_lEBnKQIZ_m9
}

