sprite $Icon_workflows_0403_blue [96x90/16z] {
xPW7ikGW34GRJ1Pz_-DkzDyfOVt0WZVEgp3vDIKveC7Fa5bn8vxaWVke90Mt4SXA9YpZ9SD0AAZi3gj4ik128Wyuic2PQbXSPmMGoUEMW9VA20Kt11mldGra
n2mkvgAH8U2nx3RVuimhdVIgvU5nbfLvlJIDa6rixkFh7XCSP7NG9B8v_A0ePMV318M2WQprdimOYlLn6ekXrz_e65z_76668WpwCAxNatd5h_IgtaO_vlrm
OxMySR5Oy2lqyJwsUDrVoNw5b4t-JjguJVL9DWSc_0iy_OiqHjo92_XtUUByuHqsSE1AA9qaATbZaK9nOsBZW-8MzHm34ad9XtS-b4xsOqtVXe12IdY4TJAi
w2kY2XYsKF32xbVqK047MQ5mdVAn0yxMwu1cj9jCCzTRhTS1XrNjoextQMGsz3gWKCojI9W8q7eTq9bnHLWm6L37FWPI7EoL5ZPC12Yz3h0taFciMkplG3AU
nIc04M3xqzdWmlSubotMkEg4jCVOVDR7nRSfBuUXx-o7eK_sb5bPyG7YgLS1IezcciWueLS1Mez8Ekk7RaAl0hJUdX0-DZNqKwy3j1umEb0_DlMaUkfrWDO3
CfvYcSoOG0Km37guhYwNxZmJ5mASg9fu8IMwxyzpdzQF9GgdNYsPRBLK8Sa4B0LGw_K6eXS7h0P4yv-VMaiEMCRNWF-G9xaVk8tdVFtqftQbRFJJmk_qrwmf
c_qH6h_azotTwezalj6lvuTrVwN02DZc3qgc0XRyMYPvGCYyo-yQhtJIB_WreRG18GKB_eaz_dQ_rk_tQ_r-Vz3w_Nwbt--71-xqZv39QS9Uly5El_1ATtYJ
pm
}

