sprite $Icon_documents_1404_blue [96x115/16z] {
xSs50K8n00FHVhTs_t5n21gamNC3l4kvrO6Migkk-UFP9bBSjlHZnVqO7gyd0v4VoK3XTsIWy9kA31H-80E9JmOIdmmaFXb8V3AG-6GWyp7G-sGWyp7G-sGW
z35G-sIWz34e3_n9vcCWzSb0ufE1tCT0xsEGC13uTA3tCH3vP23noK3keteroFVRugJzGQv_hWw3wHd-5338yxjuhZfi6k5BUwbltxvz-_RjsxTltxvz-_Rj
sxS_shTlNvHz-_RjsxTltxxzE3wjcBw-EG
}

