sprite $Icon_orchestration_0101_blue [96x94/16z] {
rLe7WkGe31mG6TN_dti1zt9d2iQqntr1kvDn8KeHyDUEY4-beekM79pvUaPiA9XAJUxdu55VO3a69sAj5UTZAeec-KTJ-7A019dCx98shgAzYwu0DBdlLbVR
_783FIY0wYyjtrQHtrs3L01bIo_JJ1JVGJTf6xr9L43tBUre-9P2SLSR0EbTSucYxAbI0BtZ47i1RHN8JuJ-6Zu-YCSimlrluQsIPPyKKqdxHwK0_eFmwNlF
iJxbgWgj9OLVotIvQjvJoW5v_SUaE4i9feKY05IxGRv2pJ91zX8MGeZf1PihK6Ciu2TPCY0BzADAESCr-I3KqyfPt8fyhui2PIEWFI4Qqge29VIVAtIgV0QG
vgktW1k-wo9wjape8sXOMHdFTaODu3X9Xb20Qjg0UVBs0CBQ8tgu221JOteWljIt4_YBAbPHNt03kQQhbOw_AF84_ignNIElsIYCVx3zkmD9c7j0xMN4exP6
WoOs7QGlb7EftUgHWCIgIUUWEOAV9JlPY7eVKs0rchjqlua0QzOulIlXi8nKm95r-yGpSNv1cfV1GT6uYuqjDx4SuzYGZrGaCrzImvPfl4Se8Kri5YkwQFQ6
deXd1bme1t0PwE64PNwb_nBiNz_tllyKOnm6ofQK6awksdNkQo6_b8CC3cEvTCG4r95pwpFEYopi4OsP05mLvhaloTa70XU1XDe-FOBFHU1GFO_cDIBc1lvN
HPgDqBDZIG60RD_7Po9QtJad0ez3rBsDpuPis80x9sLlRL2eVHVVSSmhuXc_GitBvVEx-9OTlJPy-ViGtoFu1huZ_DJngV3O3Noo9WSOO9_1_vhXf-VuCGj-
dhAlJEtB_XciYzq_sR47Ckbdzaz_4LzKu3ZZh-DhbH-u7M1wmZ1VdNN0dD_ygAzlKBmVOJBOGbH-PoCBJM0h8AGiTvZ79sQMb4KQ6lTkjdLzYT2fMpb0U6jS
vNI2uyaN6y_ygmcvocCJW6Jxbac5kNQp-juBC_SdVAY592PetpBjzIS1MFHNFEiXHQYWoj5VCVrN_I5lXAlxue1Hg5cm_5v_6u8VtGQzsIABBDdsc_svEmfg
162PdivszC6zkR_WX4lqf3weKHZ6-BTht7N1u22AKmhbwjY22nxlNZk5Xn_uaLfx6zzrjDBqFBYa_RNSvQT0Xsq-DqWEGDYphmpsTVr9eMEAw_EDiQ1AAwZ3
lDHssKcAAelpcML1vVCOHHeoE9ql9JR3kg1o-m7tMcfU7EtJ1cdCRxpvjwVYbBtFWplo7LL9CNYtTu70-yDldT5dnKkk9s0YGZjfDDy_5L9HMkFY5DjyzXHR
_h-dsFdX-m-En_GlmxlRzDcwGOwvVJ_biSNztVkr1AZxsFsWgq2r7xlVpAJJW_Up9hwjaFlC_JBVZvj7xyTv1cHt-VP28lHDSULrB2aJR4_l9ppoVeKyztv5
lujIpAIcvzv1yJ6Vtcz9OHVxTm
}

