sprite $Icon_endpoint_1906_blue [96x79/16z] {
xPG7ZiCm30HLhVx_xzwj2-a8wOcGnabT0ZifCXZQK68RZjN3iF0RDGppJNxjDjO9PRjaIuErVQ7G-NtRcEQiAHSravT4bQah6ChvDVwgGMM_GuxiZyYE_5GW
lrqAf_mAxFmMhs7dnuibVrSmQ-5El_XR1etz1Rcolo8NydS5GuMNN9ysRBZ5Jnbr-6YWkuBj2z-utvJUwBFkyyN2T-wtPa5b_uISs9-GFVlhMY2_NmflkH_4
toBO-HDoONz1JZj_17JzKE4brwVB6txnKuvg9j90pzbJTdrXzFxvHh-l6-lvKbwFAz50TmM_s2Yd5-st2LJsH-JC_emSsLyF2eOARxaVnDyysFa3Sc9_HWux
_q71h8NyclrssfyVzfz6zbiC9t3NQjmfGsndCJTyozEKKoHr9UcaufNdAtxnYr_yORg16ASR26qqrPLw2_-DMoXEtOGPULpY1-8Nl_ZrSLnhJX_d9drjDrDl
qEjx_FgewWy
}

