sprite $Icon_alerts_2507_blue [96x96/16z] {
xTf7Wjmm3011a0B40FJ_l-kRiwdrSk38FauevQpWHwcyEUL7_PZ7tkuRYsRxRYO_aNtVc02tf7N_9VxnZt_yurSrCwqfVh4H040CAo_sQ-VBUdsbtm3mVflQ
tHs0zZA_EX3tfp6kBG2lh_4r8EphlmQ4li9NO9Plb_S4TD-_W2xVgmFNhb_YHxn8XoYFlYtz0MFzvI83NVCAlXX5VrW4fh9khW45buqkc1l3Vwo3Fet0sF23
a7KEx-ShT5dNTcQGWSawtJb0DRXaNO6nitYBF0JptVxWsGzyu_ZiakbB5KcSF_khy7uATwRVuShqWyZaBNdsEzJSqH-9V8tSqP_GSddFqyk4g6cyHYPV1-19
VB49q4i6RYC0SCrQPm3SyguuVTmrSPMlafWJQVRnZtzyJ_LrclnNgMNgfc29_7zt_xRsAzMVUAhln5_j3sQgBrhory_Z7__unpz-_liXsU-tPB-Vym4
}

