sprite $Icon_email_2404_blue [96x64/16z] {
xTY5SiCm48JXCqYA9UtxFsvffnFUmkcAle4sz2N-xJ6PMQeT0TDhCZER6iAcJcOLG2jv-9GEe5e2Ej0N6pnhVu5JHRCCe8pbomlPK3iAlwnEu_IfCab11_Bh
4-iW_VXpCq2V_nx6yCVSHzziwK2RXxMvyctQW9wy_C8s5pud0TY6jBdjszpOoD_cskSS02Hd6-5pszecJnljiz7oOPoRnshIFpRAZZRIFpRojD6-pTmE76s4
Vzp_UTfe_xsxLB7hahxOfQessjVhJBVHllwicdJLHlbwsVNhsjVhJY-VmpyUTaGRbyy6IRHn-EAmemyLsXVMLHk7BtQfRERqhtUfeetJfxc8DawVkzGisdXz
DbhO9i3dOOTj0dmsOfimtzOwMvZF-UF-xk_-xk_-xkz-2lQdBTEFcuuIwbUqK3y1XzW5YBWzF1tzgMByR4S_vFxyyHpr4G
}

