sprite $Icon_directional_3001_blue [96x96/16z] {
jPe74gGw34GnDaR8UlS_xW-KDqoWjc5jLPZyMccIv4Mnb3VpuAU5MytB8CkxyzMQbR-6boD-khpNhVnlMpLl_TxZRoJIViBncjF7OwMUqiIUdj5N0mWhwJew
2u1ZVKhtxOy9T02x6yFU_L8zYVqEFRTRKQTJGQ-q0RxUSiW14pFV8BRbfcq1BIiT7t2a1yti45fXw_B8QZGbzV7uBPaKV4lBD3lcudVmYVWAliop0Z7H-pM8
TGogHVvo9-Gn-1IqRvrP1nRItfC_jBOEvIqxGskRWdYFQ5i6sWRxYzxepdTONpuNybZ-2iVlDsmPR0Rho_N1bi1-NkMGyzhk1x3hxX-wA-lF5WfSzqalbHFz
hSkcutM1hR-93qB6DsXoYeBpYO6fU2zGN1Mmq_4CHSMd37bH1Ghaitja_7BoPO6pWnekupjV5JXeIuAguZjV5gXmPbJ5Txuia25NI2g-ysM11DK86T_vka1W
ZilupjS570zCndU-Bc04L1dV-Rf01TXaVEVh0Xj0aV6TBmjqleplV5sW06GPt_cwGEvy4T_vga3d5ndV-Rf0wVnhlC1F3dPHt-l-J2TUuPy2wPfVBzuRbXQD
loIxOa1WYsgThviHZi_ZEswqUVp0AgHP_0GrGvx5Bv0Jr5dy2ilIE6RndNQ-JsVnOJ-JLERm2-UJ0vl3DwB_Ff_33uuUnZQ3lq7fEZw3xuJm_-unVuLw_-zr
hVgia3Jh_tLtUkPyu83rzSPGooykhmoVpxpEg_RnywNNHeZHyx4sURwNvyudztvrnWInGFlIKT4c3fg7rfOo4UzGv-9j8hx1CG-_DiNxz1HV0dPX-r05rlFL
N80_tGygZPaVxJThw3jN0ppFsi_sGg7llDS3QBSSsa-5LQPJxvRB0FoF1Tkkzllw-OHh7uf5fp-oL0CWZbhI9xiw055L-lK9Ydu-vCVnaDtynxrsNLLTel7L
V1ztXgQ-dy_PifQMVm4
}

