sprite $Icon_Partner_3601_blue [96x60/16z] {
xPP73jmm34NLA__zZvjgH25autkeLSfRos_OCOuG1ITqvgyuW_ibcsbl_DEPoN-_ls2S-Hab7FivTdzg9rJF_88Z2lC3SvWHLExFpip4kJ_vKpzvCaxzfltz
x__l_-__xoyGkxz0c3y1tknl6CplWMJs2ohpkubkzKSWKdy1Wj4_88xwdM3O_0d8B_mPg1P_44ptmkywK8d_NY_XyXC6qFs7_Y8_1qzG7AK3ScDw_ZXEG29B
KKSZMw9FoOUENndtT_-_VGCmqpRVWJtDr_vJmW0mehvzyf3gAfi7AP0kAjflqGZQDim2_SOr24dWwUiAX2s2RTIysaz6NOsEGBkfODY2mdR1MAFBjJ-UJS1L
8GnM8Zrzton9875Fx9QsElx-DvG-Yzh0VQQsrFWoh4AdduD5ui68JAmdVFvCEgwsik7kv9KELW39GRULVqZ262iCtm5WQojD_9dGT1dZ-6moVDt2sTgQTTA5
JlOUuOmiEmwli2QfqyFXZIQ7oyfQHxeTTlpFSq8ErmdXifAsdZPwh4eHR8qcGtDAaH7E35y1
}

