sprite $Icon_SecureByDesignOnly_3801_blue [96x77/16z] {
jLY74lCi30lJWAttVzn_bIlHkILj-d-wrMOedi9m_89Ksp00fgFLzBYMkzcen-ye7Gph-JZcHOs_aGSn0B3HQYcbIXi005D0fNR0ma_i0A2LZ4oY023_1Gbe
FqJ606lHtqW6U_mIs6tZEu3ssds5p2y1DpCG5HZltZNK-THT_cI0lBqxC1u_Ad2Ntl8cCq3vptn3lnKSWstzLg2bLErUU8B1qbLs7iZ73GmWVTHu_LPoAr0_
yV9cPOPjqdv7VoKg8JV3g2zCpf3lQiT79zQ12PLqC0G8NvhFzZK300of7G1WBPy90xvpe97vKvzx2VIn7iuls7S1EXl_iDVhir10yss9VjcWGKds5Uqs_slV
Ep4Ap1L4LntJRq88t_D7815xnuJLmztG-Yt_OU1t0EiYJS65KF20XWt_iEZu1ngnM5dsZbKOWDMKwPhZ7q1o_EtqHhIpVOBrv9YwK85C_4mlFZu2UwSkxLc0
0PXkAJhpCxtdhx2twc9ep_24QGwK-VNXSPZqZh_0w5FEDnur6WQz6G0DPthFZnMUfUrC6u2w-f4iAu26HR-BZqAOFm3vcPaqKvB8iiS75ZqN90VKdBW3vLbP
QBKhq9nt1LZqZgMXx_dNJ0M08cYJjPpfCwaU1NJ7VmHH0FdbwbJap3SynOe_WmYTQS6WVWL2TYL2cU7y9lfB3ixQON43c8FRTp1_vkNPFo20PPxS-k5RT9d3
rZJenOfLpZ8h0CHPc4xnPEUYUzmWhuPD-VSBrU3dwauM2YT7tJ0bwmfF4RsPtz5uHTDpGOxvXpFS_BBP0BY1jdJLDc3yFGDw_k-N64TdjsSBLKsuT1KFJFFv
kgdDUzvMSed1D4EQmRjR5EJkBGXGtcuMOX6f-IurLxt-x-Cy3pq2_JFyaLQNpp7i0dsD0rvHGihxh3PS8Px7cGpKWnKUwEajVGPwVOyEo7CSAp4Ae7GYCY7C
oeA_WS9ud8J5KycYvHXYfQuWZDsMd8UxD422L4xdMHseRxgcVhvt3Ic-ytnCGnW9-sRf6--4xWLTWNDolSbzlMne7gJzohs1oxsR3FZ2S2kXN4XQsjmqLmlU
emj9QBlKT7U9Lwz16V4Os-GOP7_G8_GrZxA__-fki6LISjwxPyULNZkafHxrGiRRflHf-qCegw4ot_VloqNqrk-sg6IzjuLktUDLZ2BPVK_jTUswF0LeB1I_
dyaDDCgLK5lLCzBsJExgIDghPmP3FjSrtYRoyBNCh7R2vEzwWa4_6oVuX7dJXn4C5pFlON2T5GwFDBcAdB4J1Zy4UNc-VHhejq5Udjr-vWP8dLsLKZE4E_pA
LBdy2mLwEsC0a7ADAtNE-0tDnySYL-TFyCtsDm
}

