sprite $Icon_industries_2602_blue [96x74/16z] {
xTW73YCX30LGsvInAVU_xefyfFG4n6pdfqvxWAqAtQOY9LjacWf7owKYz3RrDcbuZ9103_ZvKBlUdSC0dcjFIQP7_kmR8Txw8CQVSBPEcoV4HdmaOcQ9t-e9
gumudF81QC4Qti-zA2xE-uWlJJdeAV6Yeq4BVX-X2Dr5SjVNV2G-BU5ePo8XopuQcQx7xJ0pdU8ZePMZYz8A5eZEz87wzi-Z7IVxA8e7dub6VRk41tpIDa3Z
bGPyXbmlYIC-7RZve14_rXupKnxoIIjcFpH_xRENeVeZDdB7zK1cVLUh-mt-zhU__UrlNrTz_Up7LJzyziEal_tjRt_xsz_-zhT_2A_uBCTdlwKaZPxdVFPH
KqM--KXMF-gx0_HNNyGv7wBrsukwxxxJWhkJnU2T4tdlNoF12lOs-PFFs2Cj5cwK4VywinBV-x5SLpdf8o5XX5S-z1HmCEyZOcq4_-pxLXaJeWKVfZM8xttM
DdVyN_GnrUAlFlPqC_Hrl--yQVUlX-Vvv7AjYU5pmkJFz85AyoMZ7QVwA4e9jOQ2sfpkKwYrNDwUPdmlemdraYYZyVMlpmy
}

