sprite $Icon_industries_2605_blue [96x86/16z] {
xTW7RiKs40RXdvqhSkv_tFGiyc0AWaKfVL3SFx6wwJjbWwC4FPpZlsNvURnFWD7Q09ZzoKUaFdz5aoJ5DfzyH5fmwQb7n3eSMi-ffMtSyiMUt7b4A0S0Hxa-
KumQR-91tjKZWho7l-9ZD1luzeHzn-Bjqu3bApozSE3ynYHjjBZSspV-QgZnXUzOljH1sJVbbU_cUO8LlL8nc93rMXaWwRNIk_x__l_-_xxLrp8mNitK9wyr
k_uU_LzubwjKFLWdwoF3T56iDYRCOJNgea7_dX_g0BnHd_Nh11YzrThw09ZrEJyDy5-z_RVnaHxo2t1yOae7K1xnAyo5L2RKBT_v4RKe3gZRVeOHj2mCo9j-
c4pdbn_SymsIJalGDtm7JkkGTdpp1JXT8Tlm0xGJk6NzN8DmtwyGrlnWwkSYrFl-mN72-yGExBuFxOJths_Cstw4VC4hGxphPuWNl2AasxvlRxMuvXKWt_MB
-vCPbxm2bFtn5vXnmU-DFq7KnmESzzB6-llO_047zCKSR_gQDFtn0SDvhs-SVnb3NW7eNoMxxnU8yig2Jr3k-_eKonTU7RJXTz-zTH7wZX_1fFCCuewl1aMd
5MZQyZMOIISb6Dhq8ynuyg79ZBk-Cioy_C24h6rVcUKgDvpVyvKcZAAFoi0tPjTNC62szFaVO0lQzRqy01ZMk_tsQfOUyBriW6Ukx_jUhdQCSLXrVDzVz_Vp
6qqFPXHz5lLeGV-QGdoj82doNZEywnFq8m
}

