sprite $Icon_communications_1703_blue [96x87/16z] {
xTL7cjn034DXg2kNYFiVruaBsXwDFapWJbXs-5y71G0eo_ZjirNWMqpQmk-Tf8rQldbr6Bdzqq-aR98BnVciG5aqfCsuZ2FF7pIovlcL94kUNnx_Pe__-CKM
RhQiVCrlvBhXoIRvjyGIdXDy0P5vsGz6vtK_89aNV84IUDrtJE9r_vvRv8Riwm6Tr_q8tF22BmTcyBAl1vnFy3tWV8Rl0USpV0yud-J3I4EUFqbovlZExqtE
5Dzvm0C9llCUIF2TZu3ko_o127opFuAFWExhV0HqN-VrWEu7hmTqFtWX8FWgxm79rtWzeFlEdy6B0TrlDpoEasnVyslmru7wDHy7bAVl_OGz_kC_VYN9dkTt
SlFCyq_kblW5EbcnoPx6R-0mSjVZk_6ZRj9-iw-JbrkusA2jTzOHgqR6dQaRhtRvbMzs_FiwYo1AxVzjNVcJv5xlR02nLWjkro_y5LzPdkuV9xc0BByOEP7c
LoCxqln6MaMQFqWhIFCNURwGvH-Rt0Uo_9SVbrb-CN8WpMya6z9yFt3I_4NQ2qb-73WvVXmuERuVE7a-sP3fMqNUwZSTbpy1
}

