sprite $Icon_threathunting_0204_blue [96x86/16z] {
rLY7SiCw39EeIP7u_yzzm-PLFKTKniLleBjE42w0LiABA09WKBW93IVIFVG9a9ogGk_XPsWyNwRSmgzenqz1_r_oZxFm1DGxwACSiraK6k-O7eNX29_QTwUq
0cWcW7OC4_htqeWCQ0eXAfYFDcG5j7onDkE8Lj3IMQ3Ol-OLzQo9yGSs0IS1qBvJcnmc_v70WQfswGkrcVn70lErmHG-Hm5ChfF_IC2G1T3wbTeO_rJox8vy
9WOIgys5tn8mq030yUFQNFal2Nmi1glDWjyIc8WDm4ZlRaEXiE1V961YUCKng36tU2HjjLdnfySbMLuIGyK1AwRB7-WIwekEKG1b1f1yVX_F7KCXCGHIo5D-
wgAS5-bBzWEmm0iGd_0N7E258dqnPECb8Etv4w2zoKKWqp7syMU0zlpZtCAyIhJzE0Rb72_r7-5OK_ga_YQmk1WrSumUQU1Qh0fexmgWRFaZa2qWAyL238e3
4iD41mnj6xzT9tkTjHXG8xLBYr8NwMJEwVFpkU-j3IiK8-vGn_c5V7vIOB02TUDVqMR6kwxPuRUzwQirLi6MtrozRVoXC3TQFvEjXLR9pVhYhV_ueMEK0JHA
l76aE00XbzyFNHiTAZemWe--sEy-g1sKdEUCGDlJ7LmTVYVq-Ai0ARroVzMVyrEtq3yxLyGzVna08FLtw5pVkP58Bh-5hZrTejAtRg3Bcj-cqKAV68woNQdf
YZzrMEWNE5FlWhXQiqTy4D9ohFj7TxlJShA5Jclhul0-njmCTJUD5P3FZadjz0oA9gGbCY3ne_27hSOMUi-RUnmblv4f9zg__p2slIFrwGlZW79PyHklxFYZ
0ibXLqn8MLscq_7oraoow_MGbYXIQeBBXCMcfpas1cGxOiK_Qit4ilmU0kf7IjsgHplwwkRLhX8SDX0C02FRRnntHjZTAsKjmY80q6aEqMxPiIk9jdfuhdfH
ql2Lt_nLAykUAHxzgxksNlp6vv-XYbrKMfphbFC3ItpN5MPGIMr2hEoFxI8WxLt1KwQ9hrUsMskflCWOg8uhfE01DZpj3Ax0vh42Yn5dpnLSsCMVvwe5anV5
xf2bUafunZ-TYp62msyDVc-P0zbuvQSVnkKU0VrbxjU_0Cs4PVtGu3JuhMKku9z4TIZcdsFruFxcCfznHWQcDKSBTTlWQgwm0yq2fjPRced7vPf_UvdpwXX8
LjTTWpFicNlGAaa1eZCDpZBtKH-Q5DrL9-YUA_Yu7dT9tA6kAEuozz41D9eBrwFVkyA-H83qMceNUEzdxbrXZzWnqNPJaKgElYluY8L5eS9boov7fW27Ev1X
u70B59eZMV6_Zspo7P0RsASN5k1M_deJVpPH2KQu1GAqbCsTRW0f3lHm4uWT-t3n9m
}

