sprite $Icon_cybersecurity_1206_blue [96x137/16z] {
xTg9agGW30RWS2l7-x_kbj8xVpLniEZWdcHtRlqCmGCL6WcRIqcQ7WeToncRUa9NMzKVsaB8fI1ocAlxgky77UiMt3pTffDCbexF-76ERf1mzOdSgpbQhgkz
wfxeoqV1WXBg8ME7WO_TANjHQL07-4tTag09PssY8U8--btGWbXAjaIjZ_1YFrBFfx_DNxxFsNpcEvpq-hly_fcVwwgzqAd8_99q__egzN50yd2bYFrEXvzd
n9Wa_XuFO_l-PBQHo0yroVqxtfFKhqMEZ8-rQ-G-sRe1ddqsDCCdmm-4hV9pV3AvwUG0dk2hhN2V_oBxrgyRm13ih9Ybng-3aAtlfxFO6lw5g0x8qRklOwby
nyTY0JuErQomwrG7lgzZ0qDT7oEXPDvzGctTpqw3ZwpkV8p0jkh3gHMgt-Ytt-U2gjxvE2sczupqAstV99eA6nztVGpc6YXydG-oOlwkgE_p9i37RfF8u0Y1
Z-JlVVG2V0o-pD4orHpAITEmNu-NjxpKqUkPhU7Hd26VL71yU3aomE1-Ftmvmppbc-hhftoz_EMtHsJVN_w-_8jO_lANht-Jl_pbnp8n8lDTcHgkzSrStx3w
XEFRS1Tn2tU1stBukCqMn-4dOZuU4qYYrZbhxkDFagX9McfzD2tA_1r5vZv5sUDgFClWFbedg936-jp7zZyEj9_xg5yOXtd_SHyLofUnDq_1BoEhdjy_3paq
ihDCp--lxEyNsUdM9n-kel5pk0h_-VMbyIFrG-ulV_dBN_xopLE-gRvxodVLtnxmyGwfbFoKdqk93XqmsxT7xV78SQAFqPoY7GsOvIFz3U_1flfuRrTxESpt
Gqt_DUGqytnK9ojyg-Vw6lT9jK99pVHLUbK7UrASwGF4g3_EyoEx4y069lYHTwZ9w0EXhnBuTWDQxkkJDzTxLBO27tcox77NvcI-xqn9L16tKEC-Nc97rRlW
b6G-zGrcV7IQ1sZG3tnbda922yTy5Tl6TqgOxQZlkhNXI-vgn5Vxm9nbdR3mlO-KaXvu489UkFLrx7Hihvkpl_MHZAQXm0IWlc-HoK2WrRlg-JgYaiFXCbAx
y377sigc_2TxvMEEk7nkUpJSjsd277TCbM_y7D4qMQXm-NmCNICElL_xGT6aC97vhF3YRi0OrM5I_Mty
}

