sprite $Icon_detection_0505_blue [96x79/16z] {
xTa5ZWCn38LXPnnIx7V_uovJEbwrbbBsBof-mqnVTLXjTBGDLfqE6Z3IKto5qTZxFUsZ4qhxkkdJicxN3p_yyCDFsIVcvFC7geUl63vVq3n-WpouduNN-IoP
Z1RuTdu_yrbzXgxrSptmaPRw09_JJq1-83_yuLj_gjVdbdRh_mIMwMrgJBTOrBgPgChVT7wlkw_5TXhEt3_ZhvZ75yVUg-sqsF-47_vS-E4hdTEdpEVrYPn-
4LxdinJ7zQFVxnWFxWzKZryntFTF7BxZ_icKxTlTiHy-ARQp-XjV-Fva-E6V__dT-Py_dllvwIi
}

