sprite $Icon_people_1801_blue [96x73/16z] {
jPXPciCe38Gbn8xg_jUTINlI67rod33f_waNKm4jLX7wFtGyAVGNu9TEVq008Z_8KFe34a0_213e-nGCEW3YjpGhdz9RwM2S4XnQfcqQeBzRLUJVFpVwZmoW
xCi3UEuwpgWKgD03xdXGjkLB6C0G2bK1C1r405gOaWADEr1svNys2tG0w8cUv050Ew3fwBkoBKyaFsAPwKme2g3pix7Bdln17KwDS9b_xK2cpnZGZrgxqcV8
9qiwb3zlLyHlFseZnEyUjT7dX7UN3Goc3JAGw9uA25t0WUaQdGVOUIesdNtf8E-bhVXv2XrFr9Vf6FG6h5xtHWLwaY2fmUy-ThOlgIHn3a2Me7FNORY9pB3B
ikB1I3QE4AUumtN_XLZQiEN97O0E1L2j64RDmikibgiGSbSSYBK_zR4dwVO3CWwqpcVxPGWJ08nM8fj7a6R5HxBdLG2OLYdPNfLJtCKjyqhEzYOSWIaNxEfa
ycg809jVB0pCZBDDKJRwllkn3iZNZm1P_NAdtnVzz6NzZB4eoJVrhUbC7yTVb_YdyFerERpwaGoOyxa9Im2EXhJskT11iykFTWTWmk4M7DU1WsWTIuz4d0QG
JUv_q5wktjaTtMd8PWVLasn3fwt4iAHYMPpjNlqaneu7BRn8_LIiKycTvEmKEKiK9aF5SFtVEFOi3Ru1QD0tVKRsnpwqjpvzgYMywn_yRKW7p3moj3VzGoUV
a4ejMUWABe5ky8jZdtrtkm_hneK-w0qdoUHKaCGONX_w1bcBFJYDgEMLfI_faWBKw_iBpxrfsBcz71dDlu_mE4fe_jOJ4uLozG6i67HD-f4hm913S6d4FdyJ
lNepGExhfG0eHjxS6WJeRiVarnUAy7ip7ZBbdUj00kg75oC1yZeIqZgfWjbC-knYDp1McvzMlMvh0UBVftooiSObkaRaN4uQl3dk4zIlt6jd5nJ35CV-oom0
mR6kxRm-q3NnPkP4m0rfMLfdPvXOy-SNaMYX5nJ0EvrVFcoAw1u1ojsigJDKxPHLcxQD6x4fpmZKYnV5_gG5qZdgsIyY7zRxHvOuz_D-2bOIMTfj3Atn7r0v
BJzpV79SXrP-ypjmFwrnaevpPYoCzxy3jmF6lutAq3D2TrGqAuJkFZSshLRrZBg5WK8xABBpRYXVStocGVXVGWToE25v09blyVN3Kj3x-15KNSEmZs_0_W4
}

