sprite $Icon_cybersecurity_1203_blue [96x96/16z] {
nPg7qkeu38NbtlIz_-DkvMek_2GA9ZjxfeFvZflYI4QkAEJQfsBIsMkKUnHoMxoHtaBFmu1hzDx-KkzZ_UAtyWqyDWM0MNDy6LKA8b8WxjCx0AibELA5928n
Rj07W7Q37_CZZF0XlW5e4H6Vdm3Q9mvv0Sle3l_VvfelupkWLUGgNwGgqAyD8IviGg_o9GnWHV5LrCRw0LyaN_jT1MQGp_aI9j2ygJzeu_5jqmqvqm2AxFAb
0CF1PzddIz8pWmwQP9Tl1lqePWs_mpU3emKiG9Pl-P8EC56XoFTyoQ1l0cr1apluqc25DsixvHw-JEXl1XNkuWVziGJsoRTyw-thb0svZo_ZUOOYQBYJ7nJY
arsLE_bIeV_U_INtykNt0GmeT_CB3B_x-tnP46ppbFlvrPu7Yihz_F0Bcw7B_NpfZv0TrkXUVlftXOEjxiryMUY_qzF-6tw39DAjpTty14raWTpBDobBWdEk
bBhFdn0od14IZ6r-WrJF3vOCZ5r-XjeXEdp69Zz2do0Udx775sKgo-5tXR77NoWCXr-ImjZYJu3kyIKfv1t-kCQNg1ft-0sWkNpJ5h_-h_pJxzlNyvDEltU2
KvgxlW76wVwJVRv_-3l1AGES-3exVloZRy995xot2__DOA7U58eUhc62vVrsUbj0wk4CJYydYT2hrqZMGGWqj_iPwa40-GbjiJJqDFo2dpUMTq7OpFNyV7VU
JumrdleQ9pPk9ppi6UACW6xDKlVgUHOUJf0OSG7eQBMseLYjpGtDo--tHJ6vbL6Bha_UptFN1xnTQfzWV9XVXFINVfOkPZpCB-mHkQ_uFX02wBVvdSMVnfFy
pfps-MWypa-bG_cIZyQZ_DeIx7r-csRmzh4-e7x5brU32lsWFhF5Vp482k6WlhJ7VpOOq5vNEt_3VpOei0xgUvly9uEWa9pwv0RV33fqfxwwmpU3pdBgmtjy
CyZ1gMzlySt0gSzlyds3RWQR_9HIrXE30UHz_dJlXWTGjlYfHrd63tltKyVy34iAQFrRwQRxDUCNW2eBqettWyPVZrdFC6-ytpG-qFhZ64WRzxC-lqfGD6IO
Dzul6x_-6vxTSWvFZUjZM1GxSXEi--xtHM8IaM1RRzW0VCNklMsczhmX5oGRm0M5a_zNv3OLUEfjWPa-kudAGtbepTvRgwttiNX8nnDh0NnQ3yvjyLQhvtVL
mENWh_q_fxqzeyQFNVqd
}

