sprite $Icon_innovation_2901_blue [96x107/16z] {
xPW7qkis30O1acB5tl-ugVxBo716KFXIlLFSbzNK1qa81PKVI87o7_2__OVLYB_Q8I46w7M_mWXFnBZk7_5f6v3bYGH9diWm94Y2wRtjw6L2aYZzyfWFw196
3PDBB4mbJeKQ-5uSkxPg0vDRv9xa0gbd-K_mHbFEIUL7aEjOF5ZZKDb9QiQ9LJMqrREy94y0RFHwbEEeVV8RNIyB9mmLbpG0LatoZT8Ce8cFZjFfUxpyTWNm
HbSciB8uD83wt4ixl8umahYK1LJ_xPdyjrM-anPOaPSqdev-dS1w4G9ESvJiQrbyii4uDsbLVBIlVD9t-MFIEZMGLrUvX9w6uwCBcjnXNlkXhdkPhbqD7Sam
bIWPbbxE3qEYBCY1B7R4WtAFH9ab0SAPfaO7KA35ijYAn_C0BR1QT_9yYaNG8_oNcLWiEqkC6feWOyRBXHgP_hOd3FjaE2J8P4MMDqkG3X5_aY0Dr9-t1wRV
DuDAXFDlzClA9-cEtnzpufFI7XJPrtznhBVdFzwd0ld6-lxG_J-m-__Vx3HtPFdEOjm_V-mfoEQ5tJzI1foZ4FtqRsKwDsxkdl-Dxq4thrDxqGkUGd_AcPzP
jpl1tnWIO3vtfpw6KCmfHOxWZYlEvI9DO7HW9IVEI0ZpVb3vZHgECwwg-cb_fIrtcFnGx6_36kp-mpGk-lLMG1zGNB__pJ0AffxV7scS2kE2NmsIt66UPBv_
-CagNbZv_W9J7C8pvFlLi2GEuSBAz_V8xFWxs_47PYTGUZf-P-_4690zltymn4amNRz_YprEX-ELlyLpZ5zw-dw59N-Q1iNrFpxPC83f-uqb6-YGFBz_JO-J
eNd-YSaM5jtnAtJPWXvVJytKpNZx6I2RYIV2-oIeiek9HvPDA2wwqMyFuFC9iWU_-6aX_zl_zfVsdRdRhvpHlVrVd90Gx_rp7-Y1-vr1_FBVMBAD2bq2TKMO
1QkMJ-g29Hj9necLP2VQZMzOKxd6pm
}

