sprite $Icon_documents_1401_blue [96x115/16z] {
xTQ5OIHH30HH3QFo3_VEB6CPMj-e3k3Lxh2h6mtdyeRN_FtP7R3pTfV-ER1_siUtGY39Fp6W-mi6T7yQCA3x1e4K7m8fFWHIV0Ya-118yI6GuaCWnOT0YW-1
51y2AJu4Kdm8PFeHw1_uX-f38CM7G8eFWHGV0ary6pm22Ju4Kdm8fFWGIF4XqCwtyIgW-tFtPFS3gl_SbWWSBVp38g3vo_dSHhlP3hwszdxvvPTV_j0tzHVt
GVRv1J2synTttqpscPTzvcMVUTbdNlQPbttcPPzvsMTUzeU9UDdltFSEUDNl_J80lEZRV1S0Nl1jYW3oxByQ05xn8m2yuaS0UCMFm1s_c-1387Z1fq3mWW_t
GHnxmOS0yB9lS_22pu7TH9y3p_7r_Lp-NdxvvIUj_FBBBx_yyiill_npRxRJV_p-0m
}

