sprite $Icon_global_2702_blue [96x93/16z] {
j9G7hlCm38FblSJx7_SVAGBYfJJWjuZLAlQdRJjGpBKlnosVlIRx8ONS7KghP_ksoiGb1-2ZBems0RY_hDzp4L-HpvOQuCtC9ffPw83Nt1O0U0jVfOyBNe9P
0rQqcs-M72XciLukUlmIdS4rO9WP-HOMK5ufNXu-dKC3uDKkbGjF_kqWlNvLvz53PGUyt9aufZtv5XphZhewi98TgmDeTcl1mplV4hEwEexJ5E829bjMWMI2
RnNWT2O7HZYj3I4MWMwIRnFEFs40VZ185V1ir8273Jy2rQZYy7GmDoiObO1Y6xvr-kPMK1e_FnW6bctv0MZFpkqTS96e21J1v_cx0zoAR1jnaQXEWE87kd-i
dL9cSNY_2hue7nrifoZU6qbLDb3p4nWkAIQr2AEfc-Jh4znheVxUcaZJZb_XOeEgAZwlol4WNuT03I3QKooRI5xmQU4PFgrJLAVcXmhG7gQ5yR1qU7wg0UMP
vayhF4hsqsgsUSKeHxLT_QdESHGldrf3rYmTy0lSABduGOPV03lWHo3A1FISKntpX6_Eu3OXEs-9oTPyVOuQZ2vpcaHSch_Faz1eT2KpJ5l-li6YA43H0TWH
F-dq6zRjNtwlSCtNYIgtaVLJ_kSPd_dh_Yqq4nheX_o5gW7ZIa-yu7Ih-3eIrNTEfqvFy_KBfFlEFZy5PCtNdT84UbTJSSYlcmWTbLS4Fsg-BhIU4DPPF8j1
yiysaOE_6Pzqpa_aYxe1wVlyi1zGrbadVSxN261qeGa8gsEz6ySMSV5_JpyKVr_A-BTKyr1k68PXQ3IywV__tEoWTL_ZmnrvAnEo89ZJklua_wVbYg6V37va
z4-Z_fFtBur-TKlx7ndzZrQXUVvJrjQ8kI2k8OwR_f_7zR0eG80GpVZ5ycSOOr-W40GIB_woyAzFmNSaEBdyGMAONr0RyeVBl6-P_4TDd1Sb8ygJdipV1Ak5
ZlbRIUMVHrfAY5NHaioVTQmwQENFIDMj_1zsa6Niwu4UBMLWwJDeavlflrGpP-gl-gbrQtd_PDFRjzL4_IZ9r3qa9lucxFgNCXkK1Qcs9fHVlrERmfT6kG7N
5ZIJcl3ncQpQ-3fpNIkpn2tH_vd-_gqGluDkhMdrhwXDuKilgVuRE-Z2rxgv_g5u0Bvu8njHdVudEIL-aKz2vzNhtqg7nDTtkVwpj2ao0_TTedzEFr0B_GRu
iFh_y6CdCPdpY-BDBrOIGByD6vtvY-88ZN67Pn3Dc1y5j10hu-QN-TTyEl_YnL6Vt2BdTq9gm2zQbVZKA9dJo9NpHx96VYWnVtwAFveQvHQsuTlybnkdaKRE
hsFyTtxTS70mU7XQMvxn5lDtD7pERxApR-TNo9twzDYBy9LGMYNscPLXEJx_yE8_zfWTMqJisHA7vpUszoJMjArOEkZJlCOF_gMCYsFpdTCR
}

