sprite $Icon_industries_2604_blue [96x72/16z] {
xTG50eCm44JHi5Xixd_SkWkssUhyAlPmt4WICL0KfonYiAZa1UZaQHqWEhyP50Ie_zgdNtN-ekXl2e0V20ZRdwT4LoMObe2SZXq7BijtOuQdvaiY0rV7Dy8x
PU7oaI76FdtwzEdJfq-VFlrGAHlnzGtv7WNopttN5CWD-2NwRfy-VVhqwTEdJvz-8sOrCC_3j7uD
}

