sprite $Icon_email_2406_blue [96x75/16z] {
xTY7ajmW60DWqGtyUl_7JVDiTCKP9kplrDFriXz6xWPGXz4xrXFE1ECzQQS_ISvQV7EGP060IaxI4Znpa3Pf033OKJGRZyH9pXZ93C1Opj-C09za8my0anK0
MHupod28fCdsy3NgSr4JhtsrvjFDbGyqajMXcmjVe_VWqSsrZp3sTmLjvJ_sWRgzA_HpqHO-accI6zqiVOHEMjxjPkq3vMTtXQ1k5lxMhg1Arxvs1IjxtQnz
xGeRtQnzxGepRNIpy9MwE5mi_aV-nhAfcvcmvwztXQHrjE5hsrXqi-rhLzXP__BNn_Ios7vtVL7BRlPzH5K1THFXvElC-Nf2Vhxgrh79qTUPKzsu-jeLr8sx
ZpJ9gMxSVOHETUFeAzaEu4OV0VVw-6ly3x-CAF-U-FkfzPPkyaC-Z5zZHtRtOnsdtSynHer-VcgJNpDRqb2SHtRnyxd4lGHLLVevc-pW6wd6bNmOQS_wgqjO
5p_ZEkKt-Hz-iNQdNyX-VZ5NN_mCvzV1xkoBHo4hMNpy-8v78J79NdQJvG-sL_p33vDF97_tEzd4ot_g-RD5zJF80-BbUwtVGJRnddx1Ou1NF2hDmTScFiJh
Bq-daX5d-Yi-aTd13yPnTO4T9YSyKiZZiZSckAIH_UgEiC8fdHpXtOEB1fTSFT-lT5jwWJtgLbF3FHqLmYC2o8Da3_1EDPAZJP8puuQ4QloQMN1Nok2H0EKp
}

