sprite $Icon_process_1102_blue [96x96/16z] {
xPhPjgGi34P5GW39Vl_7_GURLSlASIYFUj7TvxkiOPj1GeWEbpMHXYVLQ8_o5SOd-IFa6p1XbAJvFscIqIN0BhAZLkDDLZKENGdY1RlJWkskaSBy2oZVfKjb
LgigSUm1ZwArCQl-RtdzRe3IJB4YOSKlAGRGqY0Wtw7R38yxUPalOScevtFQWARX83iwNm72oQoMsR2FtKJF5XLCJzboZb-epkFz79okGP_Hnspz3XlkLqWJ
0DCpzLawF3nNbvi-MPab3h-FVXJKsXsSCeNDZKHkC1FAHWtftrnKXRXMGmomE-9iDBy5KaMXWDooi1STuwk661QCEjmWMyHXwZKaGHeAXAlmpbhjKgF_makc
EdxaGFjQR7N-Ojfhj3xTJDGbyjKYvQrUUDJ9TsuxwebqYsAp5uxPEZP3hingEMxo5ubqBMgZhKQby-ByEod6NgGMYVGjjlh5DvEOT0xRpEykDO3DTBa0GUdc
kWlhmihEV_TCjW9ax-x8gzKVbihzTuxVDMxUp_Bsm-pISPqVO65efGttyeT6TTcubrynvyozV8Mm-9dSpHSONR9lvSU5pGd2dNp_bS9mDtzOv3J_dlpyc_Fr
oVm6qAVlpyVNrt5zKF1y1zch3yVrJK2s-Hd2Ndqxhiy3JDjyemsxzNb_V-acoXO_RuJVcRphPp1iNEUdxjlX_kZpv3DWOOqVwLTUI6LzvhTtSj7ESNm1ubTR
WkzFZaUO6KmyFxFYymZgmk_SsVA0yiOV9x2uFOiMb_c34QOOMEhyRdmRTsRHNmugjITnGs42clpYgm5vRnRzzQ0beCTJl9QX6Z2vsBX4AiJJK_niT3M_gdmY
ZRPn9jkL6i0a1wVt5slKDlb3vRxY_lck9t96zUdSqW6zPofN84d5Hx9XuPR3TPyrO7bqUqUzWL-0rRduJQTt0QYokeZAS8EQQHX-7_qeoeFmCRU-i1-Sy3_Z
WFGQek49U74rP5zdJMY-XkpJA-Ly5IoV6gK6qpc-SkxvMWcdfzG6s6VF1riSpgfYoOwcaLAEtTmxMAIUvXJMriRh-Um9-GO-LkYZoUNpvLoDMJLUsEV2Py_7
pykFCAFMnfjQrJXSavz5Zv9KSzR-Vi9bvUVVoz3V-iMLn7GTyYy
}

