sprite $Icon_automation_1306_blue [96x96/16z] {
j985WiKW44EBZxtx7tS5rkKxgLkacUCAP0NGTEn12IQYRA5F0LAhG6n9CA2-7YkC7VoEhHF3T_37ksq5NFkZMgXgQV7Bk_-5q7Pt4KK2QCjsfDKpriMPq7gN
TGC8MLBW-UNWK5vbwfJ6sytiFidhbm720nZVqyLD2jc0wEdRX4xerzUQ0tvzr_9NzDH50liZfgHB-pJNEdzoZETYpKFdaHi6mj6kLfNp_e-RGeImXVyp3xWg
bEJkvB6e8OT5_XHcrr_dQkQYKUTU8xTaoDTEPAn0-9OfoUHhvF0sPygP-oduWYa-YryG7kYXj5A5gT93r-QybENUosk4CkvCOU9V-I-BVJPWXUirAS5lT4If
nVMjZmVxDduSCSFV2NEWmEW6vQkwplYVaJ3djZqfl-u73VXrrhTK4-QqcqTByNJUooUYDcNFsTgMTdAkKFOhv6QYiprmoClYq_TdtgoxhlijkIzBEoGERljO
fPkqkscNZxJLKs6kxeSQzxT4QAg-sJO-tSuCXHcd_cezvzxhz83rJlYKRYRN2YdCDPoISPqCsm4_ZsjUpDdpikGvPT-DMFLmvKhmuQf4sKuKvfvkH2-lxGlW
uUFWSgWmvUIwIHV31nP_PoQ2zN-73ISW-30EH3rLcE3QWkifAmJFzazPhZ1V7DQt03o8N5WB2iCrW7Djsklu61yt6BcH8bwbcI2RW_l2zu724C9Kr5z9iGtt
1Gg3gspvuegdZkkaitAPayFBI9pGdmfHbCEF9Rj1d8ZkZHJbyBubn6d2PhX-34A6VssfXpZ1ecXoXKdWmmcIH1J2jQKL_q8nn_3X1ASuFQ6tPiiDYgwyKn2M
5Dwte3YDwFGzxQ-v3Bx0qmp2TzuINAyfsUXBiZBTJVnJXJMRuNbBSArTt0KrmzOhE2PLOlXGOaf4zwjTgN6IGMKEm-UPQ0GhzGsVDweWV9w9XlORVdJF421-
QG0FcGWZPqWlVeyefpAd74v6MsAZy-lyZMBIwiEayOfo5A7BuAYSYRfaQxf_lk8Bezoq63xFH3tYo_rfsHutH7ae3CBdcUXUqkubBK52OG0-pqJSmd6vEMKv
V6nX7yrBa5wyy6BulE7Um0gKcxDkhSiE1C1QS6b7v3oVfrSImkSYLC-_MY4EnBKGFiz4GvPIbFP7g5CG51Idt7Q2EB48STu9zMHuas49mfc83HgOQrqydaUg
TK8l39c8ZXiMCdprooHnulkEhmEPPNXNc99p7LlukY882JwwwQGNFhOa0Mq47yQ1EB7zSNmme1Dyk2_rmkpXZPrzoGh0Hvf9Uk5pIp7jPBu1y953k1S-jyHy
WwFyOVZ88Po8JX7Y-KnGt7tmN0CU10h4gSQvvVCbAybyB5RbMfVRo5ruFiRplIcUJoI9g7fnP33Ve_daWDjkoRdgynhwBAccYPhxFIvaURuwlsi-V4hkTys7
5-2ZmkRuw_lcyojXZkRp-Vj2MiYoG4z-N-3taPfG2Ej9taVoznqI8NpVsJ0HmlUfKLr_h54EeTNCdzZgeFSfNcL8sb-xcJ5Q0H7YK-UMx2ylU1CwVKTV-Qcp
qirU5dT9jj-_e0uxpFokRv2DMjnx_Htpsk61tKATlt_TuL6ZHVwC2Ag7TT-_dXdAlexMf2me6B_JYZOz9887-yM_JrY_ylSLZzJ--Ez3_lplMrZ6uAazN_y
}

