sprite $Icon_threathunting_0202_blue [96x96/16z] {
hLcBkgGi3BFSeStxF-v_qHdPCwaUFdUoTrnJ23GLs5OGSrC39hJN5BQlG7A73sjP_fQywekhrv9Y228XfboQua1FstEaVeXHazFFaBljaQiyP5S06AH1xcFK
G_nOzn0jF6ItIcy6nOuon_WWWWm0bfq71cWVc06sq6QyHHG3p7sZ0_ar2jb-HD2uoXu6WEgFw_qW0FNpbRAel5rt9W4lfGVwpratz3LjPkTTVdaBDJw6jfPi
7R3hd8d0ww6XBR1vz7gtrWow_rc1z8p-NiKCQ0gn0MFpSQVI87f2mm6Lg-VrvbsYP-J34Yxfh-Ub4hsFaEADlaCyerJj3T3j8UxfEmwORBU8AV-75EI6tc-s
rkos-o5tnGdh9IpJfvVixT91f2W8MkHoRKUjVxRRUtMgozuElbPsPIIat1JJzPtKAK2SAObsjbwnwwSUKWO0kqWTCUZaHprpqpLJzE1EIOCo_KbLvoETGd6w
C3jRWIZGFfr0fbZbC-PyZSsKmVHRm6nHG7FkjFw30brMwNdauSrZ0BY21gC1hTDlCXi5CC0QlrOMwQllT7BwMX3IGO7yaFxZ2y2jp6rDd43qbBS9IBvfk5YS
eydROTvdciaQVRcfrMt-CK7bUubUWYEn7SE8pjpqDVeyrs1m18glA7vot2FkzBpS9_QvKNH7_Rv8pyjzntGseHcQzar8fRMIJlgqJGIVHppv5SEjCuOTreJe
tUeKWSX5PGx9-UwnrvwBwBS218UeSzZipMu5qEBUgmu0I4oMMOWsU2hta1pJJXsZcxNgCGr3TQB-ai_1I-y6TPeShPsc1iIFcMlEQd6QMBN8shB5TfYtTs9L
YOp-7tk8tua0H7xFRHH_wFSY2f1M-3FnaqUvhYkUr3x_ji9V5_aJyNzFds_ERtIbu465hwvFDx_gz_BBgRu3m_U7-_BVFNymXwm2hQPRV_FAlzlJtc3UsTAa
cqD5d_vSlE-rx8Gij1eLW1g0T5rVqaROYRY-qDAhn-Oy6UocFZ8KmwkF0XHtAIOWtzHtXoix4obpjSoOJqvuEapSXLY1cnEmLKIlOWALSZy0QJhOCWPr_sGs
jCSdLBmVPTTjC3gXai272GpUJtF2yVwYuO25TNMcnYGFcsCnx5YHd_TIRB6LZ3Mc5BpzdOzwI2cvrkJjxmHehgR8Y_Gg-ny_dAC1Gjk91_lhTj2tjpbbEY2O
V-S0NUxPPHpq6HZXS2tXFdSWk2_F0Vl8xouez9t7XRiijDYNpcVYUP0l1-rqbV6pn_NKpJrVYfUtFne_NANlFSsVhgnN-scfxlbOh0h02crv59tpcSy3kAvO
BoaUzr-LRgPE_VCkHETyRdSx_Jn06Fd3jKRS1sjxgMp4eJEc0ybDCRbRagipuBX5J7LeptE74DD_YEAdiG5x4WJphJ7jcV8SaaeEnu6JdpE5nlK40oWtHlW5
-lgRLps735ew520yfmzAz2oHnGVCjAz_SdttbLSJkVuQf0EMraJagz-5RgrFNSNk9epxAzssFb6wVEUzVh_Ctq0zBBDRsHP0zoxzrtd8VLuNFebWBTrCQZDc
NuSSdejH8p58h0EpYZr5F3TTevMIKumfbzB6kxN5xM_nwYXZL29_YfXhLvpGNlCYzxy
}

