sprite $Icon_communications_1702_blue [96x87/16z] {
xTW7igen28PX4jB3k__btkx4TgpXzc-QzL490_yeNw8TXtILx-aufN_Z9yoYSNEqJ1WYqg69InfqqSLxV81sfhZ5w4Rnymi6wkShGFJpun_c__TJylLRy_ND
N7q5zVGRD4_Vm1nz1L0_ls96zVCdhM5kla9Ae5v-nKICwkLFkaXdElaHaaY2wECN45a5skclygm2lUjhFas1B5-IeUJJw2j-w9mdV7kSy_JmMdsIdJdNhuVp
o_MF4wRUUJw-SxuLAF91Cj3Ux9za7zKtTB3qTd-60QPo4JKOOKV_5w1-yE06VttLYn-rmL-bFdfTN8UoQJuqEFQXRPm_bqDdqlVwKCvEDspqrz0FOQs2RVug
ZqxJLQ1D_jef1Q0SLl4UVvKd33234LQ1zlYDAPA-qOUfCsax_5MU2jGrDIkspK-G1qmzclePqYw_mM4Wh741RPTl0FbYSzecNu4PBpSZkiTlq3vuT8jlbgvl
JjlYwmWVRKxTuSSxJ_tE_m_yz_t_Vyj-Ve71yFCd8pl-W099Xji7P1WYmQ2di1iFgOE5mwYzalR1AhCFCiFf5J4S7Yd6jLolwCVHqzTPMVTZAcVfS7rHrl91
qadjKxntzfT-XnbaJoxzCA2BUFbnGXCtNmsAkFaPIEBc5p0LDx_1ZEBbXm4ZY8k_6iVBLuCgRdvssd05LkFu-AjnVFpLE3v-cD0TT_Dg70_V_zB8LFoYcnhd
Cm
}

