sprite $Icon_endpoint_1902_blue [96x79/16z] {
xPS5hYmX401Vuz9r_-D-MIN9C87Dy9LwigEL5YGRMKfYELQMOG7CrpBCzZTilnXPw0yLq2Hh_AP2pGNKhV2BaitFpmXsWR-G7aSUlTvlgQ_ZHBZS7nkdfLpk
pstHqR_E7_7DMsL1VqlRYmL-GdDujJy2nDkXLo3BbNvRKUyKJJ5L2BVpw_m1YlnuEFEJOk_vPBd6RmhwgBTOxwH9wME_IoL7-mh-C884IMwIa4lsCkvtoeqY
FuFl3XQhjwKwSKF3g3z0TiRuYWQbdfGlGQveiCP69OtvxMi3YVI2RpCjyjn-mf2_ujir_no7lbqg0tv3FJZkaV3jyO3V4zjSvDpVFk180_xGHb4mvtwbbUK_
8FvsSPUf-aVysFXnxqqhZ6_xHbL6_0wrpu1qOD_CZrmhONZ-9YlY2cfFtG-jUYCsAdbq_V7AZJAoyqZcJfnOFtqk9RclCMmi9GVPto-M-BS_nGvkLEDwXiGf
PYBAFbexvD7uSy-WlxE_sx_zsx_zCKoGKfWWWh8KTLLd09sXkic2BcpNzj_O_ktVVZd6WPDZflJAD3eJ_IV-umo-0m
}

