sprite $Icon_cybersecurity_1201_blue [96x82/16z] {
xTX5aiGm38LXMsQw_t67NuO2SbS7dDA_jhvLWqgjfwZU2gsd_NrFCvcP2lnAp17txbl5BCClYXcz-sPStmpaYr-EyUD-VZZ6pmFvujEulZt2TuPPXLyCCz-w
WizlVvzwqk--ffxKQXAzfwVKb2Qav-DHRQRw-MrYn9ZOtVTafknRgPNFrsbfqSLB5E77FrIOssy3_A2OUVXXxlV7FCklk_jU_Bd2y7wva1_nUbW_px_kzzss
Bpuzos-x--uCtzBl4ln0p1BylnEXpGMV6oRQJBlxYsji_-Bxm7uhyTTNfBicRd2_dTjUvohmgs6EUBdVolrJVBdVZkhB_LRkjvQOrSadPZUutxu2
}

