sprite $Icon_endpoint_1904_blue [96x79/16z] {
xTS5iYCn34LH2zealVqlT-OpEzLEEQmRffDcA3Xf5ITFw6G9dk9qiZZyy7SNFcyvAvtALyDBNKxXKmEiv5mDA2Vm3IRffStHbliDFRr7XhBO5zZNtxdJMhz3
qvSAobAVu3zUsr9VVivHmr9VKNvEBpgnp-6_HCzbLFfMXz1J2_o20-aAttetj_ujywSxN-Dlmu-EzyCFF_pmmm-_wA2sowzbaExT_sePL37iOyoq7eW_XdAS
ZMffPyr6NVByCVpmmm-_v8bgpHCLm77INCrd0dmcq-a9okc4SVZXXny-_Pq2IdytnJkcymcUZl7fJ-e_
}

