sprite $Icon_mobile_3301_blue [96x129/16z] {
xTfLmYiX38RX19Ty-z_k-TseG2VCiRnrUqQveaGKEnIImdIn2gN4R-K1SICVyLJFwMWLJxNHxm0AAHJmrBY707HIAGF8b_oiupi0zPAVT7m6qCxrpJVV_9Pr
kkohrlzolrtoIr0fslc_rJVVVFFDDzzyyyqtttpppJVVVFFDDz_ykj6d0l4xVN9CU_onyttpcVVvFdS183No1jytV2H9tS_uLdUwViLBqbeNF2T1oV_a9Jjw
BZGy9LxFJtYgCRqN1O2mbi_oSuBTlxsZunS0_S9Cl5FotwpXYEJFpsjyeC0VwrelpSJtJ_-nv6Ftn8j_Uk23Flpxhk2B1yKVz8NVr_JoW0uVVasFn7JTJm2Y
mlbpZc--wpASv5amKPdooxYM3dDD-MqSHU44NtgNf_gOG9xl3_gPRfTc_RhPJq2dZJx5n7lyiNK_R_RRJby0X8r-nbFPysohFWlMYci-ES5IVT4dhbYfBVfF
kLJgR8LN_VNs--QRRtvBjwk7_8aE-7wpJnqpoIy
}

