sprite $Icon_automation_1303_blue [96x101/16z] {
xPZPWZ8x28Gx-mBV-p_ksMRH3DqEUlBVMREgINM02eGS3eG15YCUUn2LK-Yc1mZqRD11jj1dQCS9AkGT_0sEKoXz1tz7B_psn_d7c__D_-PteebAZ_-NF-Rq
C0ltS2m8yvfViabw2aW-7Otq2MXT9t3D3rgML2jym3wWVcJXE9RdPtbGg59d6VmnjyIgQ3XM14LMIlimYr0K61zaxTls1Dq4aRJui8Tmc_00HJ-SbFKkTWFI
QYhtMWWTqFi95klWFe7vpHbXBeCcB4wE4s3w2dXIVaQwGRatqfROhEgkha6CfOhQLw-ZtLbgLzpsd0ICnqqqDi0engXf0nRM37qVhTsnWePjh5QZ5UhnHw1e
-333Xv1Awwtc-Cp1jJkr6Qhm1HtPhL5r5RauMA75gL4ehb21j1p-DIIMeK1mbMuS_D4McIB36G5bEjBZzCRKPY7eltPVxUNEIWzv7AoWneDUf0dj2FDXaHsl
RhymuCFtMQyF2GNwgzdXvjTgQgspyYInlhijEVoewEtf7hIZuTpnIB8xL9DPllmcy6eTVxw_inYbf5-r8uYDs8MWCoGJ96E-SM0qxunmFjQmpLytTpGMPeZU
Ym27EA4PdsPden8SMrSOrY8dVtJK7kF2SBdX1-8nrKxoyszQlz__TQF_hNxKfnzhj5l_yeh-qsKZahVitt3LI96DWEgp-QV3j0OauUnziUd_yGBMHczD_-Mq
VAN7whJE2ErdBQdArHbX3EVLgAqbsTIoPn7qwcYVvRlzxAQMUH74IdtrIJ-EOXplHPZ6EoOCup0cUX45nkCH4rxkNYg6ta8GNtkHT6Qp6PlpaELShVOSmtzT
qb2d9ZegllQhgUbV7526Dm2XZAVxhmhb6G6bNDiJ_MDGnEpnZUYGpTtIFaGOjx_xCI3UxDYE3Fqk3jiXQBZNqMOikZ_HQAw77-52cvTrA8vdWfvrIHOcfaQZ
3G29tbRHz9yHvkNzRL6W3sVgYnDKWMQqUNh_dBwkUXiWsNCxBF5s05cqQUDnFp0A88-K5Jj0DpsfMBrKa9BRQcXLGFj57F9S77-xg-zWrJS06wYgbtKm0ena
0js5cpODLRBYk-OVqRRM01BEPwJ77OJZe1-xw7Ga0o__1kpaV_E_-T_ylakil8c_GRxiJJSWAFHoG_uFHQ3lEecTOnwR40SMsWuF_WO
}

