sprite $Icon_governance_2108_blue [96x109/16z] {
xTW7SkGw34LHWZdWxd-vFpYWYWx2cD9Kz9jectq8WGhi3dyUAGFGKIGydzGMbjNIaxRahW3eWCLBj6UvBrjNWDLpY512QifBPajFTMNM649uyL_-hSCEutPN
R4NDjn_Rt3zDh1FhYiNywr5-L_RATjyxIhyhMsUlVAjdsddhTsKVwFjsbcs7uNV5z_TSdRTIzguS-7OOcxEVvCqATtr_0HalVMZEyll-nO8FwHTTyNodKmfC
MBQS3_cMD02yqi_za1_qV_rVtq-VSi_ty-kVvjSN4VbBVYnZyP8rQdpQBvCjgyg3VbK0Pc-rjZuKGDjJVbg0zXGiiIcW-H6_0be_lNG1_G6_xyxUj2bt_Vvz
7-A29RxlyJ5ybmdpbbz0hogSq6_uKQtwRx8Wd_l3VdfLWPpw6NfmKg6T-kkYDdUGxsTeLuiteZFAyGV81G_b_G3EV1ZVyydMfa4wyHCKXtz9X7hYDuWU_n9b
dFW3TNXdeEClfiVRWPxuQeSTvVAogo17Vd_ZKRdWGu5uwjibklEF-DOViGcizm_qPpB3Fe7nU_hP-dOqR1Fi_EtpiqBS9zZuhP6txWysGVcIJuVtXw3Ci4sm
yTvznFSxn7s2_dKPAnpvYHsKziqMevxvOK8CNXGDXtw2uV4DwftzIRtc4wnmx8j22i4PuFWbN0xGUC6lwor6yVnGGTCLFvnNGtFMxziAai9mD_TC_-tBa2-A
RtXyMAm1uJfPWIPXJrNSaqkW5_yDc0o0KMJ_29YLmdKAP84UlEG9WCxUMnyB02t1om3RPJf9Gm4imzT3X6xxNp-vZQM0ZfQzYkp-w-xopoCmtMs-7__DrOBu
F9zWRlzxCdlL7UhJV8FctcNFas5jNzqvX_mtvlLFbs0k2NvaGTbF9XWtFj_sFvPOq9_o1mptKNVkZo-RBGhj2N_0ag_Nd7xVdyP_DS6uwSk2ASuFp_sabu8i
MF7SptWT6A3vr6_ufqW7sf4V9v23bmBC-7C_gzDRCnPe_Q4lOskztwCXlhyNxszOzk7LzwtulQT-PDZ-pFUBLUDcVn5TV3yjOCIZ9oZQ73yEG7CuIPg0bWjV
EjpPFULbCso-wKvh_5J55c_tOmUOwLJUPsYo-scOVZTI5M0aywKkqnz9MG2hIeIIEpRVOya3W0cAzUlHI5FUCdBuAqbTOPOVbVul
}

