sprite $Icon_differentator_0801_blue [96x96/16z] {
xTe5giH048JXONoMvFx7VJuKuOUcdriNll9LhyHpdExaz99ykWFUIDr-FL-JbZsfLxzcJzgZNv8d-Uhdv4bvcnz--E67tySR_D6z_XJZzvUUWm_-vfzV_CBy
1k_toTCdx_V9qny3lEthJUJfvus2D_oyKV7qDS0DlE6B1GzV1U0DVyFWuQk0lEsdsmCDdluk06_vku0yVNr5Rby5ucq_ZVc6zTiSFshz6NxuuOV_-SUFdtxy
-xd7xsUktZpmEszuqtzC9FBPozVdhX_inFczV-w77txuPOceA_lzCPtdDuwYPwRRNsBi-OzTK4zLqIU_akshuApWwPCtV1I0Xm_Uyb4mmCCV4xp3tmNYxVDx
ulr-wWzIJuQlythaRL-R_6hvAY1F7_pH3nHi_reWtl31brHGGF-nGBpXaqygeAzCyPOFNakoxQS-WBlNF-Lmht_yVfv5uip_O_iIVlZXn_czpxu_vnu
}

