sprite $Icon_email_2401_blue [96x73/16z] {
xTU7hkGm28LXR9FE__wFktsNsv3CYAnQpkrblaGdnfaH6IStvUWYejmObGvmQI-FNW3zm4wmHOgp61p60Ullxslv7LXb1HWY_O9hLDb_l2uo0BeVhoZwju_-
o_VVjQfkR94FlhGJR9HryyaNMO6jPDs8VENBC3XRGJU1B-q0qu9k0bza0VOC6JmuyFqKycc7TnFvmIWakudzS1JotSI-zDme-CAOz4Msn2ZumfxtHJEZi7et
Cxvl5vhe9kFxMIMwoVeo9aR1DwtOJqnCt6BUzr58T9Fp_SuvqKtQzr5Omsw6PFsue_o4k9-xY3xX1RuN_QcR2jyNIWyho_lnAFWbh_DzW_TkIds_GNatbRxV
EG_lfjBt9qy-plM-zDExgVGzAbBW5wJUrtLRbtQJtpRp5wNr_Z30BWDOw_q1x3-XjXfirNupRFZMYXRxEmm_sCLLxCCk7WKjzVK3Sh6N-YlseQw_1Hr7XU_U
v-FL-EVZVntTVkJ2jhSvuTVN0l-0E3M-cM5ly-Vd8l-CXcBEV_pbLl_4sft-W4lRVRwil9XbpXUzU2dxf2_ITSb7v_fvFHN-upz-_pfRaH_c__ZV0G
}

