sprite $Icon_alerts_2501_blue [96x96/16z] {
jPg7alCg38K5mXIZx_qVzxPahl_TTIOYYxwfAJv72DCH3qcFVXh_O-UeAflGDhbbzl9xyM5FiT7gKJIhQgbjdC-2ZDzOf6OFaIFVE1_zyMjB7whtn-FwDdKZ
Vwh-llWw0Ffg6If0I-uiMfC5T5xgBWV0YdZfm5WgSHv0T_vtNi7uKOFfgUTYq6MTDC3aBGquv2EAJO_yL0cZmvaaZ06dnD5YvIiCYKDXIXpPi2HRc9PlliIo
xC6OTtLxo2RApnv0jzPjX_8ZEqdsCR7lhsRP_2uskKZ6sDuJv2_vohA3-uWpj82-9b_Xa-GEt_Z-gW1T7gHNuPkfPs2qDmLehy8tJD_BSwz_HVtovT4R0_zV
njEuGF4_xV-3GhbytC_xVvwFl1ZDex3kth17CTIT0R_yK_dfuZVmopypCndYCLYNbyuKWKCy1kloSa2wqkyqyCjB1gqWuZ9morz0xKnn6YpBoqa_6U8rM9MN
mMaqSHiioal3e8hVO4rU3e0Y2mPByb80L5OCLkH5Btsd0PUyLp_BaW4gRdAqVdH-ukit_lqyujfNXU3-OKRtRw7zywH7ZoyAEMfyLD38yRr2wFnaCAFdLz7p
m-3vRTpy_5gt5D20zSMb6xS-YbxVHQvF-nLrnmBNr_7x0p8WoLOoz3_hOl_-ZAMlfL7PIFa-RJPcshhxCtyOzftPGU-s_3PnGBlTyjj3DkRTjtDRyYrB71EA
n752bJW6zDZeXuIHPcZqQfwEUDeX7r5nLQt1I1-U3nRl-QRA8iLWPlVOmyYhmTCNAchjVBcpUcpvEFDERdNgP-Vx-ZRlr_d-8jbpFy4kzNLIDG0RLM-qwp20
MPDyJkb_t0yf-Y_bg6rC0B2kybkqJsuvcyecjFRpSi7EVZYr_mO
}

