sprite $Icon_surveillance_1001_blue [96x91/16z] {
xPY7pkii44HtAGR3dlT_tBy4wQOugrW6gzwZzjKXPc0OBElGhTFaBj8EG90x2CK0TgFSzj7xfb8mMKoe1bYDZsyWoM9BWPP51erzzRnOqUUFCkXQIz_dGs6J
1UG6mz8FAbrcYKzB3qI82oqzOjGbbdeKRDBIcaHy5B9SG0-MEZJQ5Ki1h0RvIN92pYTi_RZKVOnoBRrEKh4BwNMU26d1KlVffq8k3KkBPvRF1dewlHmcje2N
NkVPwPVIoyVV0lEM-bl0Jwz92hR0Kfy0oRDq2OtzYwL1fZcUy-hConGA-x3KcPTPEiDXPwbFao2ESPPMqbWjlvtpsg0iROlrOmliK6zeYyyjiCD-GrjydlCL
kYvlYnd26Bi2NQVReXDo2RWyWBhLGZUZ3trgsA3hfAN7t-pFvyXWuOAbLkCliqTVIVu0VbjiMNspFy8w6HOdsg9ZzhElH8DqOQaV3rUdhmH_0Byj-cOVBsN1
89zjY_xLmEyhwiIfy_IEfKvVyGRmsw9ljjzN6bJNKlzgSBwlx53Tf_VDFjzNTkZEWlRDFjzNOWNw3qirEx_vqLTqCnuq_RAWVRExgJWyjy1JiO2TIwz1_7bd
hFJNFDpSfMu7Iq-zrOYyApQ8JdfnMEe1jXE5gmJtZlCqkqCwhWvJ-O569pC-qwiTOhn2chZZV5WQ34iVydNYZdFOly6WwXzFEjIBTnnd_uOEx3c6a4hdclnO
55wkZPyFUf9hDFpqqcs7oMwVV_px1ZB5bd-DBpTnl_vV_R_w6cEuJt_4ubtwqU16_GpiAKxf5_0BBHP5T48_Z-Z-Qg0QNMLAlpAm-FsNGQRqDsXHD1kcpj4w
fM-ClXgW-DL0OVO5Qi72A-FXJARqdmgIUQSzfh_Tgbzeicf-AgQlh9aVCSP7ZD_yZTF-IeQUD1HlVTP9VIaCB7p_PPpKbzG1g-haWuK9_O7wfqS4Ixx-FCcW
Rmda9aBZWTn6sW7x5m
}

