sprite $Icon_detection_0503_blue [96x96/16z] {
xPdPWhGg38GDUqZL-p_kMV-jXyWqsjnPboryOnQIo1nhKZssokpXVzN3V_WFNsAfJG5jjIJvC3ih-2Bq4Zv5p_q7ijK2_6S5ITAgt8U7XlzGIVxqlyHg9Adn
hcT8eWGllfADP0_t-DRJUVv49TbaOtw6JYBjpFy4icqzNutiilFyPj0MmvowBDI7228iuOaL_Y6szWU0i5RVn6WBCIXfjNuAsBVMvm2shVK_asbhVsc4RErV
Tiz3aae3sddtIcJy3X9atcN-Ky_-6cN_3a_V0GMabXZCGYnAehYxlpMWkMyGZIZos_zIG8iN310mkPbNlyQtajar8CpuXURzY3ZcJmGT7tNM6RyxUp9DtFvh
pCvYpDpZc1S9yVDVu4GJZ6lkCSQpynMTvJeuQFwmi9wVtyhYUFESxsGFCAiFW9D1Cd6_3AzJPlp2l120H8m99JE-iBifwAiCguKwhvywM5o78Zfvb5Zc_394
h53FYqyT5iSvFmxUoESbI8V5ZM7E3ux9ziAqtm9XhmBjLHn-6BQyBD7T_8_x9n9Ruvjec_EpxpvVM-k3icwjRyQqipuB6NRsbpHhmFb-VspKQN-Ns_qzpoRW
k_D996NdVDNc0wAGySPyECoNW_J6V3lQFv-mr-VpO_3Pp83rxuiw9BzdGBxwVIJ3NlyTvEBtNH-yxoAer_XbY9shHEOh_C0XkBug6TVvOczVG7GYBFFxD6xZ
PSiYNrSkW09eiiJlQvSR0KHudoyEVgvWH7gN7q74ASv_fVOUlv0MZsNfiCtbXtxr-ZE3R3BdIoLPZciI9L7bd2yLzsxGav7KwFEZahHyt58sacX9NlcI6bpw
kgA29A6rf0Z4LAg2_6tOVQK6VX5QEZufIRLr0mdhVWjx_Z_uy1_-mzygrSKDVmC
}

