sprite $Icon_directional_3003_blue [96x105/16z] {
xSsrWKHH5CFGzndTVxaBaHS6D70pgu2Zzb2zrBV2HcciikF7Zny_VlpuyUF7ZxzkbVwsIcETFqhILETF3_hnuyUF7pz-_6dhYTzlqtF-gRE_x_UdpkVyHHxy
zyrh0JuRs3UljG4V3EmZtZuPsAUyVJAmJtdxU63VFF3fmBvvuiE1VVF8PmFxvfcF1lRDGvyDx9jdFXpODuzyFlZspLEV3xvzyzJdWs_VFFLPgtJEqcmU-tmW
cUS-7qZciSy7valyjabRA_JRPhx01yMF7pz-_FZnuyTVfx9MbNSMyvy
}

