sprite $Icon_payments_0705_blue [96x96/16z] {
xTe34WD148NX7ll-nusDKMs7xoz6NzREfPAbZcnDgFB5zVYkr7FwQTILVfhR-fhOql29uCE73ny-VFZmGvektFlMtRytdxx1d7qqJYbEbSv-VPefcaejuyEt
QhX-tvQP0hCVXwQF7axyq_8J_72AUVwcRjzC-UvxvYzy-F15J9UPARz_CvKP_1YEPHPVqB7mbRwInoA3ppn_pRKVb_P9cyl4d8_j3_Vv4VVv7TVvAQuFm8SF
7pvyZk33Xy__V0ZtyotSp-Ui0G
}

