sprite $Icon_governance_2106_blue [96x109/16z] {
xTY7SkKi38PXcW4XlVT_kN_Dn7EK8WTxf-RRld4UOS7uWDFrv4C0aoEdvrE7yXuTzKaxjsa0c802WCsMRv2-Au3EbWeSvwsisxTnKhsabFxp__kpo_jjtElA
EQEdVtxvhFt3bBxEhlmNx_khzhlY_FWkuwxupdhVZsTTMxUb-mjZ_rnbmMtKuUOhy7tSkdNbNLSs_FCsd5FEkkV0Dto_RkM_FWmt_NVySyGB02HFVpVxlk-K
0GlKJUU-xrC581hwlf_QW_wl_-l7cIi_xVly-hlvzVC_-KD-EKG1GAMNf_rZyHBj-K6_6m1hZjx750EmyPHV5B1PazjnM7l4xu3rvD8Kc0_uyokd6wnyrv-k
3wvlck_v4xIahx9WtV8FiEz6k63Uy8jX9NqNXRRlIpZxnR2ywpUOAKY7iUihVcpPQC55r_q6m_4ALeAhBli2sVE0Bw3edW_ooY_ufC20kkDNEFnYNo2-G86-
umyedgzm35_0a1rVCC__lp_q1GJRyPNb-VzzNs30Zc-8uzzyNw13tlAduzzyN-20Si-V8A_xym5wsvUpm-Bt_uDrip_h5599taydEVVcTsBNpY-2xlWToYNV
aFtdG-pNpUT3CjOLVq3PyYUK2xxjFfyhpDW_eE_vQK49VSNIfbz18dz0lxC_wT_x5JHj-zdyPr-VmGNUzmFo5toxWSlgDWykH-Id3bQ_uoNuRZy0d_7r2Ae5
V9gWhFZu8lcJmGyYFYag41ro31ZPbpMW1wTbc4Ty0Ci284Tshu2rHeTQQ1bcYj8M0BRc75CK03jI586tNMQOAWQSaLXF1UQv_mtJXgW19gFbT24JYjl0FvaC
ostWTn8VhXJAyto5vVxsLFoe9_Id-G4ZVChkfu6-_ElPDUGFvltg52pDAKvMEFnYaXllj-FN4WhpALz0me-wVLy-RNOs64_u0fe_dtFcVN-zyBw0tFIpmih1
5_VzOdZ15z2oxpUY3WXOs_K7yHAPmDZoom9QYd80g_pSRtRsDdpTRFs7VXRN-gX7ad_YDuitBFxo7lXkyBwdyPPDopN_E4SJn7qJCyT-LK3ArYSeDWA_260j
xQGktAnvFq-uitjg2kZX_LFVQutVvcl_n2yJODKjrbUmaL_zAaxVJ-u68FNTprsTVZE70cZF1OusUQltO9e0iC0u-_LayZ3U8YtzaTHfi8uV3Vrl
}

