sprite $Icon_innovation_2902_blue [96x120/16z] {
jPe7Wkkg3eQVw2txt-uxAUR3mJOctD4fuwhsIm9ByxzRP5n8vL6ffE0CTzT8-_GufEJrCdFbIykovBm_zsg5kyqRd-YjbksoQElZ9YUPLUxHgKFJtCTlsVx2
tRmLJ5REdn6Nt-PDsw3UkWKrV32yrPZ3mR-ve_fOWhlFNTASIYg-dfS9pn-vL1bhdRFMgFwL_7pbNZgubsk-OoNkuZvtCHNnqTZrnUuIEC2xeH9qPxM_O8mU
kTNDmJod56DAcGksjJ5ZznNx5YZPoaFoHhL8R3MfEAxAKq2yP1-Uh3YrvRm4Y4rTRgM11RugG8uLVnntM9UmB5rYO7VQM-o7EWdL10JOipHv8YOWCSnWZ0mx
34uIyz-j8Zn7mepJ4RFbtra-3HrDhDr9U4pWOTDXp7M74XrEmwIH9aWE0gvWfEJxxE6P6epBuHDg40Gt8rljjEklXQbgth-4hb04TJii8yFmADyS59W8G4oH
DE5jgm5Obz6ZS6-2L6DttXiW06e6s0uM9eq1qjn1_VoJTtWN1DpkXkiyDqyQ0_nROwvBvxWP8d4I7jUWkrqsgBzeG6foh5H88rdu4wLgliL1ghf7I8D98ZSB
3X94DRUNg5G5S-iKtnmjKQWEuWYP7Aqxo5IlF6EcmlypPzokAgeSRCBJ6dlSZjeOuack5G1ybMG-nIVMw7Mh_E4MFznybRWEBzx0aW1_QiPAYIXu6pj0P8M8
5ZoLMiJb3_dBEd-O4Etuvx_YZ_v_xV-_ZXz-ajihXDVHszKhw-KPhn0tPhE8UmiKk_e38aXQMy285WuetklX3z30oj4gl3WxrK2AzIWjkpy0nBVRzL86isq3
2DpEjdI1NASgUpcsfKkhBvnIBrKUImYRpXDuZG-P9VNZ4P9iInK6BAaVF-xXXbG3YloUkn6FcFqTp-TZ-8rzG7t_LMaSMhjVFQJvmXRGRGm0ZDaFL1eplVfe
hPe7vo78g2LOic-VW7RwfJrWEIvzR77VpGk8z4Uw94Mej6rAcMGVyKMd7NqD16GrrM-FpRavwqvw1DoVIkW2-q5-a7Hkt9ua66-cPDu4C0MmG-Np_U65AblF
aob6DkF9HTRC2UHI6GJGcizMpXwFZxrlr6Y3O_PTMucV2PYHNlNFR2hfFT1c8817SC3JYc2rsayTS1-83PSdnXpz198faThi-fxRN1TVvvuWTybhGYF2rsJS
iCILHOSh1DphRPKFSalPRG2iFoaglTbPKJfxObK8P-Cr4TK1JHn4-PJ-esVgBUOk_axs0hQhIW8VnAf0s9HUmdW8uyuC09fcF1lqQ7XU7jIHu-RpqSw74CzC
0ezI33lxfVQuWzudKGcM5mYexQwJVXTtgJvaKpFIzCvQOwnrFcRoxU0bjfjGGlrk17vAsSbb7nhI5vL9JCW7l8EHYoAc3ph7LwIC2p6bd5EAmHarx4CF92uH
tkWXNwS-6CTT_x1VwYM4OHTba78GFS3ZyujYGCR9M9q9W_TrkineSs_EmNTGNxArypBAxTu0yOu8f4vpn5g8RaJ3LOwoemocNqqmNcpSQjOej_kCsTwCLWWQ
a7ZzEWzahdERgyY3abD4pKjzLQjOILPeWdIQzbRXdYXiDBBNRmFKy-Hr5V_HnC7JrpdA30eHvQdoQw559C6h1w5EL7Nz0Eqfjn6NxNthHxbDOFITAS04SeXv
9wlfcG6kdM121AFn-lXDDL0V0tYXtrsO_YBgN6_7o4mC7XFkXCC98Ht0naGu3BirvEZKyaSuWs1Fe3ytjoGTZni9HtMQX9zfTOsQPUobvWTRhrVOSrqQaERw
ubGNAjYreLEx3mo_rwL9VDJDaF2nDGpbdxhMz5m652_i78Rsa4YIIP9oDwR3LOx_7m
}

