sprite $Icon_time_2802_blue [96x96/16z] {
xPfLjkGu40Mlc3Bslzn1DVlKarpMOCU_8wd00YtWK-d3O6AZbUZq33vtBh6MtDloQbFMQyanX1XZogKD_gHdh_ka0K2_QePFCtIFkaSnW9RSHwsph7so0QCu
lSOLknCX6j23LaWTiAHrN0D6r2gX0ztl96zHEyG1P2rHWEgqILaimVMP_2v-h3pe1tIdM-IFU-GDgkuI3Df7-goxpEhFw2VjHG0tflxT04wNzAa_L461gWUe
rqEEqBM4I-wZ2igF3ndcj4JxgCu1wI9eq1gTffSum_mFtQbwogy0_OU8Uiwl_Dq82iGd_UeGlac_wL6_CyOtwOTd_SgGDjBVzcjWxalw_d5_-39Ye-jnlnhc
PYJI0R-7eXb81_pgqslK8_u0MLA4SCIlmP1KC9tnP_3Ie1_oEoXoa8_uvuGZ-5F-13w3JlaTvCeuvjUWTTevVy6CSiuV0V8vltg7TCO_WNZO7_IAd_xuB_Sd
xJ4s_KKxX05rAvkwlJNXjKwZx-tQMDOE1TlQnQXEMoHmMi5te0TjujS-eAu2bhJFqXz0Cg3e3fs-yfcaUTsYV3G0tu0HjC_IwtC1BEi-BrSlqJO-aziDSbix
W_iDYZ2YtkFb6sx9UfyCGISncavImEiWZiC5rCCJS4RNIJ94dMHWJWU9d1znEjqXhuC46ExmPwZhBhb-YxyUGTKzFD_HT467edlK_XM3wqwu0KLlKvZ-Cm4o
sFHV1gZlw_lqNmVexaszd_uhN8VXTPS6vb-_4zQD5zchv9nU-vM1vhHFCcWBxxJ1xfJW6b3MtfahCE9syXQrvbSOUs-6SSocBlgbR42BQ_O-wztmpxFxaPrU
ux8nvxNbdn6WlmZXKWUmxBJl_tB7OjJaVtJ7EgxlM3IQLl5bVBdMabAC8SIKI-i60ADSHCvE6_ZSZ2kiPQzdyAcqOS1aj99MtBy2
}

