sprite $Icon_cybersecurity_1202_blue [96x96/16z] {
jPg7ZWCj30PjEiRp_e_xbzNcWb0kR5QvKRj21lWWXXIvWgRQpFd1hHMLxw2v3Lumv1jaUmfxQ_K_MZS7J4Iq9f7xXEO0U2zHbtyTuWPoczW162NARpHG4Gbw
msu0NeE8RFm9weSzQ0COMKJs_WnuaG_83emaSialnO4Hv2BQ0SyYL_sY5Q1UJDw1fdBLVn0CC9Kz1V0eSjK_PNhbSMqPnsM_X07iKkr04RdZ5-dRHJ3m97Vz
Ke6wqKUvxvVyjeCE7kIk_o2zoRTjzNk_PE1rmcKVpjv_Q7YbYKl7T_rImLLMrA78D_pImMJ5eCjT_twe6Lo_v9V8AbE7AD_oImLR6pRvdby6v7L2N_GVGdbY
aEMRVkbGvjw6VDSVmEVEqfVzqg0y-nhoRRy-fGtoj_rpA8xBz_qHxF7KhN_Wbt7-qo3yXRz0cHRYwtu5E-AX_8bV3FHe4__6No2935p-nX-XYMxEbLfl-yKP
ajx7dy1k-msaley_0tRJVxWxwCQFtVHdo0ENdH-xvuzGdR7nLmUxvLVeq3V-71piZb_0eEty4XpY7RyphlWb3DCx_e53tVeFxlWDX_A7_ktuqrj__uQ_l2y0
6_zcVGEqzmLikxvTtk7uhSuF70EJDxmzVkhkNWQscs9wCqRVnA_GTaia3k7Nyw_jnbRQxdQIVqjGVTwTkHtKelC0I6MNeGoesxyR3rpdjGjfUtiBhv_Z7SOq
oITrRY829kz9m1gq6lD8AwHmCEkYPH43sL1Otuqhovj9prCSRB-9Lv83blKCh3emL2xv8rJP4Go0ORsRFrFMqj8lVirfgW1xeZ7HzN2CCxWu9hzNFGFKnovA
SW4jvW2ZFvft3gm3g1mCmCi0O3m2wd8LrJbPF3pw28y6rJce1laC29KR33YpyRoKH7gGy4YeRbPuLpXoMRTRYqS_frSTbu_HfV1fRhqLVTMYGf5FgT0cLvjt
raavLrR1RwJl-jGF7dYOso1JKXzXK7KIUGaQiZDrgmPBbjV9FFTD1JkjquMs0huvHBOVGkYPxpoLSFvx2ijkBB4seApl09o_AE1FPUJDFM5tUwnpkde6j5JO
0gut_4dMQoZOgq9jqE_vNuz_rQb_l4c3_UHVNkG_T3reA9ykB-cN_QC0LTTpF5yVl0CZdi_FUV_RyqprkCHvVGPzAiiwmBEAvW6kyoLWhLdKw_LdcGm77cMf
3nC5Q9V7dpRrKyRgbtpvuw_rJTbGclKITbVNjFyORdqBM3-wUeTnSH7ENQcTiOodZJoVG2iDy7pn1Ai0j32bCe0Hp_FzryhRW-nmSC2PTaKSSD3Vb6JjNEaX
0dWznlD8UW0zsUuh36a0zCr29nljYA1FVW_7utVrk3Z0g44kK6U_78Ge6_80m6gyuRz4wd1WBSTfjY6LDcXR_nxDnW_kmsmCvs0M5HZMUwlL6V8XgGvWnIsz
h6zKkK58jPaD_vzXhQHbsQCv1-iX-oy
}

