sprite $Icon_security_2206_blue [96x119/16z] {
xTTLWYGn30DGXofatV-uoruQKjALHUjhA4yfkuU4JAv3yIKwQWvoOyh0auno4nwgshLRgxMrOU_NS8UEZva_J2JaEl4nxT66eW2q9NcIr1I0beSktv-CuSdW
UjZcutpZV6W0D6toMG7DpDViyG16U7E40y1EGGBGXKZRAeWADA7ITdOmxVPaGLZZEp24ph2lPbFMRXGKABBozOihIsltQRRRCoU2tMRjYQEGgK2LnLmB3w1h
rxT380-LrUlRGnVwrHpN_GWCThjJDZB90MKRpw41LI3l-0bevFXbA-HS5NFFdr1klMFFxzI2eurnPy69MbFTzZFryhps_8lo8r1E-fAB7FJtuxxxxjyPzztl
Uby0_JaTnwFphkZFb090bMEfxd-9--wxx_vr7VKpa4_w1IZ_WU----wxx_v0USql68_v-14iJzv5UCY_01EV-iLER_fMS3tnETvyhi1ydZUVAp2Vvytd2ymt
dlFf0lED9tssm7pZMPyiCDzuscSBp3UUzVc2ZxxnlCyNVFIDvts-e0FDZjpgMm7in05Vgl5d_FDVBmteSj2NMl-H_q_TTzzzzzqVzLW6ZaSFy-y1
}

