sprite $Icon_security_2205_blue [96x119/16z] {
xTBPkjmW30DW621irli_RfTyLVVs239d7Ui-lx2Te2NcEWpVOgFc6EwOCl17HhaJ7glnsQtLsXe7iHhleBTJcpM7dvBhF1lQrOPY9vF27qddM7PfIx5p3VzU
NDyV8Hc05l-tF02MDlbiWEMdds1vZmSmdXm-3W1va-z1I5ikuE0jI6aRDuZ6rui5SStlm0Xo1X-Zfl15-hHbSJjB6qrhxscyxVDy4VcQjOdZmcDgMConC831
md9Cdha0TTslyYyqWBJktu2XNdU6ZKpnmfdhMLzG5l-UjECde8dh3riHzsgOU_w4QUVjUtu7ehh6pGCdoQ_FwMVWsFCF8B-8xxxxxhlllllTVWzWMfGlEvuz
Dd-DsToC_K41G0tFblenVFVTTzzzzwDPV4w_0EK1VFVTTzzzzzFnV_z8rtp3ZF_n1-ogpuA_-GDN_HiBVlV9tmHVAw2ly_Ir0lewJryheA_pzFK2-kGrNowW
JrxqrGBwv5LVBQ1FNlNbWjCdh_jwmUcJbtsvO1JW8A_xUe41axpkwmLdoCk-Na3-6NmMa7yEFoIp52xuUjnttttttH_rsJBmxB5dvZy3
}

