sprite $Icon_graphs_2304_blue [96x77/16z] {
xTW7hgmm38LXEuKq__jVxgkH1cur8_8gH-MMC1-aEMZCP6b0_nN_zZNc59RviG4myXf_0p20jiBVO6JzsOj-lH-XFUwqNUutXiXCnQxs5VB-ZtIn7mzEfrpi
9pWCLltBddyE-GpaYttfkqLVGA_s4zJzhrVxKg574T42Gw_tPG3M1vE_sezW05XPKZy7Gs8kMrfJ_ml4XUTNW2eB_O69qrTzwd19BZzK0yRsnEXu_CACnNF5
mTJZDnWvXbI1wESp977u6Uhii67gvTLeul3trmMZUFs6gSVF-xuKp3ywMJn-fH_AIVZPaHuTe-Fn6_Lm8CLPp6d1EphdVKdZS8UurP9tO88iFhymzf-R3VCE
zSTVsG2WwMDqkZZz2EcjytIoLQK2etLxxByAmUDFqy8x1MKpiCuSg6ppoWYRkFq8zaFL2aqEqM8ygaoOYoRJnUytW55BCzxud8xT_EGv_L7zVe7IsP-XnnnM
YdT_WnwgJoojrQnl5k7zL5RQEJyQtVsAUTxNOyNyzFaRzPJVFw_u-o5N8v_nAvzVNtSzhA0d_0p5SuwCYMvGnEz7wBvtPDk2QEhGnUtF1tCa6JDDJlW32-AA
LWFeIKxu5PAu4s9KyGSARB8iSp1N-aEM-XRM-kd-_ktsJ-RsRt_hkvRphP_wymtasTPB_Dk__QXlnzXqvlbMOMtC5ljV0G
}

