sprite $Icon_alerts_2506_blue [96x85/16z] {
jPa7TiGW44CDDiM0xd_SzCQs_yZCAht9xQCHBzk2KfEaTcnFKMZwqlaK_owr56Dw_xZvgqhvyxCY5NVxADNlpqyfUlitZV3zUHZkT-YGqlQZB3b3DDJdPzrT
xOkqNrnEzaH_N39_QWIxxmJCDKvUscy0NwJeoEOsoPVH9AKRttLZT3fJODJ4vgpTXz4mvR4_ewSKxXwvkh09TywahW5FtihcmUJQsUILPsUJdmvhDSNgGWmX
uPpShDKfaWsCGi9OOcYUuZpvMP3mq5n05ZGYCSfiUZ7Abvqpt4WRcr6A0C82c-2FZ0ARu0yNoyiU_25840dm1zWOQV27EeTiWZynof72_Zn8cKtsPqOXqi4V
wXom2Vx0A6mcm1_g75G2y8Uo0PK6_AaiGIK3V_XRtEYIFryxt4FmXroXpGJuKoxIPeByQUqGc-IFQnys4-pFsGKP2FwKlR0-o9zd1x39_iGep53sPqOvNzaV
HYLq6FBdxhG-tr9QcAzmKEE-Yc-QVLzetsS2YglzReSLCjMvzJrKcF8L64KscK-8Cc0J_9dHTJOxdCXKvv1DEwDsDg7EmT07KHK1DcqQQZ3GI5m5WKqILza4
Gn64Z7PWqyXejyK-3m9WtvpJSFlD3s30uh8kiMfSNTIcezJ3y_vX7BSaZNB4PONPArvgB-CpefF-fPdheLlAdnJLOVKFDnn6VIV_5G
}

