sprite $Icon_governance_2104_blue [96x109/16z] {
xPe7rjj838CrlH7tF-uMlLqvIf10ekMjcLT-Dtt30Kc8ZhDTNw5q0p1ht9vVgIqSQxNqA3plWGCsIXb_FEpv6NOe0sTYQWRW4QLYdKGH_hfVbLa2ELVkMYcj
okfP9bqhvRyib2a3uSSUH1LzYJSO_v7zOkhW_AfefHogU9GgMXL_LwQjYHPvhpd71fXgSRzI8sr0sJwvWFmFvV_a_-Jdz55-0cxoYwrq8_oR_BG0O8JFyCC0
O03GFi6l1g27kEzIdkRd1M2cGwMPdkJ72S3oAyia3Nv-w02iVVDAVO_Fe-KdylCFjNb6udlySxNmYdg3tqYrapGu-Tc80aIzbGJVSQa8Gl35qPM8cjz4waIj
AluGmjDQhTVvyzHHUgKf-LfJMQQ2hnjBj9dWSqU-QDoU_YgYY8JDARvkWj0EunPy4PymRidN_I-CM_9rVOZwSl1JIzzBGyDhpzo2vlFaphENSiq0QvBFLQai
bxiPh7moAyk2pxk6M0OHYtnOyFiU8QrLsdFL24ZuPwEdseNdescJVDrMrVYh0BhKHsigFwhvsjrOesLHdzvRV20t8i4NQL0Ef_bwo2HThVZQtRXynU5l8Wra
NoT_l_faE5Gtf_vnefyDa-Tz7Xcc_F83MIOp_D3EWjbt3Re0GDLfFIp6ogacLHNNFIZrfUXSZgTtJja8R0fSc8I_05H-A5wJdGOwOHsW1-FE41etWyOB1HZb
fa67S7s4IK09GB_h32mj_2w8i4rOaCxW6Y73NjyPQ1w3rZ5KxD8lMD1dTsXeMDl63w1pf-yEzSyINm2vdZZ3BV4Yi8uocZg5vURTUG3vLKVrGWccEzD50SOH
e07fqhy1NPxDetrPDHcaXkYWSFMxwphRGcCfuEL2HWOgVllwXN5jK3jdWg_-JRXX4HzYxKg4fxOVljRNYAOi3It885Ws-GPyQNpa9QKbqgi1nlCJJIPPhyxn
Hv9NU8SUvaaSje4bFpwQ2d00A5vylY1m0p3SqgDT2c8bXpQBjXxF4PgZwh7YnH9cdzNUr-_zJjJk1M_vNgwkNv6MdfFuHIDU_TKgktnAXnMQmUkBSK2FRsf8
rI9P_I5zAMdqt60rS3hfAESEBHBTXNYNTrW0CB_G8GqGkd_bYTSXGjttMsLxSAME7LhhlXL6UfB-2djVriBsYHMRtVw_Dhy2
}

