sprite $Icon_time_2804_blue [96x92/16z] {
xPhPakiw24KrM3Fh_p_t3brnLu937OUZVklzdeMqGHDE-4092J-f0-8Mq2y_bpRc4ba_m4zr2gTsyrDxiDS4fEpbvm70g3ca1JDkzJzFW75ypKEWRSrlce3K
HoY1ihL-Eh1A-CPBtbcVUPt9zEF3OPPR1Vftx6JXvn-YzXhUQe0SuLHSy9xZcrQShvKuZDGwVOiB-gjNBGH701jVdn4mGjWNOBxYmq9Ys1TWA7o3CzDsW7GR
tvJPoN376U3GkF7jZgtCtG1HMEgdBsxP0SfTyvDAjeGRolMkEzKOs1OjbfwFRCHNlSr4g1lveakn_Utz9QhX9nsmkz6vJG6GKQCn_0pPEUugVEkHrED2Qzxi
5k5huEKefSt7i0TBbvFFdZY1eMT-hPK8XmEV16QwpkcItGBHXTS3DUpfB8SvWhoTjT1ss3yDKzEr5ZrxJxLMV04ZueVkJElSMXiUDmsIvTimPkJRmRGMxMAb
EEwRbgLG3CVkoDvGxBNQcPyNPxVv-S8VdzjVWv9TZECzFwOdcIRu-SAJgc727NxVoRVzz_kpltxi_0QellhNzRbt_Tu-i8Un_spO7mmtCgGz-vi-RFt7UpN7
bAuqeMuuN-ppTp8sd8_sRQ6nVEUxbVkqeViNnGg0DYX2sNU_2WCn4h3bVXZoPM8LyTzlhoOjvgLcoz_SpzlB_JmKo3hY23xfzyMNX6ajH__xQ8qQpsdf34He
6zvtzlkt8p7iKzRZJSO4lEewnMFl1A8eNeBkwc_O3aqze-JepvYgCFIExkWlsUhAaGBLqH-pDLI00Tc1jpMXgvwP4sy7657r_7nuswALLCzoL_ls959LWzl6
EtIy7aBB273YdOTGYqyzx-B-lc0VGd96Y0BLzNt4Lkm0FQkF0Xk_VwK1i6fw19ZHnxSLsza4p760P2_VrZ64Bmb0y_Dj7Mrk_twgbOxQnfZzz_luFltoz_y_
v5y
}

