sprite $Icon_threathunting_0201_blue [96x90/16z] {
hLc9ikGW25m5J-Z__zmzPlBsOOAZsKtNbIfDYms2nuyrADKk-0lf9T6FXn1pLpZGdkD_auSi1rihcPc8c5EkNoDA3l_3JktDKlX24xYyH-x_B1Ht0EXfQc98
xnxyJxPt05eM4iUY08Hkwru1QDxfcXL03VUaKSE-H590qmtwkhQ8QsyvsDdMxO0NGEcpV1s0xKK2IDpMfWMNDT9lnDzj7P3M0VscR83oZfW0ihE8coY-e43v
OmdGnX_JEXeSRQWgJj1NGm5iDmNosdeTPGpbJIwj9AOOYRZeOJS1yUIulAANS6NNEYO8EOA5WJZqbiyIqTdwh00QN-DNN-FrGwTX09u7fexq901QT3e2me4w
aAyKc8Qf06J5ccV7Z3VwQp9bTBBCLwqLhtrQz2m0jBn5GXkjQlulGqFeYmKPcKpFu9ff4TJs2d8ZeTHn0846jnCDzCMnEH9HzDnX1o1F8HhiTIA3g-20r1Hc
0rXJBRgTL3jRJqqneeqC1UY3r5VdPcjDlPHAQCkl_C2vwhMmLqkG0BwORwMIIwaiT2sxBSmMZvmde4ZM__5KRNBmYoADyJUVG6IhJjggDXL3psGLKlHPwLFq
HT6mOsS_HF8q3HNRmfyhSHGxUZHX4O0oCxzv2TL76BnQWV0z6LcRR__s4TM84etHFFdLcfzyxUTPqKQvBn3Pm8hzr8LIkHmiYlc3pNTt8wX2vrjInGjQupXZ
CT_LZ6iwsGu-ofjR0OnJJm0xvf7dW3Wjpmr0VRLH1T23jQbxNWMobyZ3ZBv7MzlwCBFWa0gg8x_CwdaR-w7OIIU7j3aEbhyqgHHsSeOfGD7-vHXOd53Hmwoa
m_QxNh9909eNT1amVZzh7OwPfgz8eSkYivmE4u-VVlW4XT0hFOfPTFE5I43yy1d2AMOJG2RQZ2K6GAK32SZkPwBV2AfX7B90JBGPKIsm2mNepA_FyhElJ_gi
JubV8Fx-fFDd0FZYNztmx-wX7KYd-6GSMCJdBdy-hozMs6k5ugslkablSqR_QoXtw7J3P_F36XtTIHyCq2A_RQ90lPoXg9Fy74r-NiEIslhIeAVwqlXtly0L
TZPh4C2EqGJayr7rm5oSuEz9YXTs7HgSWpoqXdcea5lyn1YTvkSSIZadXy7PdyoghXZFLTDz2USyxnNG391_4bWZpXnZZRQvW71hW7R9WyvklTW9i1tWllbs
j-xdWWHesbS_J6UcbZBRa5XVRjh_V91jwm2P9jcx2eqAsOkig8lpgS5kHkNJyRZDpjTpXP6tdLE1wbtK0pCN5g2jWgjjtMz4Fy2dulkN7kBs3qHnOhsiOYoe
dNkm_jo_NrgV1EyZo8hUNh7iWKhDXr99LtRvn-drxNmxIl5sgOyAfJqx801wh7SUN_nypEXyYPPoBEkzr6798F72PkwtRRKmxphRIBX8bEMuD2o9x7xLdall
3-2_Bx3bpy1jUdifPH5J5GNeqCVeT1iqlt4BRxjVxQ4TyxYDA8kWwm0Kk6--ZPaMFgvqvq7jmVV1c4gouzz7kRDs7dkVVNu4z8KGZx-FMppuljzhJipq_40n
DmNi_k5vK2hjcCXz_by
}

