sprite $Icon_internet_1502_blue [96x92/16z] {
xTf5eiCm34NHo2Y3zh_S3sLK6wPt9o7xbBco-hmTBV_lssQqx8vy-C4T5XJiQKc3-axai0nI3aiM7jJt8eSp7AKUjhFaeVt3CbxE_x1-m_wm87R7WsmtV_-4
3p_py8MBFrBswfSHOjn_7e8F7pvy-8wLudbqp2-AN_WaQbKTHL-SVwvQyU9dVYZh_lSTVVUupstTXmyVlcSjf_lzdpzxdtykMX7tdntxyE6JrwBUVXMjSl7h
Kz_vHVLpx_UV3MbfxxAZsyBd2_ZmuSE73t_q_oUilby
}

