sprite $Icon_endpoint_1905_blue [96x79/16z] {
xTY5qgmm38RXfbJIDk_zN-wnNo1hCnIEyutj8ayTg_pKA3yzY_oqB00n_BJ4N-fV_kMB_2nVaWu3iA59plQNXajRplHZ1nYQqxAah0EWnzFy2emYcxug1jHp
VEbWETma6tGvmPS1xG4a3OPC-fulwp-pbImmvAZV8MzES8Tdw0VzwdZdlxMW7l8ZQ5YJ6hGKrZI8H_oE-H45DzfYz0F-0jaDnO31biompFkDuQWQ8VeX6RHf
N-wa2D6NMa1c_UpEXVpcP_1rcFMLxg3qvaS8QmOwwmytkutwveSbkXKoPdtVTCNYc--IOT8NIDk_XjNxmnF8jByuoG2iUcuvpG-n0J3YQNwwNz0DXfpIFy78
zoV4X9jM1PkVd-eUVTxye6v6AcFMzwSQykQdizPNSZiXFV0Zf5a_67NxHn_qJyN2jA_OLYBTZw-Xytw4uXzKeE6hJvptGyDaFNe0Vds9qSAiVtz_hGD6yVTd
EUA73Fhy-KGX7to-Qb2V-HNqyFDdTqXhhlRzXEVdxaRKZRRZd_bQdoIjzQHAS97AsgxqJ51U9cvlBBgiUbB0qhQMppEUfVdQGjUISz4ElaNjAU7w_rMa3bUd
AgU__yQitRwbQux_n_U1ox_yowzbHrJBZbH-TYmDsnEmFHbfTuV6y1CJB__oB__ovN4I97cSNRonExQdzZE-FAI-0W
}

