sprite $Icon_innovation_2904_blue [96x96/16z] {
hTY7Tkii40HWOAaBy_wF-vTeNSPSSSmDSqgQ_Csgn49sR-cuI__vkyTsnhklvtsy-xu3BVmfja44aCFtIPTF1SKj8i0GztM4_CC5x9ylOFzy0Vld2zW_Ny3-
-GBspnUmVxw0_VC5x9ylO7-_O731sZzViFQj8Bj58Z32biz9WBfL6f0tVHvllVy5w7x3FykRVvvd_ppF_dcU_VCy--Tvzi_px9_dsJ_Fit-UP_yyp_vvdltp
FFjRVCMQzpbC_ac-6q3-ITu8ya_oZH41pfnQuwlTzCa_oJik4E3WmIb4aJ-mvkDNFCrAlgvv5uP-SN2umFm3CPuBp3_Cy-9NWACy5ony7qGa-6sU2_xiIz61
AqDBtEEvOFQb3d16bNtU2ZBOZsfJ9v4WacnFDExnXW4WFpGRTzwX5dPuYx2V08pivkG18EtmblZkDm3b_iqDRPEt0cVRAj23kqleWFeDtkBzQriUK3xEGmEw
t-0vEctRqUSRm1RFmzNvrAIfeFqTd-Qprm7qQOfNfMxmVanK11I8SscmRyUAd-SAq_aOynbmuRMV8Nv5z-wS06KUFxiqxq2PVhME0DUi7FlLVDZSWExwCZ_a
sw_IF6q6PDElT-FpjDldrNnxnJJ-pRGLOyyNChoaKiVJ61Yr9F7yYYs_0DUtgRGEItuURajl9ObLbYrVeVO_O1czvTVvR7t0Scseq8Md-TCVAEP3tuy57RDS
5UONZ7j-09bz0CdU_r6_MTycm2zu8BF_lCOLQ2jUBpO2uPvF7SZiGnmLh7Y-W6O-ygUExBjsLz3mEgc1VUPvfSw-EMkUvvzvAZ0_ihJc-VZFF1VOzRCiuAF6
ry_CSu5T_wpnoptpVFqppmNcAm-S0SVv642XAvuB1FW06xhZACyFb1NF1G88_x6ZBj-H8o0hdWlcztyWpxSiJsrBdWli_lLwVNXk75kY2vxkNmkU2fhTVwUh
JnH0ZtO19Rh_hdakWAqV-EeBYYig7nVGW2xvkO3NFmtgVBqUD98zkEZBB83C_BBW1uKyvsi5m2Yl1vVQC7ZzjkQveDFwq-CdrJlxkU0dzdF7y1E_ituMW9_b
heC5eVNp1c-fG3LVnN52CzysskHvEHzPDoeQhpiyfmFDEyxg-MkBjpteD3n5FfyVTUpmjlye_lxvjxfV9WrWvBd1vm6Cv7uTtm2WyOx7Dh0uDtiH1G1epL54
OYxsixXJaRBu_ETC9BzzVfL_Y_yB
}

