sprite $Icon_automation_1305_blue [96x96/16z] {
xLhPelCi21HNLERz7_TVOazeBKcENUxEN7sB8J2CWB7k4oXWzoOen5nuGyanpFP1xdM4N0KJUir15m39lOYajaNwVn3zUurkeAEvLn0hDdJEmIjNFcRkunKS
RWJv5rplmqGqoQN80W0zEUU1x1QHHVqxGk1jKN8DVT5t6QvTWNBV-5iZo5S0FQxGYBAGLW0I5uCLzslK9MySZGZez_GKlwnXIUuBe9j6Cxcle02G4jot4FfM
8_xm1tybbS8tbBHiAjQh2iw0ejDfEKARF1DS5QW8o0wWdjj7qbXAnmrqkb7b8HPtXWuXBPK0AWFd1F5zWyeNzWFsWGX0I-G4lQ5_ohxJTfQo7m_418HFsQSf
GuBk22YViQy1wFheN9qLv7EYQ_jq403VvxiF2SRdsdvRtoRxIQSOINO0fDeUomNy888D4aS3d-oFwI9s0ERm6NOvAZ6CDeauj4rV7K2zuvFAzY-XZlyrT-PT
m3-9fNnd8mq7eW3MB9Hax-hH54PMYLh29FbvVn58jXb6eH4_l9NXelHOJyUT3N8MyWzb7gY71CrfDH-vLdkm2A9RfYToZP0DM6Ggr6us2gUTCafSAoUoaZbh
L7cfw0PtOixK0vMiYcmOQKVq0yLm4P3M15Pi4OXsoo2hxWiQpOk1uaT3gjxIGpBQcD_I4AonKlBaVJz9U18ZYSDo1BozUNfy40WTJl2XcysFW7HOoqVb2KS2
hwZNPoaWQ-CsOnQLsj4NWGJbSeAWQECmqD5tTOIdVERzJKn7p_Ef_OPws0yxUFUVt8dzUcnVmAfa-zsg3zD-lR1V5kolyzEl-T7ojMu_2ZI_yII_T1o_6RlA
kkqhwv4-MOSCK__s_gBoS6GkKv2aBoI-3Hds_hNpu_lUNAVEFz20yBZLApcp_jZrhUeyOi0te4oPGdDc_RJhirNYgN8OfKq0lkh0gce1Mvctt05w5nWDncIX
eftqHx8-PGnKYr0vslxPRWri228MPgE_s-iz43ymdzZngjzs0iWGn36IeH7btPmFonuL5NOcSb2ckpb_7i-t-amIe1bSKGMOr1TJ_GC0sp7VMZSWXQolhwFo
aA3T1nvrl3K9qf4iZzPT080VpXS2W6z3HjNuTMhpq4qIZquuFwqxL03rUNe93Hlu-Lp104sDV4Ri4AQzu3tObwX31jfpNad0q_dK04tzq3ginXoDSqK1WY4M
4xPz0of7xGyQmAVi4y0yHbiMqG3Ujwzo1EfMnW4DgdpAVWI0FbNQTb7GAlfKsOyXsD3IOpKj5oKCaBv1BjOswujtgdHr9w1efskf5U-M4Nb7SjVumnzywSLz
2vJRmgtPYpUpBNx5zORbMwsyiEdQygrM582MRit0j7RTMXTqWms5VczTbXBLqNcBuPgZK9SkVtM8yNKq2JfpFVS5AkSXnlFGQBQZ2AK1WBnIx2j4RzS1QIK5
KhT3uYRQ1DUHWF1q_mCH_Nt5Y6pTTUEB4iNDMyM8AAwoRX_Ob9DSzj-ta7iJuKELxLy
}

