sprite $Icon_security_2202_blue [96x119/16z] {
xTe7TaCf38LXH1MWV__BdP8pwM6Ci3trtTDSlu18lNbXBvBRCFw8ZPObF31by2sZF0YNPg_BLcrDTRpUR_80NG6OhnDvdTO4GENUoHXWciAtf6Q0tJKbwQzZ
M0-kop6V352vCJnBXtmsi7nx2PRFU638pH4E81_oFMn4WNmqUmrRqOCp45kiVlK1nETt664x0xgBBxuLYK5nJiSrqUHRZ-wSxVaxn7zUOX0TYsd1cGhgMxv_
0xBzoTE2EstxKsX0zFiHnkvuPZZ8t1nGXdRYDyYRdptfn4-Wc-CFHzcSgp7F_8dj7My_y_lM0KVGCxz1sZgczam_GptpA-I_nB_yox_yox_yo-_sDM3UhD_P
UNfiVexPF8nzem1QU5hQVyM__CjFLSVyBKDhUhGlPNnjR-LnlYYlCUCrAdv__IgcvXXU4hDE5k_q-za0Qp5yIcm6MBxRRo-whDhRTgVVMJV0ylBaNVu0QbYc
0kCEluEbMotfEFOLx4PJ4mtqqCz0skbvYyDtbve5J1o-kt9Kw0xVNPcAGVBx_SVfrFhZX8RRZp1_FFByO_CMFVwwRYohHzNh6_oyg_JZYytbhykw65ULeC-l
haA_GFNvtTNX2dIVFx7WY64-7uR77x3s7HiMixYg9fU-ewGiYsDNYFyaNvxl3uVlddymfiUV45p-08yFq-Shf7q_WVhy0dNVhr1yli3SzmU8pmy3uguVOGId
Nq1tVONYzSL0zdm14wyV6kYUhmjZwQz_hOaG5xyehNtFBtxoNPfGWiDt_jU-mmX7lknS0j70vCmF2MWtUN8uz4FXnWuKAE7O3mMOCImIvoj_weTi_Ebdj-NW
y5ThjBguSch6-_k1nlTBi9BQugr-FyJEIuRMadEfEdX9Zu_gPw8QNs8Q7zellNOchrtA4_enIQNKMagI_qo_T_cNFzhJCdXwxCdyhm
}

