sprite $Icon_workflows_0401_blue [96x102/16z] {
xPe7TiKW30J1NQ2z_t7J4wKNyYTLUu1v7bUnnlLozlBvw9NOIVZxydpyHFobF9-U_EGdVoZ9JxxBAycNv2jwVYIr2UGtbtpd-5Oj59ZxPt59Etb_7fBwnF7B
t4E1uDyepADyVo6wueV2GSvl-wZ2RYzdAf5GG18AJ4AXqWfBuJ8rMc6Jv7z0OQKLx4wXhjkB6JoJgoiK3hsICfPgeM00_xw2oUlpMP_mHnHClJoV9VZ32Xl3
3uNM47ue2EA7WYFyW8Za5vF3_Fv_-SbFFlz-eDzlyFkP_xxy_EyZ_ttdvnD-lkBdmwVpRLct5pC3ypcmli3NH_p1__prwTpvWv_PVWFkPzX-2Ux7s7uFxYVP
VXNkXz5-U_kj_VpOLuJ_FvB_fvAV_EGddzzVzFFtHz7xkyu1
}

