sprite $Icon_email_2402_blue [96x68/16z] {
jTO7Zk0W38LXqzBWl_znj-T9aL04YsELwH_XnOOnAnNlQdkmkmw-g7ela07EQ7uLDe3B_bRbFA0bF_w4Mk2V2D5oWzs9ZnLEitg3yFkR5rp1Wo_GYfcT7F9_
rmOj-sGJ_tRDqxVKuF39fkDhROTikhv-xf1DrzV-ml_nohVlwzlKj9JDks-vmRQGpPklZAwmb4tVL-rJew3P6VOjJur2qEoF-FgJ6gUo6VUrvJAUpPIlnpf7
ivdrrNBlew1pVSfN5NgZq6-qUL_7nL0syxwUC0raC-IFArfvrLSA_Uyw-EhmpguSV4re9ni7ltFwwe1ryZKAfPEDZwzHK3P-lkhu3MiPVzzA0rsUphuogidy
VTMkR1pzyOhxaJ_q2y3vcP-Wdb2-yY-gsKuBt_W5abbe7D_uZVFVCl4BNy5KhW_yeC5EaFtza_RurC_NGsihZTqi7j7DL-YwteAf77mrJQrg9KTVJHyWQXGS
_OCMv6kKtVm8nUJhEow-dbQ-TkJbPyWFNptgurTrYtop3QAFBqd-SrKDmtmfYOwlr22jzcRFjvFwx-rVQmTFiQuVORklpP9cwzcR-gfsReJ2VDsPbxTqxwio
7etPAYBURsIVIr7YrZcrFIv5VHqwBz_ZKkpFqabpkHJrdTGPleNHkWPUqCh1LWRUqDBpfnXL8QZ4Roj-Pg2EbNyRwW3_4m
}

