sprite $Icon_industries_2603_blue [96x82/16z] {
xTO54iCm34HHMv8XeFjVjuF5zQGgm_x1q0idzcYIGdaqZVecrrV2Vko4zJzz-jQUwwzUdkhx5_ZqMqUrH_dgE7sGd_g4wk--_lJfqwTFFwDEVSiezvfXntvU
7RNc8p_UmPVDDUmkFucXvEJwL4CLEBkwFtLyAt_YqwTFdtvfA1lwjQ5qvAlZPE1NXwqZFyyhQau3NvSLrVdyR4QVFdtwzEd7Df1d-gdt5FT3VPbFtoIGgWGo
__fs
}

