sprite $Icon_differentator_0802_blue [96x101/16z] {
xTX5UWHX28JX-gqDwlx77ISk94yJvHlRlJMzHUciuLgZCoquHMy3rmO_z8_8LXmzyekZHlCB73touQYa_wJqqqy__VJJJp_zzDDFFttnzCWNJ-PxwxZMwQtY
L9zz3LXZzjNnqykoqdnLMBNvAZZtFVUhl5_L_-EddtxwwQVVrnhgRzGQwrDhh4-jaVwcr1hepyq6H17XmmQ06Dy6edmRYF9j8CotWJ3V1i9y6mZpRI3Cju4m
tmO2VNHIQupVU4i3_5umQEtlhnH0AVrStUr-jTxybUJ081lslL_Lixzif581uOPFtg-c5-iu-wVcIixs0FksyKnZeHO8jmX_0b3EAvtisBcPq-sN1K91K4Mv
s0E4D94L6mLHALTCWGymo8taG5H2KZh2wjG9fuu
}

