sprite $Icon_cloud_2005_blue [96x76/16z] {
jPY9phKg34LRGCQkzt_SEvgG_4J50wvl7awfktHJbVVeaQlnFwr49plHMFa3IrusuJA0bHYSggZpHsu0DSW6j71cErvHyx9AjAj4NG6ABYTlGJh32hPo2TuW
oGt18Aw4jo2tQ8NyU_YcyaJ-TG573tz7WYJlqPxzymB7TDIGgW5M6-PaZW9EPZWgT8BCqcXJhNJQWFS-n19b6ZTH0j-0xEKd8kZZDYEg_4eZFvMeEFcT0Ew-
2wCiqUugKE6GDI9sftsGHVGwHe0eovJB2Xj5rZck14gOoZeEzEA8YB838yX0R62oXJhcwHfGl6mXaqVN8Abi8a7yOq6gassu1baw1R9i9KCPBcSd4L9lsYJR
IH3EqviY7r3EPitdrzseaKN4mI6VS80JIJJPJpyfxOlqkuy6JBv28IIAV4OXDw9yHgI1by_m04u-mm6eV8O2o8Uypb-Fw5_cxrxUHPBVw6-4LvPbRmR8W5MI
J9CnVUEtYPgeCibfjMga-KdQloX0eNNVdSl7IPlE9e0_qogJyZIHE2jd3-iXpEs6A296dfq8N1TgRZUSSlgfRBgG2d76t8vp6ZMTpiQ5oK5UZTg_czoR8Wql
Cw9gwobug4_fL6eVxPz5rGhz7m8q9pVqU4RewztwL91EU7ZwrVKmmlCUJM1-cAWjgiX8hsUFt-izej5Wb2CQK0vtuUDHUlpUFGFkA8156T5a05ZB5yPpnhzw
K9BQ6I1TwH2o0TZOAM68FzgG0LWESeVwC6ZKg3B4xtxNjGbUVvw3JuhrxojDrhdkrVNH_i5hTjoQE8WFdhh0uFMnw70ch10Wt3owQ1HPO0pGSCFo2mm2g1_b
M-2nW0x2nYTH8uMqDC0Vgdf_3iQbtVd4MejfvG7pSiVV
}

