sprite $Icon_documents_1403_blue [96x101/16z] {
xTc7SYCX48JXWOK1nFJxF-v5oeMDD5kYrnVrLxXW-sjbYR8i6JOwn8ltBJxXj-DxwN7vVUMf0KELvpfmCi3xnHtW_IEx0xml_W3ldmpmlgWpmFl-0E_x0xpl
3_2-Fy3x_W3l-mEyxm_mlZ_0-_u0xpi3L_l-WA6m_Zh0-_u0x_i3lEyDy7uIPu3tFzRU1Zx77sm1hl23VYoEOSVd-ilybnzFe_o2qphZLvncZ2_fjF2VF7vm
jV_oN_vnysgqt-2MMFzeNlNr-5bw-NpfT_W6_TJR9zKWIo7hMT7t_HfEC__syLESTlDzll_03qbhQxNaunFye1rlMKlN-g4EkFSnqzE5lXg0hiSOozK0tE95
VcW0sj2cHKkN-A43_RXxgD0B_610lVjr0vJt-yENv6X0Olqwy-k0HSvFG7DVmc-Sts517bU0nFWPoE9bw8pVONA_SMHM8Etx4T37NnnNeEtx2eH7NnltIuNj
-pVqX_mXFyh0iUqRwWal0SZRFg0EJvwuqtJs21f4HddmeuxA-mqzhFpm6-yhqCFAytuU_oXZOE75gDkdoBk1bHT0j_sE9lE0hlm1f6s_mcGUM7bH86px6KZp
mCfBHvTj_yEhLrdv22ZXLo3EshsF_e7m8z1EpZXrVEPwkWA8LF_bgyF2-CjE8i7zY53VRlssvy_l96jbklN2JlxlmiPh1bi1BCjIQEEQqUdwyLb4ZRdqwoTP
p4UMe0QW2jzyVB5MSaf9QryEC7In6kPwbglBjUD7rZHUGtu5
}

