sprite $Icon_alerts_2505_blue [96x101/16z] {
rPc7iiCg34G3X6AX_V_FVSNMtBsDcUoOlB9JqWz4h4gSXw1g063ryHObGyZIE_WJcAsKDW5x0tu0_RhNWR4Tdu7Z4Jg0l9jly8-e9zyUeIVG-AW1pzs7Exy-
z9rqRfXVfs_0hWDkGDhgpRoqqtsLNmpVWRBVcrHop4tu2hHVdwrx-8kTJlYM8-wBP2fxF9eMvL8lGmA5AoiIei382P9FKVMew48wLnUpICeytPj5gXnwKvGg
d-xDf5HklIbsgVFetfJUf3V5AdJ-XRJGrbbsUNJyvitvquzPzYW_zWAV6xdL5CaNF2eS6_ah8-W3su8l55aXRSWNceJWJVA59YUKBVA5LYcKNVA5GYvuatoX
LGfjZtpXCy9Uo1U-in1ByeKp4xn0lk0vmSla2paZv2BvGiuBjOHyeMO90nlvSgiK1ZRoLO_Icm9VQ9KSs0I-sYeDI09Vy2W7De6ljahEOZgV225153v380HF
vBEyw8TFlc11TSuRg4fvrnj44jkJFcSB9KmeVlBegdjJ_yslpy1bPA45wWEUOGZZfTxy9uOm7WlU5FXqYtujhLgHVvum8tIrSQekF7htMkP4w5XKctlNkPx0
_5iEf5Mrf3TrrU0M82yyocpRnsUhvC2cATVy6p_Jz1UOtbJZ3YkFT91lvL4CiLMsIeP9KFBBCmuudp0021YddIPvazPe3W0ZnOhdGsyHStgqYzjdiKe3dtCv
6KQwOauTS37wFmsHSbwM_YS0b3ljhyxp9FBlbmGBeBUj0vFt4MgCUToF_Jk6VheZVU1dBQL_Yd8_-Oo_NjlI1Bp6zevuAewaESvxJ83aS7M14G4nJ0QwHRXu
5jNXwSh5LbzKkd1-EXGCXS6khbMkDzGnPdYdE5xN28kYdqTPU2ZpNEM8GpurSoIVlRO4VUB1VtxbJmmUaTKxVtUEM2NayOHl6DBA151vnO7po01W-IuUW9K8
ivV0s-N86VwyeG6lB1MmCSBqx5gtr3zdK1Z34h_T2tpXmdGzfetdld_EENca-dNPl2Cyd3mwhcHbNJlogjlg7M0u43wAklQtnh7dNsq3WACwu9mdkhE0t5Go
j-VZd4-2ZxyVTiVnsAb6FfFg_yKlVwkzYLyG4f9AKiUbTOlz4m
}

