sprite $Icon_threathunting_0206_blue [96x96/16z] {
hLffckCg3BGGEwhx7_TjzfSNYgL9UlHhR4DfBzHahYFHc6l3Iwpcg7Bz6T5KCPMMzFVWsHwmccFmNbLzYAaypbZvZGg9TaSZgKn2Lc_5ySj0kMm0BFlr4dzx
bx_G81a0AeEFAkfN6g81oExCJm287sMraKq76jfvfXE0gX_bgW98vsijN1zACA2UUEnfuQb81Kn_jeDpTIxfO6lQ677a-Zu96MZk-bfSsol8-z0xzV-8RWoG
1kHTSEgIe8lX9LQYhhAyzY02JLOqGx8cfWg4UNOMyB7TF9c3LoSYwaEkjueeyn3DD8l1P8BUaIZxP9DOE8EvgLyw-jG0rB2XpacdwooDQPQNJ4GqfPqg6opM
oIng59ZDccqi6amctLZaY1NIcCl6fSbnZ6JOKjJ6dWez4mbG9_1wpfo58zJ58mDktsjx6HKeaD_DpvjUEv2H5GeWI_CTzTgH0jz306bfVWDsiJ_g_l9w4Tdy
jA8eKLNjODODfAyIQkENEi4E3qF3QfHf7qGkeGSEOLPRFE9qKfZ1nXRrW3w1ujg9Wt4FGwjp6bARZeJADMJtio6p7RopqR3eab7xSKd-RxW2dimFt0mZ4Kd6
iuzBaWEK0Awh0Tx2T1XX1PMs0cce7k4eweg8rBXBF6cig9TGDYCWt3XkIPpjeeoMlYhiKa199nzXVZDBfei0EG6XjvVTKUOEhXX7gps1vL4bPRiFL__4sgrt
g25N3XdMsNRPg14o81HTUYID1NMPRM-unR-NVDWa8AC1aJnQsQC0ilSPxo5iA9HnwTMH0UGEtXxRKwZEq3OLutfrbF5UdRk_4iq6m2qCTe3swleNqglJDwG8
J8pGSVyEtz7t3lyLYRUSkRrzH_WS2GS4sh33ttzNwYKgUcNxzlWN45RgCf2U5YohWj4XlvlwvCS6fF_WcwpwtGD2zNdSNvVK6x_AaX0YG8y4oFpGkt_truPk
CnhH1HcmvRTH4X5qGo5hIIFbY_YPHOmErp7QSM-meyax9ZhST7Tw074y7zloVEJ-KA3GOhkuMicb03W-tvNmbrEy8VFfGIdPp2UCxuO1A0o7QniO_Agp-SgF
-9wFZZ6sXZJEXmh4GG6ozFYIGV3ZpYUrXimEJ2Orw_5flfrkJB33-LmoJDxnnMZYdUqp59uQ7plWBXBdElkVPu9ZEr--bXwBkd9zFd2ZpCELsDu8n4_nFL1u
QUAJYV-QFSSVUoq3qlsJLkid-DAwrYAZ7P26YZItnsVuCAJ3qPpDJQiRV8Pd0nsGcOMPI-3Fy1t3ZpMU0B-_J6Ry_SB0hvxqCoiqzoF-YuZuVepZdQUtWt6F
7peYedEDNeNPZJ4ihl6rJd-d2PsnDDwFBbXoK_pG0BGntmgqQ_fMLhzlrSZy7ugHSp_znHowQnyA0k2O_u4MTXVevzV_4YkWXD-I7bxrlRTnMH4pyV_pF8NF
P_UOv_nsZb21-WjyQGG_2r5pt-8xcmQ7-ypyT_XXnbZJdarVu4l1eZ1dlAOR_EDTEqkoV8Bl2duCFRDYFCQN1ChQqQ_l5kK4Nv9XdzWbwrZMd_2rq7NnPnhG
ejlmVp80AFgh_xnXERWHtuNdQtBNzn8gSEleyMzieFXlaVdUlv_Fd_lqwy-8y-c1ChZRh-JbQElV
}

