sprite $Icon_governance_2103_blue [96x109/16z] {
xPhfWlig24UZ8cwSzt_SkzV_aic4scJkLZvsz0H-0XDfDx-5N0te6hVhBPN1j57IfN2f1e2rd9i1O5MkOOVS-96OYW6NA1MrJqKSdo-gqdFu82wfnqhvLHbL
78VkK6fnMyXzvuWtLu8pLkyMlpF-aFrBbfJoXxWYhb-LTQMoGvNbganRSPJ8kb9j0tEK-A9IBMsGjpiDv1_AV_FVV4ctyXFSofUlvB_vRtw8COOR-46qTkDX
rgjAk8WVSXryPAF8wtnf3vz7AqLppbfA6ymxmIlyM0s0NYJi5FihAYjXaPyQ04tEtWXhNE371j3psU4CW1gUvIj05qyITi3qARuOqAAtpNTWH3zVWI5E-lH7
dVpOvsA_5Q053pyPZBG3U4AmUCuNWxPqV-bWwOoV3xHnQcJoEJ-_rB0LI9_oomnnoJBeYJw7IHz5Q-kzjwfok2ZbjVwlpPZcksVw-Ra_g3R6c0zgSWbV3S2Q
fl289catW95Vvii0hAQ3VpmzlSGF3J0z-6CneBx0JmQKawupuYfVWVvvciG19cjy1TJLEFCAN_7LSWPaWL-nwEtCkgAFUn8KvMlURz_yc2J5c_X1EtzQo-5o
VYZ0D2j-VlQip0POpP94c-4kFUVRGlcn5SlmxLE0wiARx7Pcpxv1F-VNVHDEvWYWOnKy1_N1WJiE05g-iS0Iv03rBdw5i7Kit8CFqBTDeDp3rp-b7tS5O8m_
Y-oU0FHHWWFYzVW8OwPHzryXidDbOoP-zLzP1irz4vWhWq7oUbLywjZtMIEuSoXvuqH-aDLv17xnoyyVj4iRGzy7LA_25nYxUP5TLcOA5ZywSSfD-Fc0Ueau
bevoblRwqHw_TeSn3sRHGf_uemTOMiT7EtEm0NaLBmRTCuTQbfxYScAa1Mq6MFQTqK8bwEucxBWrkorsdYcUD9uBGG6JPy_AnE_Dd13xGt1ES4FRkU8DskDM
CO-KnnDqqzFPKp-8qYcIwJ7TCQVstBiq7D0T5ULxGecxsTKCxLNBu-Vl6bB3GVURT9X111rpTdYPfGh0KEq0j7GbVRhD_4hg3el5dlwjpQy
}

