sprite $Icon_governance_2107_blue [96x110/16z] {
xTQ7bjmW38NXeTb8yB__uwRwh4uyMIjas8wsb_cGBcwtWKfxXxwdsmjKoBLpLAyvJCNZfeSCnogwnKbusjiJcI678logLlEqLBgKdv5ao7U__jywDsh-UQmH
zVBbvfyRU2ILUz_AISfFnV7jwFAJyaCrts_AJyNt_QJy1dp_Fgcs9pSLtxzCgjTiOzb5PSJtayetESqpmxT842SLn_UJSbxW-4xbz-ulV_dBN_xobx_yvIz_
-SjV_lANl_pbBt_vvUNy0h2zdBy1r9VpApJqvNobLNWv7sg1_59-XX90NieN23U1-39-_DLwWleoVeNqQvDxU0a_W1wlgI_XLux_LKZp_GJwj0zjlj_ikDbX
d-gVpGPvhf__o2HsUfpfdy42BSppGuDoFfXqdg_tXxo0pl8LnFdbaE-qQfdf35zjB-yN28_wmNZ_J-D-l6nIeET7_DIlGwxEyr22v3plLFU9fLu9nUbkyuwG
3ksv7fteBLtdtvx9o9synN-yjA9nJ0zw2jRBg6yZVEbODdu56HeXAY2dezuVmMv0VfvzTCU2O2DxqL33RRXI0pGv_wH0ipQ6Qkk0n8lW1UT8S4AgNAmGAmFH
N7I8fBya8xQsKtx2w2dYhBRk8sMTjYqynROrqsTKgW3K_Ajr0Q36syGAUmVe8h-_sZ3JAYj7IPwEM-vQXbh_3W
}

