sprite $Icon_threathunting_0203_blue [96x82/16z] {
jPYBjhEy2aKJoHMOx_-wv_JNZhJMQFVevzptYmnOBB0nNB7aPcourXJ3FqIgiKTB33yHSyd_XSXhS6ibYooISbNdGPTdSUt_bBI4Fr1vK4DsmFjEaAKeWARm
eB7YFNzRL6V50Sk77Ma0-aXQLDLW57L9Xhw4s06LG_MAiLB3HapLjg8kKImyS2mS81t0crG7avUYgWFzKYKeuK71mmTfrVwXsbfY2IyK1ozVn-SZkW5UOzZ8
la-u07fUWg6RJhhhgh9FBohOilydbt12MVjMTxN7TcYdDi95IJddr80KGbpYjC6uEUXNqcPm2LBKOT1yC_01iSDEngX0EqueEJZ7fDdIQLN28FiicR53jAR_
58bI5I19SVp2hIFvSXPztrA3Hs214YvPR7XaZoXWEO4lOG1vwsGFLsI7Uh88xQ5n0ekZuAVm7VrYbtgQw6R3KeNNK4uRNq_f9zgy3MzzhR91NY-MS8hEfxti
cjuXXuteuEhGBetJJtIJdLg-l7g2o_06RHxUTeKj_lghr5fTBiFNw_23DAbsWix3b-EsD4W_Xnzk_yJmhs_oS-qNduMHhnMg9yqtaFbbENn1PZxPRHRZUuLa
8l2rIsJKFISwFlNkSFcikkKBwwIJwqjpi9vckUbrR-j9_Sw6vSbiv2lnzQmqy5PoCoQxpx1mmBK5ihepLdxIurj3cXHmCUHHMLc6a1o6KZnCIJE3TT2Yxn75
8LqKyAKw0dNRyk-h0lbB0NLcpOe_avFPqhykO9aEPqF7QuF9E5zRI8Swa_m5vD8F6MJIt3AVYdgihHsexVJmnz5Gq58CoXT9LOY7evrERySFsZTsYOShvc8r
5Ji-8Cf10HqxIb_2LrmNa43cwS-9SLbY_2mWVmPh5wOQHCcrgJaCtBJNd9PnP7wd7VZi87t9pJZ5Mf43PMNlbVnX7gawqjNUQiav9P6KSYwrTNK66Yy4Ccpt
a6J5UadJe-QIohC-hCgxG3RhqL9jIxf83DT8xbkLBRqwQFdintWweaN27rXoTm2lMzJ8c8fK-pPmgQ_1Smn_9pLVBzu4zvhU3mFPvi6l6VbvZQ7om9RrCEE0
-LRVJyIi0BvzyhWUdE9ugFOpqf-EpV1KFeu3rU_4xGI_gYIxm_3FZ9Ext1L_2vPWkvT5fuPVQ2qCwZPT7Q_GOX23dvmZRzT7nrDS6jHWhEJm2_4zG6P5dy-h
F8NVCDh7iyRjLp5b2R_IiFtQIp7yEmg4En6GS2TGmfqOBTn9HyETL3pSIOPuR_vOZU4ceZBMm0qOk2cmt2L-NK-iUfCvRMo96uTBRX98wRUQj8BCZuY_4nql
aWnok8N4IWit8NhyJEj_
}

