sprite $Icon_directional_3005_blue [96x96/16z] {
rPhPWhGg38Hb3oJV-p_kMRdm7xL1sjdgPfPk2gaK8L6t6RYGf1dGOKros1v2A8rJgCJtoQjribfoYjw7468gjKzfRqtXYW5OJNuxm2Sn02jkaLq0h8HNqXc0
-5Ns6iS20iZTDPG-QbP5AxUYgi2yhgu0DXzf0Ugj5ViAoEHtjL_CBGG3dObpD90LkrMmkS2cRGdHT8RU_FPf46Zky-WhjEtpK3wNFdykVG3zH7fls4EXrJCB
wdF6DFGijcbx217aA7vzT1l5WpfFxYl5FgeJ7_PYsUS-epsU2VnUB_op_CvsyVHGFY7N-DtbZuAR_Fq5IF_L3I_VDThw0iheyfs2JHCVhjgeeyoqmB_LFYP2
75O62_oXyrPia4o8vIR_NXTx6Tq45hOL_ZueG1ZL4mlydNamL43TjiRVbT4NxcczN5da5tJR85tlgZxt8dy25y1Vsxxqt_CIluUGuThsULzRjDQgI4bXFXL1
5lJAzdlXwiVErCtmDwHHhss_GnIHsfeQ7Lh6wwWqezmiettCOW1e6kymIDUsluPB5S3oo40Ghsq_cA81bWQvYt1b-p520vg__lo4tod8hKxMqaj-Vz1URbNr
TZt0d_37dJEd-zdsWZ-SDAZnTblb9lNlcI4zqbY5StzwWtntWdhbptIPElVmkPISS_e7CGRltC4LvJpBzFyFJ5euG9law7PxCfpbXqOTd2rTIFiN762jX5uF
wbb-4zhrsRXjf-UByo76NAhQxYvVF558aGn3rrsVZpwM1e0LNy4VpvS0Vb0yZCxVM1H0GKuAb1TUBw1-wdmF0W3kett-q-Wwju3vkVh1PUDZ12ew69h0mcnz
KWmvr5U3-Z22nKd-pILta7zGt_Paj5hV3klpdepUgSyZXD44ji3VUSVzaTFL_cYslslh_Tt-jsiqT9hus5GBzedzzUVV7zWgk6VfFSW-5jHd-UkVaXS8JzB7
ZmN2SpSdpm_B2FAaEeJXBRzr92Z3Mtxhy8QU_LSV4z_yzdbGY9z8to1_BhtyMdhtkVJ1PXAnMbhTLbDvtg2wjGV65cUVRuQxzD50_VJPG_Lt0ulS2XJ5tP46
lRNaOc35JREJrvxlXw7kzv_lT_ZvznFSU-zNdBviudCr0CrkMqUKtViXCVoBc7Af2W0cuVrTByefMWcFPPOiJVTDjQH9xhy1
}

