sprite $Icon_internet_1508_blue [96x92/16z] {
xTe5iXqX48LXNFlV_t8ZHAXmupHFEINZNuyxhpur7Ki5IEPOqelnh-zx7CtGmsZ6xbNzGX_DIXtDJdbLVlxgbgzk8wlw9jZHiC7Cvbxk_d_zwzUa7p_z8v73
Vhtxpm-v_lMlV_sGIpZbsrW5G6gqwhvBZO7BQBJa57sVEmClOUdOzsqeChoU_R8mOqrj-cM1rer1jJj--jsAy6F9qevV4FVRpIwKFR-RtwQ_JV_wtXxrCtBI
pz2L_PMtn_p9w_kJL_LzM7bTNoWBh-itA0klviy2azVrPu4qUMNVDYXvyZf-Himi02jlXBpZ1_2pm2CVmE_uHgYpewsyQOZPyZE4ULEoyX7odcy5SR-vUv3T
-xUmhFIbjj_rvow_ndM82lUt1Rep3_42IUN-EOF4nvuGbUxFewptiRw3QDoVprKjSpnRW6OrdryAtolOBBEQbczS0oIxK06ArN--2uslgUxCysceZ6Kuz_nh
OxZl1rHo_UjV__Z_2Qy-7m4
}

