sprite $Icon_global_2701_blue [96x96/16z] {
h9HLWk0y38CLQD2w_t5_o0vvb6mxeAU6FcEDHqgb3UERRBIIy4lATN2hKNzk8pLRB3EIinMojFcw9gtzn4IeneNDsSYUW4X680tIyhKCqMh0jnJRWfS09ADT
m2iVk8oMW52MYVOD2w4jtrRuQT7U-6uhLVkEXMBlaKUZHNZ-sbp72CL8rYzLTP9MNbTZkUhvoy3ywCryNkdg8gvaXlAHoUgosHxMTJfd4jcmuwEHoOKy8-wL
pITpSaBvUeHAMhulB6dPhzE9dydBUyPod_hfUitOSUAZqrnFpxi-QkJmuNXWbALtUBWgx_0TJiQ6Cn-D1gV-DmDL3Yyo2D-lBt6ndalRuJNTZlBHEI4Hx8kS
oG6lH2RXRs_u6cIeed5gFVoMyZ4rtvCM8Heq6OB6SiSlD1cz6q_H92gfxfOVDk-oDb7QbRrpGFaITzT6bAfC3KdJetnDq1xNoDu-gvERhQvR-wS-YR-lwDoV
GsIqprkJdFjhUh7fcDBEkCy_CXcsmo3ebD9toh_nGoTZsBgFoeadV4pMxNE6royBK7MsP_pE3bMmLxFhuxxxbR__0tpM_GZqQKtF-4aAvRWo9FMLyjKJrMHp
UV2wQ7Z6X_72HeLsZWwLuob_x0iOoIHjgErpps--WNpZ3hR3ONd6FxlOE03v-pIfoj-NIlTvJB_QFVCp2HnQlD1EP_78rzrmoa7Zm5RztshDAej180Y2h0ip
zpzkt7L8g4X_yrYthcw3zV_7RwydLhS-2ux_jwjg4ytS_xEAQkJ-7tMbyB__3xfIz7R5gP__k_Z-uSUN-t_a_q_l3_J-Hk_F2JvVwFDnK4tW-VxeVb9ck9_G
zolwVWZVR-dxEVs-WDz7_FkEVv_ox-l1GVu0x6_0_eo3_INO7vlFtwktpCZ0-fFbbh_g0N-LyOSTx6_Z_hoTB_ZfV07c8p3VuVYK7vzppdJDr-8KliRnmQeg
4UMRtTdvR6Fuh9ql1z5-nPVDIYTyt1dukEIN-7uDkt_Tv_jLtaaGw9Zz_No2D-GJBFcA54MrN-Khn92leF8XTWKitt9KIAN9ySzZAyduxoK
}

