sprite $Icon_people_1805_blue [96x102/16z] {
xPY7bkIg3W15ng3w_yzzxoQVtLQZjfbmOzT96sPAHW8Hv89Osb1ET1ur1VaYGZcK1REbBx3dSUgEtchvXTgESopQegmP_8nwdzv-5usdTCJI9m37UX0yyihU
irUKDW76Aa9g9rqTVrLWrfTrJ0V04SKbJ9R-E86PhwlV0Ueh_LpuAw15xX0FO4HNVrIiFmoWorsoWXPFBnMUSwDPDkX0S_HF_gmmWcnH58wrtlepq6MNf31M
UklFGBafjRgnq1l_fjuAxT-iFwhHRmReHc_yORvQAwcKMakEhmAK1xtr3w-qiHvwtPgZGh9wISmVaOOiA0EBzY3FP52h5mbdUD3WD3hqQ2N545EkVUArjGRz
Xzum8OibJK1xCkcQB9Ui3517Nw0lLxwkIfu6C9CO8ZXwKJIikdUJDNakrafGcBAYGLtCXnd5fM6ZX-bjjq6P2_rnsPcRqJjBg4As4PtSc4zefYbCT9rzEvsC
tWsG7_HILYqcOqVLxxNf11eVcu8on790i06dAxNJ-a4l7QAjBhQIYaQvHLFJS-9pOWjaRxRkT__9zDDZP-k-NfgnFPUaGlcmNfBzxMYpCQy-lytiwaMWs_Gd
C-dgvO4dktePJFlZmLGtNkaXUthfOEFjfAU3DY2RWucRZyamgw6BJmEDKe1iz5w1eTl_ljBBxm6CtfalqEpmhlH_13ZrASWB8HIZ21VwCy0V-emQVxT-M_vh
lKWvarFD5od7IxzUw4zobI_mMxrbty-UNXh8It-zKT_gwgKx_gtvUHYzQG36lx--OZDwroSJtUyFFW6QJMLx7FbU-rzjhyP0D0Mr_Nc30vxFE-FXRtbdVt5E
7oPaDldRIv0zMng2eevlUty_LNw9ssVE9yLaSr7Y36NtV6KpOKamd0FGrlcmGxdyZmxHcM3NsHdkmCPFWsaVEvyx0xLLdMZupFt2OljaCRRxzwFwQbr4CGFO
lj_P9DekQWQmVp_r20SqinvsxjTfugxoCiO4fhCUjjy7B0h02DRrRCghzurWtpSieAFdv_L0kdgVYUPzPiswx1bckFk-vDfzlpGOjzx7pD1TlsN0iV6-j-Et
Rum-ktvRu_h5VhjcntVwPVwj_M__s__s1sZVwKzGljFV87wdNvdoZVuAzHlz2LI-pvyLqhVvGmUgV8q_vaTA7G15liQVM36IV96_W4Lx5lb2VqaF1BbWrszp
yVQ__JFVf7tClyE-lxE1XblE_mC
}

