sprite $Icon_payments_0706_blue [96x96/16z] {
xTg3eGDH04JHPq__vNx4M1jpOvruNT2G5HsoQAXWJl-IDtLfqIbT2tW0C6Asp1bz-lJfqwTFdpvzBTvIkGmkVVWQiFRZEeSHwG_ied_vCGmgNVolldqvyDFU
b6_LvQAqyduwgU-GBnSzqkKq84tg1-3cbijfH9xvzST9VQ4lnn-dC_z-wCy_V0WOaMttFL06TjxV3ttwzEdJfqy_3wjK-TP-Ne4HgI_zwpbbY8Fp7xpcyW7w
zAUDFdtwzEdJdt_xaBctRodp-kKN
}

