sprite $Icon_governance_2101_blue [96x109/16z] {
xPe7acCj38GV6IJr_O_x1-oY28M32c-qTYVm67yjDN72zNgOa0K0HNkT3viOBJYTbV0rSK1A2EN-QVPds2OKZ4HNIpdYb8s4koDkz_o4AsRjDQqxUwDtXRS-
wvsQNwPFP0qpkQ9uYI8PHSagLnJ9ALrvxfJ25OrJSUFAaLNfhdHqCvcTAXSWcoL-mAdYBY1Sdmp0_wByB__Bz-wZV0TybEy_nV_oltpZnhayTyV2JCcf-OBK
jGXbwCsuHx5gFbA7H-wJPm12fNvmEhxj10YW2KyLQpCWLiDl0Yl-obqr4M0TlmdCU3kq4n0K_2OmuslAdUT6G0f-4v0PVn5aSal3Rm9BUemobMDq_Ce2qkVu
1Am213xa3m7aP1P8W1qM8kluXW2wZK6UZjNEe0141R_XhrM0EgGJoANWD_maqDhcDhW2U1M_uXjmDC4982N5BAWT2hu1gCzusY8Ozn2lt9zz7839Jjr5053y
uFbep1z-ld_vNxwnzdDyanXOLwdDWsOAIduGt8FTTC1tRTAUZma0fn2pJ5yMq0aGTFUJIWbD2RqbiGeqlD7mZK0QqzSaPu66r_3ZSE_BW5y46bx3PyXutEHP
NloAN_cxoJK12RpKXma_Hy3--3HJJu6i1eAt-9P2tlBJoEVb0j1cqNw2ytRo2ihOf0NFJmG8lByy5eWPxcnnnbCru840aCDs0ld1EWRiWhyU2pWWJFDkGgHM
391NV1NOp_0Cc8iWPl-z1TNaF0EyuWU1tGtDroot0X1YcUTvRlWgiCamtOHvMy1bCchCAUHXBeKDGC2tRgG7FselH2MO-V7OsgKVfwbnCYp0RHhHUNu1VBCJ
yJG-0AKxIKuxPAKVT8_MEXGC-76iwR3vQNvGpk7pagvX89_2ftRkZ0Bf07kxOHW1qYcytUnc-OWvuZPpzi0WF_fvd-4sCCemrF0x0R5wl7sQO04Gj7WlG35F
XmT5RJtIIqcmrNaZuSKnGbBC-fVJIdYt14juP_4u1f3UIrxyksF5_kLise_BtYkXl62IALCgRnJzF2sJ1DfzqHO04X_c8018lU8TJmeplLcZZN1JC3jwMr5w
XOf9Tl5zKvgo1f3lV2jez1FX2MX5c5ZrE5m7msLKQ8nL2iMTf7TftmenroV29ddxRst-1G
}

