sprite $Icon_workflows_0402_blue [96x48/16z] {
rTZL0jmW48NX0uCp__i_RbsosowLGEMxoaqC6z5F2BbDFl9HJNkbpYElKTla2J1gjXXYJAKvG8_Q8WvWvA2BM1sesg00m_IDx32ZxkhWITzLWQHx1lIW5ymX
wuwo7kGmRxx0Pj5A691qK9Xuq47H6JefGzP97TT94OfEQhZsi59B2deIDwtHx7pGWXuDkkxhWCy9kEb1mRSyVfYaK1pYym3PXcLUlswfgGTEqKr-6MDxtbA3
fdlImvXqXguQGml15gBUgyp7mT9LPTfhWQNmyGkxlZ88kkWiEGl-4yzlhBYMVcvyT8-1lTwmZQwR9kFw-Mdp-bI2_lLoRDzVgk0vIDR1m_RpGIfyDiE1yqsA
dVTcqPD9rnR1SefQnvVz6lu_n_U1_yVvLNJ6lvlV9Z-RdzV3zSMwFaeE-LXz5ngGZjMdnM76G_MrLGVgrlx0hDbYZ9PAN_G7plGtxWlfqfyffb_n5W
}

