sprite $Icon_documents_1407_blue [96x127/16z] {
xTbNOiGs301Hi3VC_O-R7ZU6aI1pKpb_snxXxeNaTYvr06Z9oVwoyfRctRhh0DfRwmhGtLRUAz23_5BiWFgTqm_GA6z5XU7s-Uthl5wXRUC3Q9Zk8kpoEsJv
KeQ-YVUWCgNWzlWPYanLI7ly2a6c8bHvNXjlAVW__goDjvgHZtnAvXoVYZO_yTxY4r6_wHV3L-Z5Vddg7p_LBwM7_a9ZoZ_tFTUfU-uxPQw5JpbvxelxR3M0
-hglR_rB_EFN1xufinzVx4iRffgOV7l_KV_unp_-yO_lK-r3GKUhoM_sGr4-fSNly-DuTz_FwN6F7txLHutU_Ve_Pgg_tHKs-1L0ivTF-Q9tNrilXzSaCfSK
6FvRVWGeigW06h_X9q23B0iAfCT-1BgxNFl5Xtu0cbpKWF38TmfTBkkWxedVOSYD1hG7VWBrTtUZoUoxnQiMavZz3CEoNxJw2i6o7pNw2RffGPfiVeTuDRM-
VVqZT9FlGIzvI8jbwwMVe5xpuoEKB7w5UCsxnJpN_W1duCN1iFYW5bv4mU1xw2PUElZxVe1cugL1CFdlzthLSCLBlVBNk_S4n8cVfVXmVkb0dFXvVkFdVpvW
pKipVNqT39aFMFComDttHK7c0zQyW8h1x-3d0zQyXsxn2wJfH5Znag5O_3Z_W7NMl7G85byKt6GiUGSg9hz2dkwh2ruoL9iVGELs2i7WB__dM8_VnUX7K7UF
TmhHwak7UizlqCJiUo3TuHFWxRva85pp0SXYyUUhxdFpbNYxxmPe4CF_AJPVd5wyFvIee4uU-kB6dpzUcQOt-U8we74zFDs9mPyhgrL6x015nE2lrnjQmhol
OOGT-vci06WhASMOKcc_tP5txPVIO6gadVknK3gyrxFVlzyBAPTQIqxXx2UFV_pZ7v_Zhpl-yOy_wiiQl3nzCVyZ
}

