sprite $Icon_global_2705_blue [96x96/16z] {
jPg7Skkw3aN18bQi___SLpoUYrm9oF34ENjQ15gBm6PHYvofj3wM0g1xzbQJ_9RIDJPFwMpvStXk2qEkZIwrmExb8tfzmLczAUmgqjaYUGAZJGNGzcEdkW8w
QfAYq4JUV7aTTv7I5M3yoAUcmBhUE2toXIzfGNyr3O3nnpLSQebbHRCO_wK5r-kFr1NeVzH3Nb_BtY_yZIyBifMArZ-pPcPvQq2L9pyfzdVdtAIqG2-RGz35
uKk1yRLYj1nvis4cEzviSVdIuGkn0UriO2zvG3o-R9QOohQ2GhLRcKaP4l4hr9knytjyXvLkWHJoPR7bgmQiR_7tzWHTOdw1omNuQjRgfE_mPJadX1RLP-Vc
li-lK1uT31zVODyd4sIFRzgFT7imJPEYISGjF-Otk9yqeJZyzGmdk09-_1D96qtUs5vEB3bylqHJLkP9J9PZhZD4IPwnwu5wrfIWElpOe9ZMOOsx5inRQAFZ
9ds6nkJcclBhAhTLDnw2FPpydLp7GyhoDqbJXYAX_oRrrjC5DTfbx2Tomf_kZhDPxYvZ6gmZVaFzpQnukunfqu_unJzT6TuID47r-Vuo2HT_zjipP9Vl3x3N
RVFzyuStva-61vXlMvOrUwZpeBSpcNt-jFDHVgNEpXItog8VyWiadp2TQUwFci-F5xeDxAQxVAWkF_ofkp3SHZ-fcA-qACN8F2_kyyq2BnxDVgcd_7Y6os1A
PqLyEUNFWD_PhpuyNUWnVx0YHbXROv_ol_LWq_uQlq1IhiYx3wCY2OgoXgU5_ZHgWiBVrGLxULBqEBhKPsmed_iVAqC-c3yVyHVzh_4hX6kxeH_pBpHUs_0n
lxFZ_VDp_Ylt-l7-7wlkAWbADFOVy8ykRh_2dyoWt-it-E40R_gVydERx57z6mM_hdD-wHk0zojJquxkFzSnFrrJ0NHUGm5OBTivdzm_solgFQfxN7o3ojdz
VxTydNf6Sj-nd3-_TFFR7O_bliOuV_wQh2AHydXvd9JkFtzu_F3MBTx41fhYXV4vFq6F1_XpldJexI6Ozz3y6JznBFq9NoRelalX4Jhafzd-nPVjBKoeF_C_
RVJV_E8DyMOSy5qyb_5V6kxR7ZtX-_WRNpQQ0eFE-OP_yBEodIVaGtvzu8rl1zDvntB47om7R_perRVIZ_WNh1l-oPVnw62WP_vqM8OF-3Bl7MHe9_nt1uRt
-J9XtWBwBNyon3emVFIGEsyVU39qX-y5EXW-V33kjmzK0_8t_8erTxZYwM4ryJMQbENn3J6jzORlxZriKLZPUPdlyQtP0H6-zu2Ud0-n3j_xhc8RGX9NLK6R
ERHJp4yRBJvUimHA7TZDFbmbupiWBZV5Ah7o07JajySx6T_hO4JJC5QP_zpuNQ0bv4jQiCljK-qsSsAN563tsXH6_ifF-PQkVL7F4nXof3eK05LWZyakzMfZ
ANIvPSp8RsFPLOvLnyPJz_vVeYziwfshl5BcBLt3-mUQfk3HpvNobPF4gfDvS-Q_
}

