sprite $Icon_governance_2102_blue [96x109/16z] {
xPZdmYih24MnAxBU_t5lEyLJafZvS6xV_z8Mk44Z8nSKgvffZNA7KfjyrcpfB3laRe2D4a8P1bZFuHIyA9-8Qoa6i9nokx8SMQK0c3txNT4IDgR9TSMwNDak
Jsjqkx9FnEsA_oUhRDv6s9lfRsH_C-oTshlYT2hspMRqD7UGj3bCV4vLKKQIcvIg20IvJtzd_l_y__dXPhxDM_a1pl3_vwSwfc5JMpxF3yrOiXxFyjidhFRU
rG3euHm_JM3M-DqjmV8fVW7czxIaGFFo5xvjtdNmynChaa7rywD1sdpYuIiyAsG2y_8BT7cc2it9dzZcKnS_hne--zZ57vlcCgQBRupTkH4S_BHRVuRiu1T8
kvyt1xzkpoQZE_WDPCSVj_AdbnyS-VlhAxxw9YZoIWcAWo_GT_ihUlYARSfhuk4NAA_jQGx-zW1JY3v-UtK2PUZYuyjytgB1iE3b9vv1meJYlvyqcF5nzWpn
ywM3vSTtHZt1b_xpTJOqm41FyAK0z5Ncs0neGK4z_0LK01kjbDA60SpqgV_Lmr_AojAwJYkecxyU_GDWsbO_AQYNlnHYZE6d8qB3IxuvviTjW80PKMuB434b
osq1CjgfSbk0IY-et1P0AH6Jsm90b4a-4M0yj7-AL5JSqeTyfOe48ubRZn3fqzvj3Bb5W_vv4wSxy8dFMxUZT_2L_lM_j9x7btKpo11FuuDHLYNGy-xeTy7w
MNp7ma-Zg4ExqQH0Tl3sJmxwmLsGZFx8iKC1ukEnRnmAa0nzDWxb6_1B0t-HywkPk4DpD-PuVTqV3le-mGmQFaeF2cLV7iiVjjxIMqdqZ-3RkqklCDDLUfpl
zqQQb_keScbtzcjBI1Dwk5QhJHKsC-PxFohoXefTJNwDTNkJqkPRkyn6V9d3sAnotzDeV4h_F7ix53emqkFSlVILfEQVVF-3lfRcZJ1haAKoMNI_GZFMCuZK
3Qm5EQciWBKOsmHcaUEApG30Uf9xbBlPo795lm8
}

