sprite $Icon_graphs_2301_blue [96x96/16z] {
xPc5iYin34FNjAp__zptBfLHQNtH6YYf9sWbCzjHadMLBb46QF5tAhuwenxedP7Ynyk4aAeGCY1rGsZnYq-h-CKNEVtgMaT4ARvYFVbkWLtchr22V_OS1EBQ
H5W6ttBv8uPK_emncLzyEUNB4_azXcE-ONaUVyHyp0-WXL_yuXU_-CKllWAouK_RAw2_l_7jvN7Qy8NaTxwnIyXcJDlZFSxywB_m_b_yuXU_ZpJrIDUIZE-o
L2g9a1x-QHhXeHM0t14nqSfVC3zgUhnhqPp00t3F-W9zw_HCzzYcnX0pmE_nEM0j_17hVSOL8mq__HlV4NxO_4JooyPl17xRyHkPBni-8zhBViQSaWsdWysP
KW46EXkIDXk_fVcCu4jonKZR-Gxnm-KdD2NIoGqnyaTIVs56_mC
}

