sprite $Icon_cloud_2002_blue [96x77/16z] {
jTW5ilCw38RXJsPRUlU_t8kTFuVIfYV9Cr2MOMIez3whOmN_yrcJhcHjyKNqh8ka0H2pbMIIfLo70woY2zZygRTM5-1PPxM0LNQ7DKrds88esf6sJtyd1tGz
KGBQcV1HNWzmw7SAkEcLyTi6yXR-gGvTxxFOmZ_NeUgWLFeA89OJfcCcP1rH7JP5Hpckrteyje6SSccZwR04NIyKXnX9lz8WlKopQFerP-e9MoUtal9q0EPG
TOhJjMiHMUTKujdSPvsrdyyLgawRZDsDO6fp-GHrmdHUsicW6ZHT8IW_7w-XIwpl_SmEZAnB3CRtZPjkEcV_d9cmagwmxJ7QBEYwL8Vvv5GxhyBOdZPThl7e
j0L3DvYFnJe8tIAOaX8KNMuxQ0QkcpX32gfkKWaLGhS9oc3gDfFXDDscuf1rcmoGT9i4OBgD0UX6T_V__laFYcvJY4NNRJghuRgDqnAa6wS_oHcwoS2bUZn3
XxsRdLNIuUDtOdh7n1_7M3buPp8TjyLTHD8hoNalVWhcyV923jwBRxu5JO4dFLE2AE_4JqwamzMZ2cxsHlmIHDOc1UndNuDbEXxV9dZwbXtqf9-CnrqO8jpN
QCMqELfCB06iNf8sdo_lZJ-yfxsQaGDHdfPyrfU1DVtFIYcrFOhFA-kBoV-yQaT-LAm-fttzuNiEpAHF0eZLavwobErJOcNz92-8porRJgRtF2kc58UkSyoX
QC-4eNDiGTrU_KFQT6WwQSkV4ZpuchrbamOKdJHvJ7FmXVUy29sobPKDifcbb79jVJW00VsQFylVzv_S5a2OpcgmVjpVKWzeEgs2Pp1zOuEkymh4plwykYwG
WvtukUiAQQ__ohf4SantCZUzxMy
}

