sprite $Icon_email_2403_blue [96x73/16z] {
xTS7Sjj038LXR6N3V__ZfWSfi6O82vlgvrxqaNfSB4SYxMHHZYeYdONfKW6kNjFJBu1we2VeaEGCXKCvOCe0Zbn-voCy0Pf8lU1gUVedhueqW6h7o-AxVkcZ
VlRjToMjco4_-L9Eq9RMZVD59h0zozjQyRuqXRCysuqEUU1BEK1xIZVUjwUtnr3_OE_xKuYd7DQDyzteFTNDOz-DGhIRExxKm2ZuXU5zdoqo2hQmx_lI8wCm
hPjxlcqNFT1DoBUp2dGJzQNT60NRjAA-dvXuYzuFZ8Bl9kxRdJFGJS2tKPWFksaIy0CTsOG4_C15j0bFyAretqsARmkbkieIV3yATiapVTlWhPjStsvGrask
RtVEmxh9zsKeDiuhVAcdTPFhMxh8Kbz-dz_dDaTPv9TTxKNf0hyfe9S2p7o_0Vj7g4o5BTilYZRRMg4d-piqiODTNCc-iejOElHSV_mur1VxqldQhQ3ZME5F
rBvVwh_vVNiX9tpwck0Vy3Wvllfy-bsIVpww2FVyDtyizK-qhFGRNBsiysNooenxllIBLsM_wOlKFkBfD_fvAXd-c__crvUp9VaFyslyzm
}

