sprite $Icon_automation_1302_blue [96x101/16z] {
xLg7hkiw38lt4l__SzzgG9mgKI2WVhkyzwoWeJLeKns70t7W1ZqSUn05jrYR5bX0pnSCO6oXBq2zkzw1j8E_Gswl1wxx6GRMSGkW_KFul_nV_Yz_cp9R-9G_
vVXu2ZTzVTdyCrrY500h7rS8iFe48ENj1i3crrH5y08fYFQAF4q0Ys5b0J0C7ydZVOKu0SmSgm1HLm6OZ04dPUHY1a8LFZXqvfwkrZC0yZG0qdZ3Cwe0ai-m
ccKz6UZApqLy7Xu6WBO0pCXhedgs86zCQO4tF85DUYL1jFSMrwlL5P7i7p0kiXO6p7GKmk57Q57dz7F53kHZCoOGbJOToArx8g56kPGxA5SiB0fBvS80HAXa
6smgM-rEsPSjHKcfUh20wEqMDrK0bdCEFUlOF6hZeU2VKWLo5XRYrwXlocROJCI320nViYmx2-lLgCrl7-39gz420CFRAxMOhwR3KqoM9Ap5OlcsM11WPUTU
EV8Pk6lJv0MK8ou0mzwIb2JvATP7n86pffLEw3chaaUZftdNdtyqXpR9_tWCCMJbwCNMPbJyFD-jmcEccslHrARYjpJA4ItVvfHiRPBVD6q-15ADtHOjRMf-
MwFPr4e3J1_I_BOn9I1RAXHJcvhVDjR8j5nF97Y0AtvReq1pyskEH7vgrCy_mKFBh47lHksy_BOsZTv_L9yA5CUvQl2R-h7Z2sP-X5xIrlzrk0WYmVQrPts6
GJPB7zIdgL5xVnK1aEnxDRyrV9VRWpXEkjZJ_WnhFkrlyqbdKq-WV8ElCSvbOQoyeDhazd1grBQlEEwTHMdJniAwQeL-M0ndzBzysW33nMOuaZax28PtJ1PB
aA94huGXQqqJuyG2ciamW6x7vSGCzk3nLENIXyPT7ZP1XXBcPbHWgEPinOIeGN8hCj1uYEq5pS4mwKtLhpIHhQ3vyUTcyE3cGRaT4HY6IUz-WIdlrYYDtnua
OptyYC4Op7IjYCPJou4iKarJOw_rB059Rfq3Asjjwh-LzGpukX8787Hq7Uyr7xxiNC-VDlZe-7Bq5kxgpNv4Md_xCSayhH0x1mM6PUWb0L9INKoKVP0Mdrx_
v-IHE5Yrkyes0DT6LNb-_s9cFLYjlW2n1b0fryis_untRxy0wpxZbEEdxq-5DcNM_ydxTr_-B_-NlqEi0QJkcbBDLortO06ZAEGoWV7F_lmI4GQk45zpVmK
}

