sprite $Icon_security_2204_blue [96x119/16z] {
xTX5kYD130FWOhJkVzo1VCz38RK3GzQ-Vxdih1AunDANu2EoUedXYQaBPrdrINZiecEFqViO-X3fyGdwE6bRDwBRsgU6yMX3bHEJmrdowLbI7nf-wXgkBsv6
Cvy5m8YtbWT0if4l0aYvFu8K6mzWtNryN02AaP-1o30LP056e38CDuYYqvC5yPW_WHNeB1s6JTM9-DVMWzivjD5yR9x1tDR-HJoRXdfnv8T13mVJ-0T4OSQt
VrJFncVIwP_G0j9nFm6BlUuEXcpomkLiFVI22ldhoHO_0uDSVp25tAjWs_mDuSuxRVwa3fnqZPO3P-fC_PL-0PhDRq1vY-----wxxxxxKpGQGBWmNqwyFB9_
ZiWsHiue0EZXPUd_Xk----wxxtu6oWlz980aWy_pMc3m6LuB33x3Rs1h0Utp_Af0NLh0-ZmVl_f12rYVvyF9rmBMv_aFNmj8d-RLrmBIftdrjO3qULvzBU1y
bbUVBL2VvTLd2zHdUVNP0lLPNdsYWFP5_nK_yxNWKN-5wtvOZ_gvXbj-g9dmoQXFvD_otNVVVVVTZtj7Ws-8--wxxxxxgxyi2o-Fl9Z_3
}

