sprite $Icon_orchestration_0102_blue [96x94/16z] {
xPfNSiCm30N1tkz_tFHm7fYeontxkvD5t0tHjI6UWC9KH1MPAgWyKppF8sqwKhZZemU2_QME_TXL7lkbgpZsQrUXVM2x6lfuTwMnd-0E6VlqYttrllIbNyil
ZVTHrLPP7zNORwWuWO31Ub2PAm82LpuYYW078bKst4J44Q2OyhGI3GDE1GV4smxmKT41L9aV45jpT7H0ciiNHPSOWFdZ0_A_9a7-02h309xFYiuWztSi84F-
A36hLJSAkTpJAYGWQbGk8GQL0P4ho-kOWB3l-rkU_hFO1ah-vK-_TbLvlp3L5EztLUJpzt9zwKl_yllNfVV7sX1tVFzrFAyqGemJbAA7HH24Ixy_NFBzJQxl
oVU7wRxqfN_IVaVJ-zqf-odlC_RkruWZcjolwHdH-U9N2jLby-5Xy-RoUV_GUKSNmvwVn_E5pDwjoKN44EqvNsWSEta-acdN-GW_tqdJvpjbp_cEVFvEzwKl
VRc-T-dVjxm3
}

