sprite $Icon_people_1802_blue [96x78/16z] {
hLY7ZiCw33iFUOh__xbl10WkBXMbxfKOdQ4r2ChspyS8kNO53kXi4d--2HbunQpVMY8qFGXRoIc6cBBK0G3ewIli1vM4zUjyB3h-d8Cee3MOFqq0xM_1Tm0r
U8lFFnGfpQSIL03oCRq2TUC_cyY0FYSVneTDI82-9O_-KGPHeU6zl_PFUZ2Nw7qCO5T53SZlorWnjtjRztfLzwfZ1XHB7wDPUTMz2XKWcKvqG8rkAiO6lw9p
y1FGNfljEhAJW02Hefz0ETx5OLLxeczKlxk2wiRw0eJtrK0zZ43nwwTlIwX2ZOxhsl_02KuUsb8aSNcC_lKbuc1qCx-kcGSEQ5k_3m1BVApPa-FGT-5WLsL1
PwjJTRLgEuIss2D6_fydrPSHKP_D95bgRnZN6aEkgSZrVtrJ0Io1kYOue87otBMp35nQUFw1Fq_KZqPF0cxrsw0N_kAoLzXU4u6BccdjUBvNZryKDFQPdqC4
yZln1z1spkA_w8M2Tkhlst0o-JdeZkRnEpFrFVw6iSNF-lVv1Rh7pt6fKNzXBJ6IunqJTNbB-k7i696qOzbknw3UHF9w2y4hNRWTu1sJffE5TD_xWN4xG1DG
bapBTdy384k8bVQFb0qZejzRTbWeqCxFMO546uWz14LzFNPeJJ546G0oRp_tKAbd5IVu39XsJmmHQFHTKm10DwZwPWB3Fko4bA9TphuLVzd9Tny9w3_R28-W
URo3XYV8BtsamalnxuW4JnWdFSaxTHoOukr1Hd8mJWVB1xsHkG9EMuP__8sdlrJUJGnWoh7p7BSBL40Uz7vUiCn8qTSBJVj4SEMeIUpWvzFoLGF4Fey7typw
mOIPERFvU7NGtSFcURxBq68rHbv2qS3P5oRbQHJjCK1_dXJ2sBqyS6QtlFPoKaORTmtAgLUWq45wp-hzis6_VfcVhjEwbru2edTNzNnLb05nVxLI_jLx8b_O
keWfq9kqnldMfwzB0TmpgjJBkbHrtzSOV7O0kcCKhgzvU-XhgdNpZb4SxVBMkmEo68KikF4r3s4DSbu_9gpGEr_pdIcyc5kycxZpq7E_0gYFzMFXUq8Rj2R3
kth9mF24aDg29mNmrKkn9s7Ssg5xLo_DB6htTVxipgnIdc3x03BjCEC495qX7HWnFCFWJujQ_mPk4VJdY_nSrty1
}

