sprite $Icon_innovation_2903_blue [96x105/16z] {
rPc7jkie34K564pH_l_FdSvBC2l3Kx2dx5Lk2HnB1z4SPS3BxoImK-Htt2ZO68doEurlaD-9N6cvKo5r_Me4wActsb608fq0jUkBaTwbGf1E6VL5mU_fUr0P
zQlyu8Isfr_Xb1zKW2O_S0tAZdu1THTzbHS1QEvh_HCuPF3x8dKed5_hPuZo1hGAJjxmJSFt_gGWRpYe6O8CxFW_4Y2V49_IZt0Ua9_IF-7mK9_Ih-15qQVq
5Vtp8S_e_sdD2UaP_GYdI83oZ7xvi_GL7j7lmWMEkR4J6tEKVJU9iq7LhZ-NOUu32pexvyN6BABWkbgyGR_9m06b_qQRKWjYmeqQOzGDmhHmY8bXcRbknEaw
mWcIc9YMoGpdS6wOMfk8buWSuDxzg9VaYXYO7SrZX0h7L0qM2lYB-suql4qJU6Dvg71UFp_7z8wDyeoWqsA1looj1k9WjrE8yshHBkLiOCotGfaT749Gsm2q
IpNgt3dmIcewYIq8xyaVm24pwVt_Xy6WSO_r-cdi2cYm6JGtTleviWhgXzrXmPoiQz0-1jPU3mYWyfDKY2zv_I3VFpw6JWl6KFmhmCyF80wxpfhQhGnwaPzn
5SZThFIJxcilG9gN1QMt2jtA1GrYxrYTB4c0fZyx55dHxvoXzSIN10LgwClKSd09uZBqncjS0IWkheQhBrjH1-lN70geBz2MezLy0pZD6ohHAPHLAn-1uiM8
praa_7rW4OZYMZl4nAYGFhfei-MpJv_hhCWkcGzxlLUeiay1WamuXIPtKAPfC2tqUrHcgGgwBp_7EkUqppoKUHgJ_GUaiV2ZtCand1-d8yW-6SfqNRWHfn1U
ltgvcqJt99gM1ViHlvWk1_Opie8OC5-neCa3P0ZTgFzZ_FNblye3WBwzThoT0yem4mpO3lcU1moAqARR-Nq4XJXTDMyZZaUH4qYtXNwancM3B40xOt2t77_e
DuVvtyLjBse0BKvPLG1GlnjzEMCGcV7npBj7kCKnONSh2ykTAcqLqW79qC9EBixGmeOpy9Kt1fAOAHXeOaQX_2GAxflZZkdjeTt-R7gvRUI4Q9g61ioREAWO
0NqW6ECBOhkPymlk_MBOBpa7pNuODtyx-5n01SBUxBftcqaGxHkTFT-dPfZ2a_NWeThhsJwxdkWHSyuDIZPHG7FEQMqDMqHPu9GDvghx5G
}

