sprite $Icon_internet_1501_blue [96x92/16z] {
xTfLWWGX303HnY59tV-uw-uILbC_RV36VVZrjRAj1b2ERPL_v8VVBzVIpJAv-XKkbXszM4wMgzyWdIy7Th6z46__kEylL_-OxMAHPhqyECkVlt-67xvC__gD
lwbowvlwj-B-u-o77txuAUUqpS_306paBVxafkdl9m5MAwKjG9AtBx2kqBH0dFq1yzvLDLpzPApxbyQIfpyWtxihmV3qbNL_nq8zVMZtTtHmz3FK-tig95U_
F9gPly0Fly-p5gnvh-iz_RE-y6BoUTzKrKplTxd7FFnrFDlwhtxuuOSVVlZXlzJFzsj_iHgVtyFVKVZXXx_z_mc_lbC
}

