sprite $Icon_governance_2105_blue [96x109/16z] {
xPe5Tcmv34IV6U_-bpla4qvUAXxhimurtfBAaXelFLng4-ZPN-SZbC5ZZ1AEmcET0CoMLWqmQpm0NgxmI7nMoX6dVEwFZWYtRxlYtgahFZZLuhuhZ1kV1QUK
f-c92E5kND6UeYUpNVA-Atfo-wxeJkckx3kL7w_AYUjJ6QuYB9FzuMmNJ674DvrguO9qMGR47vJ_X_-77uCfFu0fFvho__3_y7qIA66VFnZk4tm5jyrlB85R
_13otnMeCBt0bmHqlCvV0W9Uvki22o_mzmJgkbtXwm8wNkSl0G4ly5M1XPVuie205_YAmC9ly3M1XTVvke20t-Kl0G6_ory20dwJlmIMY0L_2Ioy4V-QGBYk
don_tN_x_h7lV_lvjTy_zllJVl_RltxPl_xQlt-mV_-ZutM1_VUVki3Y9xltpmaWsxt_pm3r3b__r-UN0eDkz_chCohSFTaBtxgc3pi4MZBy01mWEQX6-ELS
PpeRl8F-tmmK6tvUrW-h0kPgt6HKG7uOtG7UnFtns4RzFBz1VEgZV1gVe3sMCY6SnVlvl6iYftjeG7ovwFfXyylh6zevV7sJhXi7zr3XxLPtyzYOvNMQDW8B
xzzlAUeHSsRue6VLGzvylNTZ7Sn-kBxmDm8pxEFzfmas8EtYes1m0TgszHGfYH7sl9b9F2FAHjSplDh2wx5w-CvNXYUCnnBav6VywbdDg6T3UzEMofC4arm3
HjpQKr3T9_GosTsBlW4pt-OmWNvJfM3Ip3VqPSr-fANWtgVVJ9Iky1-c-3U-tvIsKGCzFlEj8T3rY9sd8bmU02DT1oDK04RE7O0MJjAVfGthl2t2b_db_zhy
3G
}

