sprite $Icon_documents_1402_blue [96x115/16z] {
xTA7OU0W04DHtC0KxJ_kNNfL2a6aIWEyRmCOtH5U7OQtlUKNklhAskq0e6sl-oryV2S9YFr60ae_aO3IFpOIKFhXAh3Eyqb0wfE0r2S1gKy2Kfy4f3u9I7qI
aFea8FL9GEgJWDId0RtF0q0L-2IWyrb0wTE0rkS1lNyJm4r0vVE0qES1eSy3Gfy7vlbXlmgC-sbvjeU1KPyjtGUgthyHRmA3VcCxmirAjnzZw5YtVm1nff-0
P9_EldtxzktRjxz7kWoKIBTt-H7TYpr-wlTJZn_IILU0Uj8blq-nRz--VVl5ldtxxre4uan_EVCYy0MpRz--VVlsPys-VVkjJ5l3Zzz_
}

