sprite $Icon_detection_0504_blue [96x88/16z] {
rLTdWgiy4FEuDzt_k5ynIMoGmInlNzEltIHCqMXahEv1h8yfLuoe9SLWjVf161V7m8mItTCaubBjvUOOl7FMUY0u7s8gTUZbopcqpzYGepSoP0Ny-q_Zmhk4
4imNAlTbAom1KHrGaVQLk8I66kvrOLElAA6g0nBAiHmWRTqMBse1NxSVRhLuu5XKv9H0KE9QYXglcf1Gssy-N1h07Wi0cB8uq9hCMVJOIdVxqhpQmt5B-JCI
are6VSfCjbpQ7XOm53_tSSTvXjYYKsi5wRXoq_X4Go0DeFRQdyJlq0c0fVWezd5y9l4G2sW4QPR6a_W673-u2Y0AIPjA8_tCc-GT2G2g7va47EjVRZR9lz4P
G35NOWoyN-TDyY1jwV8bC-2FpfTGQ4RZdWKootD52PF8JIQKtO9Kjz7ePcGmsSicm_Y9oTio9sgJbSTai8cpB6m5GCVBmh4N6wUF589ZgJmFjbIifhvrddaI
4DV11F3hkHMmrLh0ScL-FIJMNG8yMKO2rFh0uOzuv058RwtwtZXniTp17a_sEYcYZfRXIUhp7JnCd9aDGDLA3PRHaXNIjTABMVRM-uUIU_ZHCXpWk6_ea_7w
8DEcN7sJSx2CmhpsbdXNWHfeA8qEdgBPrEhkq9DVATi2HJjwlGw5jsgq39dImplOIqNv3A1Ke3V5gkjQ7TIJhvHY4pwwRC5HUW2QMax7vYnHHagtfkzczbgT
G0ggzEEDx8vRkXeL8xs-tLc69gNJeNGkDRQBKQllfBAWPtvsyCnwxcuP6aXBUdY56QRlysWPYGhYYVFXn32L3BrP1k_XuKh5ldssMNP-6_7qCULSSkSmRpa0
V6K8vE2hRmFcNKb5vJVYYgBE8II8PjNcP26iEhmHiuEpn-WZzKNF5TjAqMbtCI47vnsEkujE_v_PaTqRiOwL79mnI5f2TpD2xaFPB2Erw3mgRY2zek-6nqCF
HwqY-OpMrM82vdrHplfyKJ9jODYc4fODb8t9JAsINV3QyikeK0CDqPoNK7bD4lBypTm1DQSKOz3zAfpT1Oioiui8oFPmfaarz2yySKZL-obbHkdCKtCXvb9g
hMxGdhuC7wR2xeYo7F6zy1m_qYLwfMxMuPbYVV3wSxnPnU3jv2W8btR1hsANFsVfkbi5-GfoEbhG0_HWrPmuyl6syBd0t6IvNOtIMbsXxAcGZFEXhrrjlgLc
pwUvOnUCjOdPSh4qqZfz0FTgsuutF4OctkuY04LQxTLT2I6gXuW0NJWuV5QFiTskvIU4xoejtnvUMwzx1-S997ybl8WsreMOAyR7ugdmTG6IkWUFFSBw_TFK
6yhXqwVcwCp2bEdJ9SHxxvmr-knGIJApwiTWfglX3xuDadPiUBBg9s3trnEh_awEMbHNoUsUWaTQNBDgzLDW2e2VL7m_neBwYH2lrLy8BUedmcNKdvR0n0hy
lFXsEu1_Nlb0ikeP_WK
}

