sprite $Icon_differentator_0803_blue [96x96/16z] {
xTf7ZiKW48HXCC7qO-h-nvsC4Bj6eYRMl_Vdd7c2knG-It2tmQCCls2dSdbAgvykJsMijgFL3wxIL_lovSlFFU_xfIUlRx1zlwDH_OVVJvRs_MJNJzc_iSOD
Vqv4tVw6-_kF7_dovLUKVVz6-P_tN_dovSVLZqxVt-9JoiFFy9UgjppNErTlAVpZb6AVNzph0_lwHhW-_-dxbtpvyYiArJVOZ_Llt8plOvE7CVRlv7kaV9-S
_Edj7zFAd_OxsiAVzWreap_lXmVG1i_mGmVQu1b-wC3a2NxeawVumIp-gEiR-_-Exe_ovSidZm_Xl_-on-Uy
}

