sprite $Icon_endpoint_1903_blue [96x79/16z] {
xTSvZiGm34HHaLwaXiJxNtV0k5q3_zaNVZX-9S0HUtng8pwzpJwjBNrldvQNNpwf_Dwn3r_aVyKll_pootTNlli7-1PnNFj7X05VDNFWsKz-jW_mBGUU_UJj
bWy6qXUyzi50-eBNFXX8N_3Q1mFf2rxxO21zmMiV3AGlUEs3WVG5htqmqFDBdlXW84iU-MmWUUQJ0S9plzbQoJEVP5RtnSVweulskyokX16lvk2Lkgbwj9iz
9F6T_xVyyiillv-WCKvGZqzlduiKiKXpRo1wdlAy_FBBBz-ksoDskmxnAt2Bl9xx8Uw-5m
}

