sprite $Icon_integrations_0302_blue [96x109/16z] {
xLg7hkiw3FDU4l__TnzgA0bw79zcwQrRONGphfOfnkQ4kGe0rHaTyunkx5NWBGCbX0AmrS0lG7mzHg1eu3EgwLR16ku1akcM0FlVmpS4sfueM0QAn3aP3IE0
QYM0Z8fPGZUoHiaI0PICddd0cpyK_ul_nOz0r4Et1G2ALO9Fo_wUL5nF00XehuTmogcDgOO3r8UY1toW0oGeLEBMG-K8tUg7lGMSblo9_2aC5Tt8TLP3fVBy
0XkUu4kWEVu6pxKGGBO0-VMB2iIvuz7yU_wx7WO_pU9gPKTTMKr_CfeiTQolNy9GmUkJTTbbbpKb0CX3_MxvcdUPM5d_213M4Euxljf9VvY6ORrgs5OtifhH
nsF_yQt7PiQKCj30Rd54cZf-tj_YuAGDoZ6Q1pZxKF0ocZXtZY-ryJFTW19yPi2RXAMhR0anJuwy4qzNudkTSsO1ZOiFErYIEd9dUinOvrakimR6UcytdtEx
sYFpbcuRvf0pLtkyPrdorBQShVRQtXCFpK4lorVs7ZQ7yCkaBbtAfUJa9dLU3kFlrQND337ETg_EJ-2FUuYWippaiSvFuKikqmBI_q-q_NdiBvPBamJh7BxK
OfDd391_xm4iOMYzDC_Y2-wsnZ8CyxHzwIg-MDr9rpnis9VnWq0D5_NFu1FOxiefz0Y-1zAaL_edy3DW9u94VWAVqCokDT0J-DDUbu47yEt4_QBJtCPtqwuU
0QUzVcN_w-VFlp__FP0rwzSqtVvZl4B_rE__-lkNgmk6fNU-6sXJ4UdY_cj7_f0wa4iZV-WlRl6VzCv_qZt-usc7ln74QCBVRlFF-EAVSU2VCkxK0_Zw_3ag
yd_n9VjhsjPiVd7lyrU-gcsrtVdBqu_vKOPEVrBRQkvzVXHAFCw_tUg9-RVAE3lElydCvlTmQdxdD9lV7z4Vgftg3xhwYRx-yqc_uflwrKtzpNxItxJrGyi0
7z4_wsdzam6o9_JRlE2d4_gjelvSunNzl3y4NVrV-Vw5xlsNx_sfB_uN_pzuVi1fdd_GFx-HWRm-AXYZJPZIztoH_lah_VDZbe4IOmNO_dlExscVF_mB
}

