sprite $Icon_graphs_2302_blue [96x96/16z] {
xTM7SkKW38LXCCWq_U__kDjtxSjE378cdJFbzYyKIN6cU5NlNZ0RRCi_ilmjMhB37YtP-F09fWOsjM-05os8RVdBN_xobx_yuzqe4gnKcFMb0Q39dHBf8frK
ILE-h_oDdfQKwPAxHHtEjT-WYdSkPD3jvBTuIkjz1Sg4N_Ytpw3esNUdrCvFK20C_G2fUp7ZUoYkqOP-HbttQiOlu5q46VdwK0K1memVOF_rflg13z6T0ZBZ
D_GFbgzz3y7koz-l9TX6wvV7QujZtolrU7RjDyfZq_XBlr-rW5pwgVjhrGtyxjGRUkbxFJa9ui3lgoP0klATGFlzscSeRkX7aAuJhdoNW29Hia9ru_dJK8b7
TYYNlXCzHkHuVWh_PxlqdTyhqD8sC_y3z56__hylV_dBN_xoUNb_bnVBpekdlJ3lNYehAzvRlcFd5J_y3dhR5yR-1dBNhzJdVkdvIvFR4pZ1pFt2Vizl53UH
SdE81OXk8X727J_FLfwIxlXAkhqG-xRj1sc_DdiXsClENiZsjh4tehtjxL-sByc-MVkHscU4lIJiCo90kDSiBzIIIZRF1kk2Nh8U0aJZTRrWGHHxFyeJ5_0T
}

