sprite $Icon_automation_1304_blue [96x101/16z] {
xPg7SiGe38PDDw3l_H_tcZDAri3UpgoukdywO_y8IQ12ZXVWAoFaT8SDl315DvgWmna7D6Wcz0doRFo4OC5_8jDnf_E-Xqe_fe3o3-7_y7_uF_obIolkNVuG
_TDJkDp7-vg_XK560NeyHWZqim6IxY-qEVz8bOGBQLJE9NbeG5UneW3LBSFQmmo-0ItwBE3lpwgKwPlIwsGBkFpzi3jrxG7gO4IKfm1Iz8Ndo08IlyGggz0J
uRmjN0Hu8OQx2fGEDAzZSlE9ZZmmXOw-y0ngf6iHYl9euZo6kYI3botX--3MeWBhSjv1kgyq_fpnX7WOeu4VVDCG7kembHLKAQegOwXHrTJso93LLQsXcqgN
OOy8PJWgh7rqEEgCVHJYiGqdRELFi5C_Hu6gkslF5dC2FQubQAtbttsjBP3NzB53Edn_4aaS09UhBR1qdiPNKCmQ2OtarsYVV_vXPuPHPA-9bGMYglm-zZQr
ParnkgPWGA-AloEPnB6uzXKutaU0k6u4cEWdhGiL0q1PyXlihpL_encS3o_nAqgjzNSHGrrW8Vzk_TlxZmBoCjhiz4zNmU_RNqamIHGZI9eVUjLR1DrPqLcq
W390551PTU3S4hwqxFQc-OEh6W-J_cQQFuGED7U4vrLq_hFpGILRE6I5i36zhMhO7QW0UHz_XAtoPwZ8Flw6H2WRrLEqUjzLe0QesxIVjPcrgK6WFtSrE3Pr
2BJhetROs63QuQCHpibS2XyDV7FGbQ90Swy7HCaJtxpPUkXJItZPpw77mJTNVuS6j0gK5yijwHhHR_AEwz6sSxv-hg5FTtz5zEA6vk5WZ-l1eH2SmnTD55Ii
XRy4a1IoBbJjW9Hr_rypZuTkVfbfjW2ZeRBmzFwYnNjYrSyEVH7laJGPNj-_-CdrosMG6KBqxzvFkTAavV_5_Ts7_yF_uL-t3JnaionrWcgLk7QeCQO7nDIW
_kF_VqchsG6lzfD_1G
}

