sprite $Icon_internet_1505_blue [96x92/16z] {
xTe5ZWKn30FGz7VAzVsFk-HbeQLcCHw8y0rZYr-VajrI7lriRid_o0-_vWyrrNJKBm1vhAVQCKxxwR4sR7lCm7HP_uP5__3wMozF9JtNtFEVFp_33t_qywal
lbVocx_N-OoVVNp33p_yyCCFFzNawQUDxkYd1HGldtmrDv-ycq_UpIVlvfDtyyax-UIRkVcVUTtNUTs_AVjUznk6jFQwZo7micy3w08l-pQ1Bl2gpmK8lEfp
0G8l-bn04tZL9odmea-q2hpgSm42h_fSmDEycuTlQGELQ-_Yssq3v1ryBe2ybs-tsNx5-stuuOSVVlZXX-_UF-7Nvnu
}

