sprite $Icon_cloud_2001_blue [96x76/16z] {
xTX5WYD940NHxy7WTl_Z3dKNPqLA2SDlfPK5k5ZFizo6yyFi9UXALWQVU8swI6W0taiAPh8GSvi08-a2rd_iTkj4C-giujzjD7IWcywm0PxqZJ30euwB3bKB
oQ6SoNlQFs0xdf-cFUte0f6t_4g5gkUPl-NNAkI7gwaE1tnCFEWn7Q8UaGUyINhKP6fV-R7nacACgVIYXmNsHn0dqA8EAM1QQa0r7JLfUoCQGSSb2EjNOT4f
SpM10Ldd57nrzqadsVUD14MdTPgsELtdPLoRAcuwBy1c9Zb5L_2j0PG9haiCokPxGe-wHFiou09KqqKgb4yBCe8k4oOqlUdGTAa6VUCurobGzKE2gijLIFgT
ELqtwBZzk2ettS2S9Yb0rYqo1AaoTPD9avoicsHS2TTT35AbwpQTDYcwJM52r6qYGD1j0e3fDWQW6-tjFzLzSRd_zVrtzfNb_JjfsPzzpLVzX0_gib-b80io
qwQnwbT6PUpq6saItG_q9pL2MFS7nKbWJ_S3H4tgkX-gfQASzNI_CgM2swBVmegj-lPZzavRNE0EM_GRBaaPuj6-B_eHyiyhT7lsbyB-_PiptXujvdkiR_Dj
rn66NTktyVxM4ynuPJyw9Br93lMwVWMFNxvHUx4h-bOSPjZyowJdSAuVSWUyw2kh3e3FTgnVvyz0DMrBpG7yMDy1l2MjM4mv7kk7dA9fwVny_plz__l_z__l
x_gB-xy2
}

