sprite $Icon_integrations_0304_blue [96x103/16z] {
xPe7ZYCv34MfdFZkVznDmg3WmiAarLCR-tSEVb-14ad3ubMbovFgp6_-AJ_Ltj9Z_300cE64c_je1d-2BWKzC1W0yIs_Gh--VAOEQerV6J_-zrDyW66jVu2o
DndIX_m2mS7Ff_oAsl6Zx7Ll43xcO_FRNg0CGvxW1uMr5cXyX2zn0Q19dk6B54MBo5Fy_TV_EZ-49_bvWRRm5By2WDQNjB6y_67m8woI1x3oIzeOBdwnpkxS
oI5EOCGVnnujuk4Nw-ncgDSsq8DatLyz_6pXPR6kdL3GQnustyPNoFTqlP8H8NvyqDjZqzHgHQ0VBnsYfpuvn2Teuk4RU2CsRVuPla0H5_y8ByeI7_y8to0v
-IVuwChw8PN5Ei3BS1GjPGAWDxmheKEpwChMEi2BjVff0RCcwSm3l1Z1cHNc7w39YvnuMQmtwr-l5B1Ey7kYrNEnTxHUAa6SgbTEl2ig6hxSFwO9pFZd5rEI
B_Eld7XJXY9VvbyviRv9cb_aI-Xm0sJ89j-lkD3RpQ5ophTBCANzLFwYtoxM_5N-k_5cY3-PNszfyxuTurLz_z_uNTdcyvw_k6lVl6mL1_zy_0hboVMFXe4p
Vlm6eIrThztGjEFVRP0K0CtNtmSiw_nw3QB2Q8DhYHkWoRf_l0O3qfx5s2W5cjoaJ2V_CcZrT_s0LRYQBgCmtNpJuEKu993GhsRbflLf_ehhbPyXBD0Ydlox
qXyAOkXQsO4sQC5JFqnmNmKLHf3GeK4NL_qpmMym0GMcGFBLRvqLVrTIZq47e8j0_h3-3CjZ4CgkmPJ-QVqShXdOQX3TzV-1GL1Ntjlzoub1XUpjluuC5khb
7nbag4x-WS5n_nxT1X6wdsyRsC-VX6Jm3GCZHeioWytV1g7qqU87CPeMW2QJlmqKWEvzZYCCO3QW1uk_3LXJBOCCvMfaohutjPfyKKXxKCcAqRIfx7GJEg0j
lkVdpRMloGYelZIIQG3Kj_oAEhDpKcwDy7QOVhwXqcfw4vG7wsF9vekYqTxVStu6fX6Vv_mhUtPvY2-X3kD-yFCD_Vluttnzb9-XFScN2MkKv_XX0jZyS-Lk
ZF_xzJdV_ETUF_Oh
}

