sprite $Icon_detection_0507_blue [96x62/16z] {
jLW7biCw21H25PZx7_SNl-thYPHuFQ-cq4GdRK6qzcaU0KIupLur_HdASBmZ0k_mKT9bIBE3xVyQv_Vlyl_M78AioYND3K2CSoPI3nbJNrRTWUWFoRK7u2sz
W1Q0rJqRusa9DO2HqnRo0Boc9w0Ep9osaGsm_Vztm9xqcXhGjvMFzfA_VCU4IanTGWnOUs40ZT2NFitTPYz2J036GWT7wBbPXa-mmDM0IUB8xFSMHnwh7ALk
10jvCUw4G_oauQhVlfc0dnew4ShOan1hPnxFHXmrc03b19Ma-3XLvro01cMVgRVs1MJ2lbFs1qtVf17oryBOlmjG8a1-n3t9Z41vdEn1ijH_H9MHIZVJGqnI
rUmRONyNz_lLP97m2265eAqVkM6iwrLZqQxlikWZEvQLDCDPiNktp33sQVTrc6ykg9HBGzzfTerAhiVhGEdRbhH4eJxIuuKczw51VeaSln_HkEzdAeZ44FZz
rUz_FsHG7EK-_WLkCzt7FqrBwJR-7Do_gjo_73V49yNp-LNJ2dAjFgoOjZlgM_ci6tgjFgzRPuFBQ_qbh_hB_VtnW6FG6al1Q_k0h-SJxfftAAdj0o4Nvwir
pVvyg5HxFX_kZyy3gCziAnrGgizTy_c1VED-SI3xQZyIsTwFIDhvjVtEPP6GT-wdxzwKL_VhbjR8hzq7Qi1rjo_2ylNx1eSwbS0lG7hdVIbgUX8z02kNxsCS
qcBdlhV9dITLZ2Bd-J02nCPBzzNqvRxQ95s5yFkmfB-2rZxUxjlkDlRls_y2
}

